// Generated by tools/hal_agilex from a Quartus Prime Pro EDA netlist export.
// Load with the AGILEX_TENNM gate library.
// source: lut_logic.vo
// Inversions on ALM data inputs were absorbed into lut_mask; tri1 nets became wires tied to 1'b1.

module lut_logic (y0, y1, y2, a, b, c, d, e, f);
output y0;
output y1;
output y2;
input a;
input b;
input c;
input d;
input e;
input f;
wire devclrn;
wire devoe;
wire devpor;
wire gnd;
wire unknown;
wire vcc;
wire \y0~1_combout ;
wire \y1~1_combout ;
wire \y2~1_combout ;

assign gnd = 1'b0;
assign vcc = 1'b1;
// dropped: assign unknown = 1'bx;  (declared by Quartus, read by nothing)
assign devclrn = 1'b1;
assign devpor = 1'b1;
assign devoe = 1'b1;
assign y0 = \y0~1_combout ;
assign y1 = \y1~1_combout ;
assign y2 = \y2~1_combout ;

tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8F88FFFFFFFF8F88), .shared_arith ("off")) \y0~1  (.cin (gnd), .combout (\y0~1_combout ), .dataa (a), .datab (b), .datac (c), .datad (d), .datae (e), .dataf (f), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h9600969696009696), .shared_arith ("off")) \y1~1  (.cin (gnd), .combout (\y1~1_combout ), .dataa (a), .datab (b), .datac (c), .datad (d), .datae (e), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h75757575FF202020), .shared_arith ("off")) \y2~1  (.cin (gnd), .combout (\y2~1_combout ), .dataa (a), .datab (b), .datac (c), .datad (d), .datae (e), .dataf (f), .datag (gnd), .datah (gnd), .sharein (gnd));

endmodule
