// Generated by tools/hal_agilex from a Quartus Prime Pro EDA netlist export.
// Load with the AGILEX_TENNM gate library.
// source: counter_adder.vo
// Inversions on ALM data inputs were absorbed into lut_mask; tri1 nets became wires tied to 1'b1.

module counter_adder (count, carry_out, clk, rst_n, en, addend);
output [7:0] count;
output carry_out;
input clk;
input rst_n;
input en;
input [7:0] addend;
wire \add_0~11_sumout ;
wire \add_0~12 ;
wire \add_0~16_sumout ;
wire \add_0~17 ;
wire \add_0~1_sumout ;
wire \add_0~21_sumout ;
wire \add_0~22 ;
wire \add_0~26_sumout ;
wire \add_0~27 ;
wire \add_0~31_sumout ;
wire \add_0~32 ;
wire \add_0~36_sumout ;
wire \add_0~37 ;
wire \add_0~41_sumout ;
wire \add_0~42 ;
wire \add_0~6_sumout ;
wire \add_0~7 ;
wire \count[0]~reg0_q ;
wire \count[1]~reg0_q ;
wire \count[2]~reg0_q ;
wire \count[3]~reg0_q ;
wire \count[4]~reg0_q ;
wire \count[5]~reg0_q ;
wire \count[6]~reg0_q ;
wire \count[7]~reg0_q ;
wire devclrn;
wire devoe;
wire devpor;
wire gnd;
wire unknown;
wire vcc;

assign gnd = 1'b0;
assign vcc = 1'b1;
// dropped: assign unknown = 1'bx;  (declared by Quartus, read by nothing)
assign devclrn = 1'b1;
assign devpor = 1'b1;
assign devoe = 1'b1;
assign carry_out = \add_0~1_sumout ;
assign count[0] = \count[0]~reg0_q ;
assign count[1] = \count[1]~reg0_q ;
assign count[2] = \count[2]~reg0_q ;
assign count[3] = \count[3]~reg0_q ;
assign count[4] = \count[4]~reg0_q ;
assign count[5] = \count[5]~reg0_q ;
assign count[6] = \count[6]~reg0_q ;
assign count[7] = \count[7]~reg0_q ;

tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0000000000000000), .shared_arith ("off")) \add_0~1  (.cin (\add_0~42 ), .dataa (gnd), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~1_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h00000000F0000FF0), .shared_arith ("off")) \add_0~6  (.cin (gnd), .cout (\add_0~7 ), .dataa (gnd), .datab (gnd), .datac (\count[0]~reg0_q ), .datad (addend[0]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~6_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h00000000F0000FF0), .shared_arith ("off")) \add_0~11  (.cin (\add_0~7 ), .cout (\add_0~12 ), .dataa (gnd), .datab (gnd), .datac (\count[1]~reg0_q ), .datad (addend[1]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~11_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h00000000F0000FF0), .shared_arith ("off")) \add_0~16  (.cin (\add_0~12 ), .cout (\add_0~17 ), .dataa (gnd), .datab (gnd), .datac (\count[2]~reg0_q ), .datad (addend[2]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~16_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h00000000F0000FF0), .shared_arith ("off")) \add_0~21  (.cin (\add_0~17 ), .cout (\add_0~22 ), .dataa (gnd), .datab (gnd), .datac (\count[3]~reg0_q ), .datad (addend[3]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~21_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h00000000F0000FF0), .shared_arith ("off")) \add_0~26  (.cin (\add_0~22 ), .cout (\add_0~27 ), .dataa (gnd), .datab (gnd), .datac (\count[4]~reg0_q ), .datad (addend[4]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~26_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h00000000F0000FF0), .shared_arith ("off")) \add_0~31  (.cin (\add_0~27 ), .cout (\add_0~32 ), .dataa (gnd), .datab (gnd), .datac (\count[5]~reg0_q ), .datad (addend[5]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~31_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h00000000F0000FF0), .shared_arith ("off")) \add_0~36  (.cin (\add_0~32 ), .cout (\add_0~37 ), .dataa (gnd), .datab (gnd), .datac (\count[6]~reg0_q ), .datad (addend[6]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~36_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h00000000F0000FF0), .shared_arith ("off")) \add_0~41  (.cin (\add_0~37 ), .cout (\add_0~42 ), .dataa (gnd), .datab (gnd), .datac (\count[7]~reg0_q ), .datad (addend[7]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~41_sumout ));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \count[0]~reg0  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\add_0~6_sumout ), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (\count[0]~reg0_q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \count[1]~reg0  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\add_0~11_sumout ), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (\count[1]~reg0_q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \count[2]~reg0  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\add_0~16_sumout ), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (\count[2]~reg0_q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \count[3]~reg0  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\add_0~21_sumout ), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (\count[3]~reg0_q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \count[4]~reg0  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\add_0~26_sumout ), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (\count[4]~reg0_q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \count[5]~reg0  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\add_0~31_sumout ), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (\count[5]~reg0_q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \count[6]~reg0  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\add_0~36_sumout ), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (\count[6]~reg0_q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \count[7]~reg0  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\add_0~41_sumout ), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (\count[7]~reg0_q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));

endmodule
