// Generated by tools/hal_agilex from a Quartus Prime Pro EDA netlist export.
// Load with the AGILEX_TENNM gate library.
// source: traffic_fsm.vo
// Inversions on ALM data inputs were absorbed into lut_mask; tri1 nets became wires tied to 1'b1.

module traffic_fsm (red, yellow, green, hold, clk, rst_n);
output red;
output yellow;
output green;
input hold;
input clk;
input rst_n;
wire devclrn;
wire devoe;
wire devpor;
wire gnd;
wire \hold~_wirecell_combout ;
wire \i14~0_combout ;
wire \i23~0_combout ;
wire \i23~1_combout ;
wire \i23~2_combout ;
wire \i23~3_combout ;
wire \reduce_nor_1~0_combout ;
wire \red~0_combout ;
wire \state.S_GREEN~q ;
wire \state.S_RED_YELLOW~q ;
wire \state.S_RED~0_combout ;
wire \state.S_RED~q ;
wire \state.S_YELLOW~q ;
wire \state~6_combout ;
wire \state~7_combout ;
wire \state~8_combout ;
wire \state~9_combout ;
wire [3:0] tick;
wire unknown;
wire vcc;
wire \yellow~0_combout ;

assign gnd = 1'b0;
assign vcc = 1'b1;
// dropped: assign unknown = 1'bx;  (declared by Quartus, read by nothing)
assign devclrn = 1'b1;
assign devpor = 1'b1;
assign devoe = 1'b1;
assign red = \red~0_combout ;
assign green = \state.S_GREEN~q ;
assign yellow = \yellow~0_combout ;

tennm_ff #(.is_wysiwyg ("true"), .power_up ("low")) \state.S_RED  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\state~6_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (\state.S_RED~q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("low")) \state.S_RED_YELLOW  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\state~7_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (\state.S_RED_YELLOW~q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hDDDDDDDDDDDDDDDD), .shared_arith ("off")) \red~0  (.cin (gnd), .combout (\red~0_combout ), .dataa (\state.S_RED~q ), .datab (\state.S_RED_YELLOW~q ), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("low")) \state.S_YELLOW  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\state~8_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (\state.S_YELLOW~q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hEEEEEEEEEEEEEEEE), .shared_arith ("off")) \yellow~0  (.cin (gnd), .combout (\yellow~0_combout ), .dataa (\state.S_RED_YELLOW~q ), .datab (\state.S_YELLOW~q ), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("low")) \state.S_GREEN  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\state~9_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (\state.S_GREEN~q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \tick[3]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i23~0_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\hold~_wirecell_combout ), .q (tick[3]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2D2D2D2D2D2D2D2D), .shared_arith ("off")) \i14~0  (.cin (gnd), .combout (\i14~0_combout ), .dataa (\state.S_RED~q ), .datab (\state.S_GREEN~q ), .datac (tick[3]), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \tick[0]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i23~1_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\hold~_wirecell_combout ), .q (tick[0]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \tick[1]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i23~2_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\hold~_wirecell_combout ), .q (tick[1]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \tick[2]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i23~3_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\hold~_wirecell_combout ), .q (tick[2]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0002481000024810), .shared_arith ("off")) \reduce_nor_1~0  (.cin (gnd), .combout (\reduce_nor_1~0_combout ), .dataa (\state.S_RED~q ), .datab (\state.S_RED_YELLOW~q ), .datac (tick[0]), .datad (tick[1]), .datae (tick[2]), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0229022902290229), .shared_arith ("off")) \state.S_RED~0  (.cin (gnd), .combout (\state.S_RED~0_combout ), .dataa (\state.S_RED~q ), .datab (\state.S_RED_YELLOW~q ), .datac (\state.S_YELLOW~q ), .datad (\state.S_GREEN~q ), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hAAA3AAAA00000000), .shared_arith ("off")) \state~6  (.cin (gnd), .combout (\state~6_combout ), .dataa (\state.S_RED~q ), .datab (\state.S_YELLOW~q ), .datac (hold), .datad (\i14~0_combout ), .datae (\reduce_nor_1~0_combout ), .dataf (\state.S_RED~0_combout ), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hCCC5CCCC00000000), .shared_arith ("off")) \state~7  (.cin (gnd), .combout (\state~7_combout ), .dataa (\state.S_RED~q ), .datab (\state.S_RED_YELLOW~q ), .datac (hold), .datad (\i14~0_combout ), .datae (\reduce_nor_1~0_combout ), .dataf (\state.S_RED~0_combout ), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hAAACAAAA00000000), .shared_arith ("off")) \state~8  (.cin (gnd), .combout (\state~8_combout ), .dataa (\state.S_YELLOW~q ), .datab (\state.S_GREEN~q ), .datac (hold), .datad (\i14~0_combout ), .datae (\reduce_nor_1~0_combout ), .dataf (\state.S_RED~0_combout ), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hCCCACCCC00000000), .shared_arith ("off")) \state~9  (.cin (gnd), .combout (\state~9_combout ), .dataa (\state.S_RED_YELLOW~q ), .datab (\state.S_GREEN~q ), .datac (hold), .datad (\i14~0_combout ), .datae (\reduce_nor_1~0_combout ), .dataf (\state.S_RED~0_combout ), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h7F8000007F807F80), .shared_arith ("off")) \i23~0  (.cin (gnd), .combout (\i23~0_combout ), .dataa (tick[0]), .datab (tick[1]), .datac (tick[2]), .datad (tick[3]), .datae (\i14~0_combout ), .dataf (\reduce_nor_1~0_combout ), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h4545454545454545), .shared_arith ("off")) \i23~1  (.cin (gnd), .combout (\i23~1_combout ), .dataa (tick[0]), .datab (\i14~0_combout ), .datac (\reduce_nor_1~0_combout ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h6066606660666066), .shared_arith ("off")) \i23~2  (.cin (gnd), .combout (\i23~2_combout ), .dataa (tick[0]), .datab (tick[1]), .datac (\i14~0_combout ), .datad (\reduce_nor_1~0_combout ), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h7800787878007878), .shared_arith ("off")) \i23~3  (.cin (gnd), .combout (\i23~3_combout ), .dataa (tick[0]), .datab (tick[1]), .datac (tick[2]), .datad (\i14~0_combout ), .datae (\reduce_nor_1~0_combout ), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) \hold~_wirecell  (.cin (gnd), .combout (\hold~_wirecell_combout ), .dataa (hold), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));

endmodule
