// Generated by tools/hal_agilex from a Quartus Prime Pro EDA netlist export.
// Load with the AGILEX_TENNM gate library.
// source: uart_tx.vo
// Inversions on ALM data inputs were absorbed into lut_mask; tri1 nets became wires tied to 1'b1.

module uart_tx (tx, tx_busy, tx_start, clk, rst_n, tx_data);
output tx;
output tx_busy;
input tx_start;
input clk;
input rst_n;
input [7:0] tx_data;
wire [3:0] baud_cnt;
wire [3:0] bit_cnt;
wire \busy~q ;
wire devclrn;
wire devoe;
wire devpor;
wire gnd;
wire \i21~0_combout ;
wire \i41~0_combout ;
wire \i41~1_combout ;
wire \i41~2_combout ;
wire \i41~3_combout ;
wire \i45~0_combout ;
wire \i45~1_combout ;
wire \i45~2_combout ;
wire \i45~3_combout ;
wire \i45~4_combout ;
wire \i55~0_combout ;
wire \i55~1_combout ;
wire \i55~2_combout ;
wire \i55~3_combout ;
wire \i55~4_combout ;
wire \i55~5_combout ;
wire \i55~6_combout ;
wire \i55~7_combout ;
wire \i55~8_combout ;
wire \i56~0_combout ;
wire \reduce_and_0~combout ;
wire [9:0] shreg;
wire \shreg[0]~_wirecell_combout ;
wire unknown;
wire vcc;

assign gnd = 1'b0;
assign vcc = 1'b1;
// dropped: assign unknown = 1'bx;  (declared by Quartus, read by nothing)
assign devclrn = 1'b1;
assign devpor = 1'b1;
assign devoe = 1'b1;
assign tx_busy = \busy~q ;
assign tx = \shreg[0]~_wirecell_combout ;

tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \shreg[0]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i55~0_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (shreg[0]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) busy (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i56~0_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (\busy~q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \shreg[1]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i55~1_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i21~0_combout ), .q (shreg[1]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \baud_cnt[2]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i41~0_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (baud_cnt[2]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \baud_cnt[3]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i41~1_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (baud_cnt[3]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \baud_cnt[0]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i41~2_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (baud_cnt[0]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \baud_cnt[1]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i41~3_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (baud_cnt[1]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8000800080008000), .shared_arith ("off")) reduce_and_0 (.cin (gnd), .combout (\reduce_and_0~combout ), .dataa (baud_cnt[2]), .datab (baud_cnt[3]), .datac (baud_cnt[0]), .datad (baud_cnt[1]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hFE32BABAFE32BABA), .shared_arith ("off")) \i55~0  (.cin (gnd), .combout (\i55~0_combout ), .dataa (shreg[0]), .datab (\busy~q ), .datac (tx_start), .datad (shreg[1]), .datae (\reduce_and_0~combout ), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \bit_cnt[0]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i45~0_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (bit_cnt[0]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \bit_cnt[1]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i45~1_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i45~2_combout ), .q (bit_cnt[1]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \bit_cnt[2]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i45~3_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i45~2_combout ), .q (bit_cnt[2]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \bit_cnt[3]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i45~4_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i45~2_combout ), .q (bit_cnt[3]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hEEEEE4EEEEEEEEEE), .shared_arith ("off")) \i56~0  (.cin (gnd), .combout (\i56~0_combout ), .dataa (\busy~q ), .datab (tx_start), .datac (bit_cnt[0]), .datad (bit_cnt[1]), .datae (bit_cnt[2]), .dataf (bit_cnt[3]), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \shreg[2]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i55~2_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i21~0_combout ), .q (shreg[2]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8D8D8D8D8D8D8D8D), .shared_arith ("off")) \i55~1  (.cin (gnd), .combout (\i55~1_combout ), .dataa (\busy~q ), .datab (shreg[2]), .datac (tx_data[0]), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hD555555580000000), .shared_arith ("off")) \i21~0  (.cin (gnd), .combout (\i21~0_combout ), .dataa (\busy~q ), .datab (baud_cnt[2]), .datac (baud_cnt[3]), .datad (baud_cnt[0]), .datae (baud_cnt[1]), .dataf (tx_start), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2888288828882888), .shared_arith ("off")) \i41~0  (.cin (gnd), .combout (\i41~0_combout ), .dataa (\busy~q ), .datab (baud_cnt[2]), .datac (baud_cnt[0]), .datad (baud_cnt[1]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h28A0A0A028A0A0A0), .shared_arith ("off")) \i41~1  (.cin (gnd), .combout (\i41~1_combout ), .dataa (\busy~q ), .datab (baud_cnt[2]), .datac (baud_cnt[3]), .datad (baud_cnt[0]), .datae (baud_cnt[1]), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2222222222222222), .shared_arith ("off")) \i41~2  (.cin (gnd), .combout (\i41~2_combout ), .dataa (\busy~q ), .datab (baud_cnt[0]), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2828282828282828), .shared_arith ("off")) \i41~3  (.cin (gnd), .combout (\i41~3_combout ), .dataa (\busy~q ), .datab (baud_cnt[0]), .datac (baud_cnt[1]), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2AAAAAAA80000000), .shared_arith ("off")) \i45~0  (.cin (gnd), .combout (\i45~0_combout ), .dataa (\busy~q ), .datab (baud_cnt[2]), .datac (baud_cnt[3]), .datad (baud_cnt[0]), .datae (baud_cnt[1]), .dataf (bit_cnt[0]), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2828282828282828), .shared_arith ("off")) \i45~1  (.cin (gnd), .combout (\i45~1_combout ), .dataa (\busy~q ), .datab (bit_cnt[0]), .datac (bit_cnt[1]), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hD5555555D5555555), .shared_arith ("off")) \i45~2  (.cin (gnd), .combout (\i45~2_combout ), .dataa (\busy~q ), .datab (baud_cnt[2]), .datac (baud_cnt[3]), .datad (baud_cnt[0]), .datae (baud_cnt[1]), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2A802A802A802A80), .shared_arith ("off")) \i45~3  (.cin (gnd), .combout (\i45~3_combout ), .dataa (\busy~q ), .datab (bit_cnt[0]), .datac (bit_cnt[1]), .datad (bit_cnt[2]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2AAA80002AAA8000), .shared_arith ("off")) \i45~4  (.cin (gnd), .combout (\i45~4_combout ), .dataa (\busy~q ), .datab (bit_cnt[0]), .datac (bit_cnt[1]), .datad (bit_cnt[2]), .datae (bit_cnt[3]), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \shreg[3]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i55~3_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i21~0_combout ), .q (shreg[3]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8D8D8D8D8D8D8D8D), .shared_arith ("off")) \i55~2  (.cin (gnd), .combout (\i55~2_combout ), .dataa (\busy~q ), .datab (shreg[3]), .datac (tx_data[1]), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \shreg[4]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i55~4_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i21~0_combout ), .q (shreg[4]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8D8D8D8D8D8D8D8D), .shared_arith ("off")) \i55~3  (.cin (gnd), .combout (\i55~3_combout ), .dataa (\busy~q ), .datab (shreg[4]), .datac (tx_data[2]), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \shreg[5]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i55~5_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i21~0_combout ), .q (shreg[5]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8D8D8D8D8D8D8D8D), .shared_arith ("off")) \i55~4  (.cin (gnd), .combout (\i55~4_combout ), .dataa (\busy~q ), .datab (shreg[5]), .datac (tx_data[3]), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \shreg[6]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i55~6_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i21~0_combout ), .q (shreg[6]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8D8D8D8D8D8D8D8D), .shared_arith ("off")) \i55~5  (.cin (gnd), .combout (\i55~5_combout ), .dataa (\busy~q ), .datab (shreg[6]), .datac (tx_data[4]), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \shreg[7]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i55~7_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i21~0_combout ), .q (shreg[7]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8D8D8D8D8D8D8D8D), .shared_arith ("off")) \i55~6  (.cin (gnd), .combout (\i55~6_combout ), .dataa (\busy~q ), .datab (shreg[7]), .datac (tx_data[5]), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \shreg[8]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i55~8_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (shreg[8]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8D8D8D8D8D8D8D8D), .shared_arith ("off")) \i55~7  (.cin (gnd), .combout (\i55~7_combout ), .dataa (\busy~q ), .datab (shreg[8]), .datac (tx_data[6]), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h1054B0F41054B0F4), .shared_arith ("off")) \i55~8  (.cin (gnd), .combout (\i55~8_combout ), .dataa (\busy~q ), .datab (tx_start), .datac (shreg[8]), .datad (tx_data[7]), .datae (\reduce_and_0~combout ), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) \shreg[0]~_wirecell  (.cin (gnd), .combout (\shreg[0]~_wirecell_combout ), .dataa (shreg[0]), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));

endmodule
