// Anonymised netlist: same circuit as the import, no design names.
// Produced by anonymize.py from netlist.hal.v.
// Ports, nets and instances are renamed; buses are exploded to scalars;
// gate types and parameters are untouched.  Name map: <output>.map.json

module top (PORT_00, PORT_01, PORT_02, PORT_03, PORT_04, PORT_05, PORT_06, PORT_07, PORT_08, PORT_09, PORT_10, PORT_11, PORT_12);
input PORT_00;
input PORT_01;
input PORT_02;
input PORT_03;
input PORT_04;
output PORT_05;
input PORT_06;
output PORT_07;
input PORT_08;
input PORT_09;
input PORT_10;
input PORT_11;
input PORT_12;
wire n_000;
wire n_001;
wire n_002;
wire n_003;
wire n_004;
wire n_005;
wire n_006;
wire n_007;
wire n_008;
wire n_009;
wire n_010;
wire n_011;
wire n_012;
wire n_013;
wire n_014;
wire n_015;
wire n_016;
wire n_017;
wire n_018;
wire n_019;
wire n_020;
wire n_021;
wire n_022;
wire n_023;
wire n_024;
wire n_025;
wire n_026;
wire n_027;
wire n_028;
wire n_029;
wire n_030;
wire n_031;
wire n_032;
wire n_033;
wire n_034;
wire n_035;
wire n_036;
wire n_037;
wire n_038;
wire n_039;
wire n_040;
wire devclrn;
wire devoe;
wire devpor;
wire gnd;
wire unknown;
wire vcc;

assign gnd = 1'b0;
assign vcc = 1'b1;
assign devclrn = 1'b1;
assign devpor = 1'b1;
assign devoe = 1'b1;
assign PORT_05 = n_006;
assign PORT_07 = n_008;

tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) g_000 (.aload (gnd), .asdata (vcc), .clk (PORT_02), .clrn (PORT_11), .d (n_007), .devclrn (devclrn), .devpor (devpor), .ena (n_038), .q (n_001), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) g_001 (.aload (gnd), .asdata (vcc), .clk (PORT_02), .clrn (PORT_11), .d (n_030), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n_002), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) g_002 (.aload (gnd), .asdata (vcc), .clk (PORT_02), .clrn (PORT_11), .d (n_014), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n_004), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8D8D8D8D8D8D8D8D), .shared_arith ("off")) g_003 (.cin (gnd), .combout (n_029), .dataa (n_006), .datab (n_001), .datac (PORT_08), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8D8D8D8D8D8D8D8D), .shared_arith ("off")) g_004 (.cin (gnd), .combout (n_040), .dataa (n_006), .datab (n_002), .datac (PORT_00), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8000800080008000), .shared_arith ("off")) g_005 (.cin (gnd), .combout (n_023), .dataa (n_015), .datab (n_017), .datac (n_004), .datad (n_031), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) g_006 (.aload (gnd), .asdata (vcc), .clk (PORT_02), .clrn (PORT_11), .d (n_024), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n_009), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2222222222222222), .shared_arith ("off")) g_007 (.cin (gnd), .combout (n_014), .dataa (n_006), .datab (n_004), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8D8D8D8D8D8D8D8D), .shared_arith ("off")) g_008 (.cin (gnd), .combout (n_020), .dataa (n_006), .datab (n_034), .datac (PORT_06), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8D8D8D8D8D8D8D8D), .shared_arith ("off")) g_009 (.cin (gnd), .combout (n_028), .dataa (n_006), .datab (n_032), .datac (PORT_03), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) g_010 (.aload (gnd), .asdata (vcc), .clk (PORT_02), .clrn (PORT_11), .d (n_010), .devclrn (devclrn), .devpor (devpor), .ena (n_012), .q (n_011), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2A802A802A802A80), .shared_arith ("off")) g_011 (.cin (gnd), .combout (n_010), .dataa (n_006), .datab (n_013), .datac (n_026), .datad (n_011), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) g_012 (.aload (gnd), .asdata (vcc), .clk (PORT_02), .clrn (PORT_11), .d (n_025), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n_013), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2AAAAAAA80000000), .shared_arith ("off")) g_013 (.cin (gnd), .combout (n_025), .dataa (n_006), .datab (n_015), .datac (n_017), .datad (n_004), .datae (n_031), .dataf (n_013), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) g_014 (.cin (gnd), .combout (n_008), .dataa (n_009), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h28A0A0A028A0A0A0), .shared_arith ("off")) g_015 (.cin (gnd), .combout (n_036), .dataa (n_006), .datab (n_015), .datac (n_017), .datad (n_004), .datae (n_031), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2AAA80002AAA8000), .shared_arith ("off")) g_016 (.cin (gnd), .combout (n_039), .dataa (n_006), .datab (n_013), .datac (n_026), .datad (n_011), .datae (n_019), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) g_017 (.aload (gnd), .asdata (vcc), .clk (PORT_02), .clrn (PORT_11), .d (n_022), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n_015), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) g_018 (.aload (gnd), .asdata (vcc), .clk (PORT_02), .clrn (PORT_11), .d (n_040), .devclrn (devclrn), .devpor (devpor), .ena (n_038), .q (n_016), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) g_019 (.aload (gnd), .asdata (vcc), .clk (PORT_02), .clrn (PORT_11), .d (n_036), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n_017), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) g_020 (.aload (gnd), .asdata (vcc), .clk (PORT_02), .clrn (PORT_11), .d (n_039), .devclrn (devclrn), .devpor (devpor), .ena (n_012), .q (n_019), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) g_021 (.aload (gnd), .asdata (vcc), .clk (PORT_02), .clrn (PORT_11), .d (n_005), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n_006), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) g_022 (.aload (gnd), .asdata (vcc), .clk (PORT_02), .clrn (PORT_11), .d (n_000), .devclrn (devclrn), .devpor (devpor), .ena (n_012), .q (n_026), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hEEEEE4EEEEEEEEEE), .shared_arith ("off")) g_023 (.cin (gnd), .combout (n_005), .dataa (n_006), .datab (PORT_09), .datac (n_013), .datad (n_026), .datae (n_011), .dataf (n_019), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) g_024 (.aload (gnd), .asdata (vcc), .clk (PORT_02), .clrn (PORT_11), .d (n_028), .devclrn (devclrn), .devpor (devpor), .ena (n_038), .q (n_027), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2828282828282828), .shared_arith ("off")) g_025 (.cin (gnd), .combout (n_003), .dataa (n_006), .datab (n_004), .datac (n_031), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hD5555555D5555555), .shared_arith ("off")) g_026 (.cin (gnd), .combout (n_012), .dataa (n_006), .datab (n_015), .datac (n_017), .datad (n_004), .datae (n_031), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) g_027 (.aload (gnd), .asdata (vcc), .clk (PORT_02), .clrn (PORT_11), .d (n_003), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n_031), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2828282828282828), .shared_arith ("off")) g_028 (.cin (gnd), .combout (n_000), .dataa (n_006), .datab (n_013), .datac (n_026), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) g_029 (.aload (gnd), .asdata (vcc), .clk (PORT_02), .clrn (PORT_11), .d (n_029), .devclrn (devclrn), .devpor (devpor), .ena (n_038), .q (n_032), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h1054B0F41054B0F4), .shared_arith ("off")) g_030 (.cin (gnd), .combout (n_030), .dataa (n_006), .datab (PORT_09), .datac (n_002), .datad (PORT_10), .datae (n_023), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) g_031 (.aload (gnd), .asdata (vcc), .clk (PORT_02), .clrn (PORT_11), .d (n_021), .devclrn (devclrn), .devpor (devpor), .ena (n_038), .q (n_033), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) g_032 (.aload (gnd), .asdata (vcc), .clk (PORT_02), .clrn (PORT_11), .d (n_035), .devclrn (devclrn), .devpor (devpor), .ena (n_038), .q (n_034), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hD555555580000000), .shared_arith ("off")) g_033 (.cin (gnd), .combout (n_038), .dataa (n_006), .datab (n_015), .datac (n_017), .datad (n_004), .datae (n_031), .dataf (PORT_09), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) g_034 (.aload (gnd), .asdata (vcc), .clk (PORT_02), .clrn (PORT_11), .d (n_020), .devclrn (devclrn), .devpor (devpor), .ena (n_038), .q (n_037), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8D8D8D8D8D8D8D8D), .shared_arith ("off")) g_035 (.cin (gnd), .combout (n_035), .dataa (n_006), .datab (n_027), .datac (PORT_04), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2888288828882888), .shared_arith ("off")) g_036 (.cin (gnd), .combout (n_022), .dataa (n_006), .datab (n_015), .datac (n_004), .datad (n_031), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8D8D8D8D8D8D8D8D), .shared_arith ("off")) g_037 (.cin (gnd), .combout (n_007), .dataa (n_006), .datab (n_033), .datac (PORT_01), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hFE32BABAFE32BABA), .shared_arith ("off")) g_038 (.cin (gnd), .combout (n_024), .dataa (n_009), .datab (n_006), .datac (PORT_09), .datad (n_037), .datae (n_023), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8D8D8D8D8D8D8D8D), .shared_arith ("off")) g_039 (.cin (gnd), .combout (n_021), .dataa (n_006), .datab (n_016), .datac (PORT_12), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));

endmodule
