// Generated by tools/hal_agilex from a Quartus Prime Pro EDA netlist export.
// Load with the AGILEX_TENNM gate library.
// source: recovered.vo
// Inversions on ALM data inputs were absorbed into lut_mask; tri1 nets became wires tied to 1'b1.

module recovered_top (serial, status, start, clk, rst_n, data);
output serial;
output status;
input start;
input clk;
input rst_n;
input [7:0] data;
wire \busy~q ;
wire devclrn;
wire devoe;
wire devpor;
wire gnd;
wire \i15~0_combout ;
wire \i19~0_combout ;
wire \i19~1_combout ;
wire \i19~2_combout ;
wire \i19~3_combout ;
wire \i28~0_combout ;
wire \i28~1_combout ;
wire \i28~2_combout ;
wire \i28~3_combout ;
wire \i28~4_combout ;
wire \i54~0_combout ;
wire \i54~1_combout ;
wire \i54~2_combout ;
wire \i54~3_combout ;
wire \i54~4_combout ;
wire \i54~5_combout ;
wire \i54~6_combout ;
wire \i54~7_combout ;
wire \i54~8_combout ;
wire \i54~9_combout ;
wire [3:0] prescale;
wire \reduce_and_0~combout ;
wire [3:0] slot;
wire [8:0] sr;
wire \sr[0]~_wirecell_combout ;
wire unknown;
wire vcc;

assign gnd = 1'b0;
assign vcc = 1'b1;
// dropped: assign unknown = 1'bx;  (declared by Quartus, read by nothing)
assign devclrn = 1'b1;
assign devpor = 1'b1;
assign devoe = 1'b1;
assign status = \busy~q ;
assign serial = \sr[0]~_wirecell_combout ;

tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \sr[0]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i54~0_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (sr[0]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) busy (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i15~0_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (\busy~q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \sr[1]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i54~1_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i54~2_combout ), .q (sr[1]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \prescale[2]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i19~0_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (prescale[2]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \prescale[3]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i19~1_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (prescale[3]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \prescale[0]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i19~2_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (prescale[0]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \prescale[1]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i19~3_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (prescale[1]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8000800080008000), .shared_arith ("off")) reduce_and_0 (.cin (gnd), .combout (\reduce_and_0~combout ), .dataa (prescale[2]), .datab (prescale[3]), .datac (prescale[0]), .datad (prescale[1]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hFE32BABAFE32BABA), .shared_arith ("off")) \i54~0  (.cin (gnd), .combout (\i54~0_combout ), .dataa (sr[0]), .datab (\busy~q ), .datac (start), .datad (sr[1]), .datae (\reduce_and_0~combout ), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \slot[0]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i28~0_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (slot[0]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \slot[1]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i28~1_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i28~2_combout ), .q (slot[1]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \slot[2]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i28~3_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i28~2_combout ), .q (slot[2]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \slot[3]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i28~4_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i28~2_combout ), .q (slot[3]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hEEEEE4EEEEEEEEEE), .shared_arith ("off")) \i15~0  (.cin (gnd), .combout (\i15~0_combout ), .dataa (\busy~q ), .datab (start), .datac (slot[0]), .datad (slot[1]), .datae (slot[2]), .dataf (slot[3]), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \sr[2]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i54~3_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i54~2_combout ), .q (sr[2]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hBF04BF04BF04BF04), .shared_arith ("off")) \i54~1  (.cin (gnd), .combout (\i54~1_combout ), .dataa (\busy~q ), .datab (start), .datac (data[0]), .datad (sr[2]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hE444444444444444), .shared_arith ("off")) \i54~2  (.cin (gnd), .combout (\i54~2_combout ), .dataa (\busy~q ), .datab (start), .datac (prescale[2]), .datad (prescale[3]), .datae (prescale[0]), .dataf (prescale[1]), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2888288828882888), .shared_arith ("off")) \i19~0  (.cin (gnd), .combout (\i19~0_combout ), .dataa (\busy~q ), .datab (prescale[2]), .datac (prescale[0]), .datad (prescale[1]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h28A0A0A028A0A0A0), .shared_arith ("off")) \i19~1  (.cin (gnd), .combout (\i19~1_combout ), .dataa (\busy~q ), .datab (prescale[2]), .datac (prescale[3]), .datad (prescale[0]), .datae (prescale[1]), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2222222222222222), .shared_arith ("off")) \i19~2  (.cin (gnd), .combout (\i19~2_combout ), .dataa (\busy~q ), .datab (prescale[0]), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2828282828282828), .shared_arith ("off")) \i19~3  (.cin (gnd), .combout (\i19~3_combout ), .dataa (\busy~q ), .datab (prescale[0]), .datac (prescale[1]), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2AAAAAAA80000000), .shared_arith ("off")) \i28~0  (.cin (gnd), .combout (\i28~0_combout ), .dataa (\busy~q ), .datab (prescale[2]), .datac (prescale[3]), .datad (prescale[0]), .datae (prescale[1]), .dataf (slot[0]), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2828282828282828), .shared_arith ("off")) \i28~1  (.cin (gnd), .combout (\i28~1_combout ), .dataa (\busy~q ), .datab (slot[0]), .datac (slot[1]), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hD5555555D5555555), .shared_arith ("off")) \i28~2  (.cin (gnd), .combout (\i28~2_combout ), .dataa (\busy~q ), .datab (prescale[2]), .datac (prescale[3]), .datad (prescale[0]), .datae (prescale[1]), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2A802A802A802A80), .shared_arith ("off")) \i28~3  (.cin (gnd), .combout (\i28~3_combout ), .dataa (\busy~q ), .datab (slot[0]), .datac (slot[1]), .datad (slot[2]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2AAA80002AAA8000), .shared_arith ("off")) \i28~4  (.cin (gnd), .combout (\i28~4_combout ), .dataa (\busy~q ), .datab (slot[0]), .datac (slot[1]), .datad (slot[2]), .datae (slot[3]), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \sr[3]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i54~4_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i54~2_combout ), .q (sr[3]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hBF04BF04BF04BF04), .shared_arith ("off")) \i54~3  (.cin (gnd), .combout (\i54~3_combout ), .dataa (\busy~q ), .datab (start), .datac (data[1]), .datad (sr[3]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \sr[4]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i54~5_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i54~2_combout ), .q (sr[4]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hBF04BF04BF04BF04), .shared_arith ("off")) \i54~4  (.cin (gnd), .combout (\i54~4_combout ), .dataa (\busy~q ), .datab (start), .datac (data[2]), .datad (sr[4]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \sr[5]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i54~6_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i54~2_combout ), .q (sr[5]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hBF04BF04BF04BF04), .shared_arith ("off")) \i54~5  (.cin (gnd), .combout (\i54~5_combout ), .dataa (\busy~q ), .datab (start), .datac (data[3]), .datad (sr[5]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \sr[6]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i54~7_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i54~2_combout ), .q (sr[6]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hBF04BF04BF04BF04), .shared_arith ("off")) \i54~6  (.cin (gnd), .combout (\i54~6_combout ), .dataa (\busy~q ), .datab (start), .datac (data[4]), .datad (sr[6]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \sr[7]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i54~8_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i54~2_combout ), .q (sr[7]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hBF04BF04BF04BF04), .shared_arith ("off")) \i54~7  (.cin (gnd), .combout (\i54~7_combout ), .dataa (\busy~q ), .datab (start), .datac (data[5]), .datad (sr[7]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \sr[8]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i54~9_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (sr[8]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hBF04BF04BF04BF04), .shared_arith ("off")) \i54~8  (.cin (gnd), .combout (\i54~8_combout ), .dataa (\busy~q ), .datab (start), .datac (data[6]), .datad (sr[8]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h1054B0F41054B0F4), .shared_arith ("off")) \i54~9  (.cin (gnd), .combout (\i54~9_combout ), .dataa (\busy~q ), .datab (start), .datac (sr[8]), .datad (data[7]), .datae (\reduce_and_0~combout ), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) \sr[0]~_wirecell  (.cin (gnd), .combout (\sr[0]~_wirecell_combout ), .dataa (sr[0]), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));

endmodule
