"""State diagrams, emitted through ``hal_viz.dot``.

``solve_fsm`` can write a ``.dot`` file itself, and this module does not
replace it -- the raw file it writes is kept as evidence.  What it cannot do is
show the things this workflow is about: which state the machine starts in,
which states are reachable, which path the witness takes, and where the diagram
was truncated because a limit was hit.  A diagram that silently drops states is
worse than no diagram, so truncation is drawn.

Pure Python: the escaping, quoting and layout all live in ``hal_viz.dot``,
which is unit-tested without a HAL build, and so is this.
"""

import os
import re
import sys

if __package__ in (None, ""):  # pragma: no cover - direct execution
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from hal_viz.dot import DotGraph, truncate

from .transitions import format_state, reachable_states

__all__ = ["state_diagram", "write_state_diagram", "readable_condition"]

_NET_VARIABLE = re.compile(r"\bnet_([0-9]+)\b")

_INITIAL = {"shape": "doublecircle", "style": "filled", "fillcolor": "#dfefff"}
_REACHABLE = {"shape": "circle"}
_UNREACHABLE = {"shape": "circle", "style": "dashed", "color": "#909090", "fontcolor": "#606060"}
_WITNESS_EDGE = {"color": "#b30000", "penwidth": "2.0", "fontcolor": "#b30000"}


def readable_condition(condition, signals):
    """Replace HAL's ``net_<id>`` variables with the net names they stand for.

    Only for display.  The condition as ``solve_fsm`` returned it stays in the
    findings document verbatim, because a net name is not unique and a net ID is.
    """

    def replace(match):
        entry = signals.get(match.group(0))
        name = entry.get("name") if entry else None
        return name or match.group(0)

    return _NET_VARIABLE.sub(replace, condition or "")


def _node_id(state):
    return "s{}".format(int(state))


def _label(state, width, base):
    text = format_state(state, width, base)
    if base == 2:
        return "{}\n({})".format(text, state)
    return text


def state_diagram(
    table,
    title=None,
    base=2,
    max_states=None,
    witness_path=None,
    focus=None,
    max_condition_length=48,
):
    """Build a :class:`hal_viz.dot.DotGraph` for a transition table.

    ``max_states`` scopes the diagram: states are taken in breadth-first order
    from the initial state (or from ``focus``), and the fact that the rest were
    dropped is drawn as an explicit node rather than left implicit.
    """
    width = table.width
    reachable, _ = reachable_states(table)
    reachable = set(reachable)

    order = []
    seen = set()
    start = table.initial_state if focus is None else int(focus)
    queue = [start] if start in set(table.states) or not table.states else [start]
    while queue:
        state = queue.pop(0)
        if state in seen:
            continue
        seen.add(state)
        order.append(state)
        queue.extend(sorted(table.successors(state)))
    for state in table.states:  # states not reachable from the start, in order
        if state not in seen:
            seen.add(state)
            order.append(state)

    truncated = 0
    if max_states is not None and len(order) > max_states:
        truncated = len(order) - max_states
        order = order[:max_states]
    shown = set(order)

    witness_edges = set()
    if witness_path:
        witness_edges = {
            (int(a), int(b)) for a, b in zip(witness_path, list(witness_path)[1:])
        }

    graph = DotGraph(
        name=title or "fsm",
        directed=True,
        comment="\n".join(
            [
                "generated by tools/hal_fsm",
                "state bit order (bit 0 first): {}".format(", ".join(table.bit_order)),
                "state values are printed {}".format(
                    {2: "as bit vectors, most significant bit first", 10: "in decimal", 16: "in hex"}[base]
                ),
                "solver: {}{}".format(
                    table.solver, "" if table.complete else " (INCOMPLETE - a limit was hit)"
                ),
                "initial state: {}".format(format_state(table.initial_state, width, base)),
            ]
        ),
    )
    graph.graph_attrs.update(
        {
            "rankdir": "LR",
            "labelloc": "t",
            "label": title or "recovered state transition graph",
            "fontname": "Helvetica",
        }
    )
    graph.node_defaults.update({"fontname": "Helvetica", "fontsize": "10"})
    graph.edge_defaults.update({"fontname": "Helvetica", "fontsize": "9"})

    graph.add_node("__entry__", label="", shape="point", width="0.1")

    for state in order:
        if state == table.initial_state:
            attrs = dict(_INITIAL)
        elif state in reachable:
            attrs = dict(_REACHABLE)
        else:
            attrs = dict(_UNREACHABLE)
        graph.add_node(_node_id(state), label=_label(state, width, base), **attrs)

    graph.add_edge("__entry__", _node_id(table.initial_state), label="reset")

    for transition in table.transitions:
        if transition.source not in shown:
            continue
        if transition.target not in shown:
            continue
        attrs = {}
        if (transition.source, transition.target) in witness_edges:
            attrs.update(_WITNESS_EDGE)
        graph.add_edge(
            _node_id(transition.source),
            _node_id(transition.target),
            label=truncate(
                readable_condition(transition.condition, table.signals),
                max_condition_length,
            ),
            **attrs
        )

    dropped_edges = sum(
        1
        for transition in table.transitions
        if transition.source in shown and transition.target not in shown
    )
    if truncated:
        graph.add_node(
            "__truncated__",
            label="+{} more state(s)\n{} edge(s) not drawn\n(max_diagram_states)".format(
                truncated, dropped_edges
            ),
            shape="note",
            style="filled",
            fillcolor="#fff0c0",
        )
    if not table.complete:
        graph.add_node(
            "__incomplete__",
            label="INCOMPLETE\na limit was hit; this is not\nthe whole state machine",
            shape="note",
            style="filled",
            fillcolor="#ffd0d0",
        )
    return graph


def write_state_diagram(table, path, **kwargs):
    """Write a state diagram and return ``(path, node_count, edge_count)``."""
    graph = state_diagram(table, **kwargs)
    graph.write(path)
    return path, graph.node_count, graph.edge_count
