// Generated by tools/hal_agilex from a Quartus Prime Pro EDA netlist export.
// Load with the AGILEX_TENNM gate library.
// source: accumulator_alu.vo
// Inversions on ALM data inputs were absorbed into lut_mask; tri1 nets became wires tied to 1'b1.

module accumulator_alu (acc, carry, zero, op, clk, rst_n, operand);
output [7:0] acc;
output carry;
output zero;
input [1:0] op;
input clk;
input rst_n;
input [7:0] operand;
wire \acc[0]~reg0_q ;
wire \acc[1]~reg0_q ;
wire \acc[2]~reg0_q ;
wire \acc[3]~reg0_q ;
wire \acc[4]~reg0_q ;
wire \acc[5]~reg0_q ;
wire \acc[6]~reg0_q ;
wire \acc[7]~reg0_q ;
wire \add_0~11_sumout ;
wire \add_0~12 ;
wire \add_0~16_sumout ;
wire \add_0~17 ;
wire \add_0~1_sumout ;
wire \add_0~2 ;
wire \add_0~21_sumout ;
wire \add_0~22 ;
wire \add_0~26_sumout ;
wire \add_0~27 ;
wire \add_0~31_sumout ;
wire \add_0~32 ;
wire \add_0~36_sumout ;
wire \add_0~37 ;
wire \add_0~41_sumout ;
wire \add_0~47_cout ;
wire \add_0~6_sumout ;
wire \add_0~7 ;
wire \carry~reg0_q ;
wire devclrn;
wire devoe;
wire devpor;
wire gnd;
wire \i45~0_combout ;
wire \i45~1_combout ;
wire \i45~2_combout ;
wire \i45~3_combout ;
wire \i45~4_combout ;
wire \i45~5_combout ;
wire \i45~6_combout ;
wire \i45~7_combout ;
wire \i45~8_combout ;
wire \i46~0_combout ;
wire \reduce_or_0~0_combout ;
wire \reduce_or_0~combout ;
wire unknown;
wire vcc;

assign gnd = 1'b0;
assign vcc = 1'b1;
// dropped: assign unknown = 1'bx;  (declared by Quartus, read by nothing)
assign devclrn = 1'b1;
assign devpor = 1'b1;
assign devoe = 1'b1;
assign acc[0] = \acc[0]~reg0_q ;
assign acc[1] = \acc[1]~reg0_q ;
assign acc[2] = \acc[2]~reg0_q ;
assign acc[3] = \acc[3]~reg0_q ;
assign acc[4] = \acc[4]~reg0_q ;
assign acc[5] = \acc[5]~reg0_q ;
assign acc[6] = \acc[6]~reg0_q ;
assign acc[7] = \acc[7]~reg0_q ;
assign carry = \carry~reg0_q ;
assign zero = \reduce_or_0~combout ;

tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h00000000B4004BB4), .shared_arith ("off")) \add_0~1  (.cin (\add_0~47_cout ), .cout (\add_0~2 ), .dataa (op[0]), .datab (op[1]), .datac (operand[0]), .datad (\acc[0]~reg0_q ), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~1_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h00000000B4004BB4), .shared_arith ("off")) \add_0~6  (.cin (\add_0~2 ), .cout (\add_0~7 ), .dataa (op[0]), .datab (op[1]), .datac (operand[1]), .datad (\acc[1]~reg0_q ), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~6_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h00000000B4004BB4), .shared_arith ("off")) \add_0~11  (.cin (\add_0~7 ), .cout (\add_0~12 ), .dataa (op[0]), .datab (op[1]), .datac (operand[2]), .datad (\acc[2]~reg0_q ), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~11_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h00000000B4004BB4), .shared_arith ("off")) \add_0~16  (.cin (\add_0~12 ), .cout (\add_0~17 ), .dataa (op[0]), .datab (op[1]), .datac (operand[3]), .datad (\acc[3]~reg0_q ), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~16_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h00000000B4004BB4), .shared_arith ("off")) \add_0~21  (.cin (\add_0~17 ), .cout (\add_0~22 ), .dataa (op[0]), .datab (op[1]), .datac (operand[4]), .datad (\acc[4]~reg0_q ), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~21_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h00000000B4004BB4), .shared_arith ("off")) \add_0~26  (.cin (\add_0~22 ), .cout (\add_0~27 ), .dataa (op[0]), .datab (op[1]), .datac (operand[5]), .datad (\acc[5]~reg0_q ), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~26_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h00000000B4004BB4), .shared_arith ("off")) \add_0~31  (.cin (\add_0~27 ), .cout (\add_0~32 ), .dataa (op[0]), .datab (op[1]), .datac (operand[6]), .datad (\acc[6]~reg0_q ), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~31_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h00000000B4004BB4), .shared_arith ("off")) \add_0~36  (.cin (\add_0~32 ), .cout (\add_0~37 ), .dataa (op[0]), .datab (op[1]), .datac (operand[7]), .datad (\acc[7]~reg0_q ), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~36_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0000000000000000), .shared_arith ("off")) \add_0~41  (.cin (\add_0~37 ), .dataa (gnd), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~41_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000004444BBBB), .shared_arith ("off")) \add_0~47  (.cin (gnd), .cout (\add_0~47_cout ), .dataa (op[0]), .datab (op[1]), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \acc[0]~reg0  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i45~0_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i45~1_combout ), .q (\acc[0]~reg0_q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \acc[1]~reg0  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i45~2_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i45~1_combout ), .q (\acc[1]~reg0_q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \acc[2]~reg0  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i45~3_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i45~1_combout ), .q (\acc[2]~reg0_q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \acc[3]~reg0  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i45~4_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i45~1_combout ), .q (\acc[3]~reg0_q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \acc[4]~reg0  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i45~5_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i45~1_combout ), .q (\acc[4]~reg0_q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \acc[5]~reg0  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i45~6_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i45~1_combout ), .q (\acc[5]~reg0_q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \acc[6]~reg0  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i45~7_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i45~1_combout ), .q (\acc[6]~reg0_q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \acc[7]~reg0  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i45~8_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i45~1_combout ), .q (\acc[7]~reg0_q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \carry~reg0  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i46~0_combout ), .devclrn (devclrn), .devpor (devpor), .ena (\i45~1_combout ), .q (\carry~reg0_q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0001000100010001), .shared_arith ("off")) \reduce_or_0~0  (.cin (gnd), .combout (\reduce_or_0~0_combout ), .dataa (\acc[0]~reg0_q ), .datab (\acc[1]~reg0_q ), .datac (\acc[2]~reg0_q ), .datad (\acc[3]~reg0_q ), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0001000000010000), .shared_arith ("off")) reduce_or_0 (.cin (gnd), .combout (\reduce_or_0~combout ), .dataa (\acc[4]~reg0_q ), .datab (\acc[5]~reg0_q ), .datac (\acc[6]~reg0_q ), .datad (\acc[7]~reg0_q ), .datae (\reduce_or_0~0_combout ), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h7070707070707070), .shared_arith ("off")) \i45~0  (.cin (gnd), .combout (\i45~0_combout ), .dataa (op[0]), .datab (op[1]), .datac (\add_0~1_sumout ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hEEEEEEEEEEEEEEEE), .shared_arith ("off")) \i45~1  (.cin (gnd), .combout (\i45~1_combout ), .dataa (op[0]), .datab (op[1]), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h7070707070707070), .shared_arith ("off")) \i45~2  (.cin (gnd), .combout (\i45~2_combout ), .dataa (op[0]), .datab (op[1]), .datac (\add_0~6_sumout ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h7070707070707070), .shared_arith ("off")) \i45~3  (.cin (gnd), .combout (\i45~3_combout ), .dataa (op[0]), .datab (op[1]), .datac (\add_0~11_sumout ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h7070707070707070), .shared_arith ("off")) \i45~4  (.cin (gnd), .combout (\i45~4_combout ), .dataa (op[0]), .datab (op[1]), .datac (\add_0~16_sumout ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h7070707070707070), .shared_arith ("off")) \i45~5  (.cin (gnd), .combout (\i45~5_combout ), .dataa (op[0]), .datab (op[1]), .datac (\add_0~21_sumout ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h7070707070707070), .shared_arith ("off")) \i45~6  (.cin (gnd), .combout (\i45~6_combout ), .dataa (op[0]), .datab (op[1]), .datac (\add_0~26_sumout ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h7070707070707070), .shared_arith ("off")) \i45~7  (.cin (gnd), .combout (\i45~7_combout ), .dataa (op[0]), .datab (op[1]), .datac (\add_0~31_sumout ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h7070707070707070), .shared_arith ("off")) \i45~8  (.cin (gnd), .combout (\i45~8_combout ), .dataa (op[0]), .datab (op[1]), .datac (\add_0~36_sumout ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h7070707070707070), .shared_arith ("off")) \i46~0  (.cin (gnd), .combout (\i46~0_combout ), .dataa (op[0]), .datab (op[1]), .datac (\add_0~41_sumout ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));

endmodule
