// Generated by tools/hal_agilex from a Quartus Prime Pro EDA netlist export.
// Load with the AGILEX_TENNM gate library.
// source: crc8_checker.vo
// Inversions on ALM data inputs were absorbed into lut_mask; tri1 nets became wires tied to 1'b1.

module crc8_checker (crc, match, din, clk, rst_n, en);
output [7:0] crc;
output match;
input din;
input clk;
input rst_n;
input en;
wire [7:0] crc_r;
wire devclrn;
wire devoe;
wire devpor;
wire \feedback~combout ;
wire gnd;
wire \i8~combout ;
wire \i9~combout ;
wire \reduce_nor_0~0_combout ;
wire \reduce_nor_0~combout ;
wire unknown;
wire vcc;

assign gnd = 1'b0;
assign vcc = 1'b1;
// dropped: assign unknown = 1'bx;  (declared by Quartus, read by nothing)
assign devclrn = 1'b1;
assign devpor = 1'b1;
assign devoe = 1'b1;
assign match = \reduce_nor_0~combout ;
assign crc[0] = crc_r[0];
assign crc[1] = crc_r[1];
assign crc[2] = crc_r[2];
assign crc[3] = crc_r[3];
assign crc[4] = crc_r[4];
assign crc[5] = crc_r[5];
assign crc[6] = crc_r[6];
assign crc[7] = crc_r[7];

tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \crc_r[0]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\feedback~combout ), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (crc_r[0]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \crc_r[1]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i8~combout ), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (crc_r[1]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \crc_r[2]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i9~combout ), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (crc_r[2]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \crc_r[3]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (crc_r[2]), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (crc_r[3]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \crc_r[4]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (crc_r[3]), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (crc_r[4]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \crc_r[5]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (crc_r[4]), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (crc_r[5]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \crc_r[6]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (crc_r[5]), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (crc_r[6]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \crc_r[7]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (crc_r[6]), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (crc_r[7]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0001000100010001), .shared_arith ("off")) \reduce_nor_0~0  (.cin (gnd), .combout (\reduce_nor_0~0_combout ), .dataa (crc_r[0]), .datab (crc_r[1]), .datac (crc_r[2]), .datad (crc_r[3]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0001000000010000), .shared_arith ("off")) reduce_nor_0 (.cin (gnd), .combout (\reduce_nor_0~combout ), .dataa (crc_r[4]), .datab (crc_r[5]), .datac (crc_r[6]), .datad (crc_r[7]), .datae (\reduce_nor_0~0_combout ), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h6666666666666666), .shared_arith ("off")) feedback (.cin (gnd), .combout (\feedback~combout ), .dataa (crc_r[7]), .datab (din), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h9696969696969696), .shared_arith ("off")) i8 (.cin (gnd), .combout (\i8~combout ), .dataa (crc_r[0]), .datab (crc_r[7]), .datac (din), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h9696969696969696), .shared_arith ("off")) i9 (.cin (gnd), .combout (\i9~combout ), .dataa (crc_r[1]), .datab (crc_r[7]), .datac (din), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));

endmodule
