// Generated by tools/hal_secprop/fixtures/generate.py -- do not edit.
// Gate library: NangateOpenCellLibrary (plugins/gate_libraries/definitions/NangateOpenCellLibrary.hgl)
// All names are stripped: ports are io_NN, nets nNNN, instances gNNN.

module secreg_faulty (
    io_00,
    io_01,
    io_02,
    io_03,
    io_04,
    io_05,
    io_06,
    io_07,
    io_08,
    io_09,
    io_10,
    io_11,
    io_12,
    io_13,
    io_14,
    io_15,
    io_16,
    io_17
);
  input io_00;
  input io_01;
  input io_02;
  input io_03;
  input io_04;
  input io_05;
  input io_06;
  input io_07;
  input io_08;
  input io_09;
  input io_10;
  input io_11;
  input io_12;
  output io_13;
  output io_14;
  output io_15;
  output io_16;
  output io_17;

  wire n000;
  wire n001;
  wire n002;
  wire n003;
  wire n004;
  wire n005;
  wire n006;
  wire n007;
  wire n008;
  wire n009;
  wire n010;
  wire n011;
  wire n012;
  wire n013;
  wire n014;
  wire n015;
  wire n016;
  wire n017;
  wire n018;
  wire n019;
  wire n020;
  wire n021;
  wire n022;
  wire n023;
  wire n024;
  wire n025;
  wire n026;
  wire n027;
  wire n028;
  wire n029;
  wire n030;
  wire n031;
  wire n032;
  wire n033;
  wire n034;
  wire n035;
  wire n036;

  AND2_X1 g000 (
    .A1(io_02),
    .A2(io_03),
    .ZN(n000)
  );
  AND2_X1 g001 (
    .A1(n000),
    .A2(io_04),
    .ZN(n001)
  );
  INV_X1 g002 (
    .A(io_04),
    .ZN(n002)
  );
  AND2_X1 g003 (
    .A1(n000),
    .A2(n002),
    .ZN(n003)
  );
  INV_X1 g004 (
    .A(io_06),
    .ZN(n004)
  );
  INV_X1 g005 (
    .A(io_07),
    .ZN(n005)
  );
  INV_X1 g006 (
    .A(io_08),
    .ZN(n006)
  );
  AND2_X1 g007 (
    .A1(n004),
    .A2(n005),
    .ZN(n007)
  );
  AND2_X1 g008 (
    .A1(n007),
    .A2(n006),
    .ZN(n008)
  );
  AND2_X1 g009 (
    .A1(io_06),
    .A2(n005),
    .ZN(n009)
  );
  AND2_X1 g010 (
    .A1(n009),
    .A2(n006),
    .ZN(n010)
  );
  AND2_X1 g011 (
    .A1(n004),
    .A2(io_07),
    .ZN(n011)
  );
  AND2_X1 g012 (
    .A1(n011),
    .A2(n006),
    .ZN(n012)
  );
  AND2_X1 g013 (
    .A1(n001),
    .A2(n008),
    .ZN(n014)
  );
  AND2_X1 g014 (
    .A1(n014),
    .A2(io_09),
    .ZN(n015)
  );
  OR2_X1 g015 (
    .A1(n013),
    .A2(n015),
    .ZN(n016)
  );
  DFFR_X1 g016 (
    .CK(io_00),
    .D(n016),
    .Q(n013),
    .RN(io_01)
  );
  INV_X1 g017 (
    .A(n013),
    .ZN(n017)
  );
  AND2_X1 g018 (
    .A1(n001),
    .A2(n010),
    .ZN(n018)
  );
  AND2_X1 g019 (
    .A1(n018),
    .A2(n017),
    .ZN(n019)
  );
  AND2_X1 g020 (
    .A1(n001),
    .A2(n012),
    .ZN(n020)
  );
  AND2_X1 g021 (
    .A1(n020),
    .A2(io_05),
    .ZN(n021)
  );
  OR2_X1 g022 (
    .A1(n019),
    .A2(n021),
    .ZN(n022)
  );
  MUX2_X1 g023 (
    .A(n023),
    .B(io_09),
    .S(n022),
    .Z(n027)
  );
  DFFR_X1 g024 (
    .CK(io_00),
    .D(n027),
    .Q(n023),
    .RN(io_01)
  );
  MUX2_X1 g025 (
    .A(n024),
    .B(io_10),
    .S(n022),
    .Z(n028)
  );
  DFFR_X1 g026 (
    .CK(io_00),
    .D(n028),
    .Q(n024),
    .RN(io_01)
  );
  MUX2_X1 g027 (
    .A(n025),
    .B(io_11),
    .S(n022),
    .Z(n029)
  );
  DFFR_X1 g028 (
    .CK(io_00),
    .D(n029),
    .Q(n025),
    .RN(io_01)
  );
  MUX2_X1 g029 (
    .A(n026),
    .B(io_12),
    .S(n022),
    .Z(n030)
  );
  DFFS_X1 g030 (
    .CK(io_00),
    .D(n030),
    .Q(n026),
    .SN(io_01)
  );
  AND2_X1 g031 (
    .A1(n010),
    .A2(n023),
    .ZN(n031)
  );
  AND2_X1 g032 (
    .A1(n008),
    .A2(n013),
    .ZN(n032)
  );
  OR2_X1 g033 (
    .A1(n031),
    .A2(n032),
    .ZN(n033)
  );
  AND2_X1 g034 (
    .A1(n003),
    .A2(n033),
    .ZN(io_13)
  );
  AND2_X1 g035 (
    .A1(n010),
    .A2(n024),
    .ZN(n034)
  );
  AND2_X1 g036 (
    .A1(n003),
    .A2(n034),
    .ZN(io_14)
  );
  AND2_X1 g037 (
    .A1(n010),
    .A2(n025),
    .ZN(n035)
  );
  AND2_X1 g038 (
    .A1(n003),
    .A2(n035),
    .ZN(io_15)
  );
  AND2_X1 g039 (
    .A1(n010),
    .A2(n026),
    .ZN(n036)
  );
  AND2_X1 g040 (
    .A1(n003),
    .A2(n036),
    .ZN(io_16)
  );
  DFFR_X1 g041 (
    .CK(io_00),
    .D(n000),
    .Q(io_17),
    .RN(io_01)
  );
endmodule
