// Generated by tools/hal_apb_recover/fixtures/apb_regs/generate.py -- do not edit.
// Gate library: NangateOpenCellLibrary (plugins/gate_libraries/definitions/NangateOpenCellLibrary.hgl)
// All names are stripped: ports are io_NN, nets nNNN, instances gNNN.

module apb_regs (
    io_00,
    io_01,
    io_02,
    io_03,
    io_04,
    io_05,
    io_06,
    io_07,
    io_08,
    io_09,
    io_10,
    io_11,
    io_12,
    io_13,
    io_14,
    io_15,
    io_16,
    io_17,
    io_18,
    io_19,
    io_20,
    io_21,
    io_22,
    io_23,
    io_24,
    io_25,
    io_26,
    io_27,
    io_28,
    io_29,
    io_30,
    io_31,
    io_32,
    io_33,
    io_34,
    io_35,
    io_36,
    io_37,
    io_38,
    io_39,
    io_40,
    io_41,
    io_42,
    io_43,
    io_44,
    io_45,
    io_46,
    io_47,
    io_48,
    io_49,
    io_50,
    io_51,
    io_52,
    io_53
);
  input io_00;
  input io_01;
  input io_02;
  input io_03;
  input io_04;
  output io_05;
  input io_06;
  input io_07;
  input io_08;
  input io_09;
  input io_10;
  input io_11;
  input io_12;
  input io_13;
  input io_14;
  input io_15;
  input io_16;
  input io_17;
  input io_18;
  input io_19;
  input io_20;
  input io_21;
  input io_22;
  input io_23;
  input io_24;
  input io_25;
  input io_26;
  output io_27;
  output io_28;
  output io_29;
  output io_30;
  output io_31;
  output io_32;
  output io_33;
  output io_34;
  output io_35;
  output io_36;
  output io_37;
  output io_38;
  output io_39;
  output io_40;
  output io_41;
  output io_42;
  input io_43;
  input io_44;
  input io_45;
  input io_46;
  input io_47;
  input io_48;
  input io_49;
  input io_50;
  input io_51;
  input io_52;
  input io_53;

  wire n000;
  wire n001;
  wire n002;
  wire n003;
  wire n004;
  wire n005;
  wire n006;
  wire n007;
  wire n008;
  wire n009;
  wire n010;
  wire n011;
  wire n012;
  wire n013;
  wire n014;
  wire n015;
  wire n016;
  wire n017;
  wire n018;
  wire n019;
  wire n020;
  wire n021;
  wire n022;
  wire n023;
  wire n024;
  wire n025;
  wire n026;
  wire n027;
  wire n028;
  wire n029;
  wire n030;
  wire n031;
  wire n032;
  wire n033;
  wire n034;
  wire n035;
  wire n036;
  wire n037;
  wire n038;
  wire n039;
  wire n040;
  wire n041;
  wire n042;
  wire n043;
  wire n044;
  wire n045;
  wire n046;
  wire n047;
  wire n048;
  wire n049;
  wire n050;
  wire n051;
  wire n052;
  wire n053;
  wire n054;
  wire n055;
  wire n056;
  wire n057;
  wire n058;
  wire n059;
  wire n060;
  wire n061;
  wire n062;
  wire n063;
  wire n064;
  wire n065;
  wire n066;
  wire n067;
  wire n068;
  wire n069;
  wire n070;
  wire n071;
  wire n072;
  wire n073;
  wire n074;
  wire n075;
  wire n076;
  wire n077;
  wire n078;
  wire n079;
  wire n080;
  wire n081;
  wire n082;
  wire n083;
  wire n084;
  wire n085;
  wire n086;
  wire n087;
  wire n088;
  wire n089;
  wire n090;
  wire n091;
  wire n092;
  wire n093;
  wire n094;
  wire n095;
  wire n096;
  wire n097;
  wire n098;
  wire n099;
  wire n100;
  wire n101;
  wire n102;
  wire n103;
  wire n104;
  wire n105;
  wire n106;
  wire n107;
  wire n108;
  wire n109;
  wire n110;
  wire n111;
  wire n112;
  wire n113;
  wire n114;
  wire n115;
  wire n116;
  wire n117;
  wire n118;
  wire n119;
  wire n120;
  wire n121;
  wire n122;
  wire n123;
  wire n124;
  wire n125;
  wire n126;
  wire n127;
  wire n128;
  wire n129;
  wire n130;
  wire n131;
  wire n132;
  wire n133;
  wire n134;
  wire n135;
  wire n136;
  wire n137;
  wire n138;
  wire n139;
  wire n140;
  wire n141;
  wire n142;
  wire n143;
  wire n144;
  wire n145;
  wire n146;
  wire n147;
  wire n148;
  wire n149;
  wire n150;
  wire n151;
  wire n152;
  wire n153;
  wire n154;
  wire n155;
  wire n156;
  wire n157;
  wire n158;
  wire n159;
  wire n160;
  wire n161;
  wire n162;
  wire n163;
  wire n164;
  wire n165;
  wire n166;
  wire n167;
  wire n168;
  wire n169;
  wire n170;
  wire n171;
  wire n172;
  wire n173;
  wire n174;
  wire n175;
  wire n176;
  wire n177;
  wire n178;
  wire n179;
  wire n180;
  wire n181;
  wire n182;
  wire n183;
  wire n184;
  wire n185;
  wire n186;
  wire n187;
  wire n188;
  wire n189;
  wire n190;
  wire n191;
  wire n192;
  wire n193;
  wire n194;
  wire n195;
  wire n196;
  wire n197;
  wire n198;
  wire n199;
  wire n200;
  wire n201;
  wire n202;
  wire n203;
  wire n204;
  wire n205;
  wire n206;

  INV_X1 g000 (
    .A(io_04),
    .ZN(n000)
  );
  AND2_X1 g001 (
    .A1(io_02),
    .A2(io_03),
    .ZN(n001)
  );
  AND2_X1 g002 (
    .A1(n001),
    .A2(io_04),
    .ZN(n002)
  );
  AND2_X1 g003 (
    .A1(n001),
    .A2(n000),
    .ZN(n003)
  );
  XOR2_X1 g004 (
    .A(io_06),
    .B(io_07),
    .Z(n004)
  );
  INV_X1 g005 (
    .A(io_08),
    .ZN(n005)
  );
  INV_X1 g006 (
    .A(io_09),
    .ZN(n006)
  );
  INV_X1 g007 (
    .A(io_10),
    .ZN(n007)
  );
  AND2_X1 g008 (
    .A1(n005),
    .A2(n006),
    .ZN(n008)
  );
  AND2_X1 g009 (
    .A1(n008),
    .A2(n007),
    .ZN(n009)
  );
  AND2_X1 g010 (
    .A1(io_08),
    .A2(n006),
    .ZN(n010)
  );
  AND2_X1 g011 (
    .A1(n010),
    .A2(n007),
    .ZN(n011)
  );
  AND2_X1 g012 (
    .A1(n005),
    .A2(io_09),
    .ZN(n012)
  );
  AND2_X1 g013 (
    .A1(n012),
    .A2(n007),
    .ZN(n013)
  );
  AND2_X1 g014 (
    .A1(io_08),
    .A2(io_09),
    .ZN(n014)
  );
  AND2_X1 g015 (
    .A1(n014),
    .A2(n007),
    .ZN(n015)
  );
  AND2_X1 g016 (
    .A1(n005),
    .A2(n006),
    .ZN(n016)
  );
  AND2_X1 g017 (
    .A1(n016),
    .A2(io_10),
    .ZN(n017)
  );
  OR2_X1 g018 (
    .A1(n009),
    .A2(n013),
    .ZN(n018)
  );
  AND2_X1 g019 (
    .A1(n002),
    .A2(n018),
    .ZN(n019)
  );
  AND2_X1 g020 (
    .A1(n019),
    .A2(io_43),
    .ZN(n020)
  );
  AND2_X1 g021 (
    .A1(n019),
    .A2(io_44),
    .ZN(n021)
  );
  AND2_X1 g022 (
    .A1(n002),
    .A2(n011),
    .ZN(n022)
  );
  AND2_X1 g023 (
    .A1(n022),
    .A2(io_43),
    .ZN(n023)
  );
  INV_X1 g024 (
    .A(io_53),
    .ZN(n040)
  );
  MUX2_X1 g025 (
    .A(n024),
    .B(io_11),
    .S(n020),
    .Z(n041)
  );
  DFFR_X1 g026 (
    .CK(io_00),
    .D(n041),
    .Q(n024),
    .RN(io_01)
  );
  MUX2_X1 g027 (
    .A(n025),
    .B(io_12),
    .S(n020),
    .Z(n042)
  );
  DFFR_X1 g028 (
    .CK(io_00),
    .D(n042),
    .Q(n025),
    .RN(io_01)
  );
  MUX2_X1 g029 (
    .A(n026),
    .B(io_13),
    .S(n020),
    .Z(n043)
  );
  DFFR_X1 g030 (
    .CK(io_00),
    .D(n043),
    .Q(n026),
    .RN(io_01)
  );
  MUX2_X1 g031 (
    .A(n027),
    .B(io_14),
    .S(n020),
    .Z(n044)
  );
  DFFR_X1 g032 (
    .CK(io_00),
    .D(n044),
    .Q(n027),
    .RN(io_01)
  );
  MUX2_X1 g033 (
    .A(n028),
    .B(io_15),
    .S(n020),
    .Z(n045)
  );
  DFFR_X1 g034 (
    .CK(io_00),
    .D(n045),
    .Q(n028),
    .RN(io_01)
  );
  MUX2_X1 g035 (
    .A(n029),
    .B(io_16),
    .S(n020),
    .Z(n046)
  );
  DFFR_X1 g036 (
    .CK(io_00),
    .D(n046),
    .Q(n029),
    .RN(io_01)
  );
  MUX2_X1 g037 (
    .A(n030),
    .B(io_17),
    .S(n020),
    .Z(n047)
  );
  DFFR_X1 g038 (
    .CK(io_00),
    .D(n047),
    .Q(n030),
    .RN(io_01)
  );
  MUX2_X1 g039 (
    .A(n031),
    .B(io_18),
    .S(n020),
    .Z(n048)
  );
  DFFR_X1 g040 (
    .CK(io_00),
    .D(n048),
    .Q(n031),
    .RN(io_01)
  );
  MUX2_X1 g041 (
    .A(n032),
    .B(io_19),
    .S(n021),
    .Z(n049)
  );
  DFFR_X1 g042 (
    .CK(io_00),
    .D(n049),
    .Q(n032),
    .RN(io_01)
  );
  MUX2_X1 g043 (
    .A(n033),
    .B(io_20),
    .S(n021),
    .Z(n050)
  );
  DFFR_X1 g044 (
    .CK(io_00),
    .D(n050),
    .Q(n033),
    .RN(io_01)
  );
  MUX2_X1 g045 (
    .A(n034),
    .B(io_21),
    .S(n021),
    .Z(n051)
  );
  DFFR_X1 g046 (
    .CK(io_00),
    .D(n051),
    .Q(n034),
    .RN(io_01)
  );
  MUX2_X1 g047 (
    .A(n035),
    .B(io_22),
    .S(n021),
    .Z(n052)
  );
  DFFR_X1 g048 (
    .CK(io_00),
    .D(n052),
    .Q(n035),
    .RN(io_01)
  );
  MUX2_X1 g049 (
    .A(n036),
    .B(io_23),
    .S(n021),
    .Z(n053)
  );
  DFFR_X1 g050 (
    .CK(io_00),
    .D(n053),
    .Q(n036),
    .RN(io_01)
  );
  MUX2_X1 g051 (
    .A(n037),
    .B(io_24),
    .S(n021),
    .Z(n054)
  );
  DFFR_X1 g052 (
    .CK(io_00),
    .D(n054),
    .Q(n037),
    .RN(io_01)
  );
  MUX2_X1 g053 (
    .A(n038),
    .B(io_25),
    .S(n021),
    .Z(n055)
  );
  DFFR_X1 g054 (
    .CK(io_00),
    .D(n055),
    .Q(n038),
    .RN(io_01)
  );
  MUX2_X1 g055 (
    .A(n039),
    .B(io_26),
    .S(n021),
    .Z(n056)
  );
  AND2_X1 g056 (
    .A1(n056),
    .A2(n040),
    .ZN(n057)
  );
  DFFR_X1 g057 (
    .CK(io_00),
    .D(n057),
    .Q(n039),
    .RN(io_01)
  );
  OR2_X1 g058 (
    .A1(n058),
    .A2(io_45),
    .ZN(n066)
  );
  AND2_X1 g059 (
    .A1(n023),
    .A2(io_11),
    .ZN(n067)
  );
  INV_X1 g060 (
    .A(n067),
    .ZN(n068)
  );
  AND2_X1 g061 (
    .A1(n066),
    .A2(n068),
    .ZN(n069)
  );
  DFFR_X1 g062 (
    .CK(io_00),
    .D(n069),
    .Q(n058),
    .RN(io_01)
  );
  OR2_X1 g063 (
    .A1(n059),
    .A2(io_46),
    .ZN(n070)
  );
  AND2_X1 g064 (
    .A1(n023),
    .A2(io_12),
    .ZN(n071)
  );
  INV_X1 g065 (
    .A(n071),
    .ZN(n072)
  );
  AND2_X1 g066 (
    .A1(n070),
    .A2(n072),
    .ZN(n073)
  );
  DFFR_X1 g067 (
    .CK(io_00),
    .D(n073),
    .Q(n059),
    .RN(io_01)
  );
  OR2_X1 g068 (
    .A1(n060),
    .A2(io_47),
    .ZN(n074)
  );
  AND2_X1 g069 (
    .A1(n023),
    .A2(io_13),
    .ZN(n075)
  );
  INV_X1 g070 (
    .A(n075),
    .ZN(n076)
  );
  AND2_X1 g071 (
    .A1(n074),
    .A2(n076),
    .ZN(n077)
  );
  DFFR_X1 g072 (
    .CK(io_00),
    .D(n077),
    .Q(n060),
    .RN(io_01)
  );
  OR2_X1 g073 (
    .A1(n061),
    .A2(io_48),
    .ZN(n078)
  );
  AND2_X1 g074 (
    .A1(n023),
    .A2(io_14),
    .ZN(n079)
  );
  INV_X1 g075 (
    .A(n079),
    .ZN(n080)
  );
  AND2_X1 g076 (
    .A1(n078),
    .A2(n080),
    .ZN(n081)
  );
  DFFR_X1 g077 (
    .CK(io_00),
    .D(n081),
    .Q(n061),
    .RN(io_01)
  );
  OR2_X1 g078 (
    .A1(n062),
    .A2(io_49),
    .ZN(n082)
  );
  AND2_X1 g079 (
    .A1(n023),
    .A2(io_15),
    .ZN(n083)
  );
  INV_X1 g080 (
    .A(n083),
    .ZN(n084)
  );
  AND2_X1 g081 (
    .A1(n082),
    .A2(n084),
    .ZN(n085)
  );
  DFFR_X1 g082 (
    .CK(io_00),
    .D(n085),
    .Q(n062),
    .RN(io_01)
  );
  OR2_X1 g083 (
    .A1(n063),
    .A2(io_50),
    .ZN(n086)
  );
  AND2_X1 g084 (
    .A1(n023),
    .A2(io_16),
    .ZN(n087)
  );
  INV_X1 g085 (
    .A(n087),
    .ZN(n088)
  );
  AND2_X1 g086 (
    .A1(n086),
    .A2(n088),
    .ZN(n089)
  );
  DFFR_X1 g087 (
    .CK(io_00),
    .D(n089),
    .Q(n063),
    .RN(io_01)
  );
  OR2_X1 g088 (
    .A1(n064),
    .A2(io_51),
    .ZN(n090)
  );
  AND2_X1 g089 (
    .A1(n023),
    .A2(io_17),
    .ZN(n091)
  );
  INV_X1 g090 (
    .A(n091),
    .ZN(n092)
  );
  AND2_X1 g091 (
    .A1(n090),
    .A2(n092),
    .ZN(n093)
  );
  DFFR_X1 g092 (
    .CK(io_00),
    .D(n093),
    .Q(n064),
    .RN(io_01)
  );
  OR2_X1 g093 (
    .A1(n065),
    .A2(io_52),
    .ZN(n094)
  );
  AND2_X1 g094 (
    .A1(n023),
    .A2(io_18),
    .ZN(n095)
  );
  INV_X1 g095 (
    .A(n095),
    .ZN(n096)
  );
  AND2_X1 g096 (
    .A1(n094),
    .A2(n096),
    .ZN(n097)
  );
  DFFR_X1 g097 (
    .CK(io_00),
    .D(n097),
    .Q(n065),
    .RN(io_01)
  );
  AND2_X1 g098 (
    .A1(n002),
    .A2(n017),
    .ZN(n098)
  );
  AND2_X1 g099 (
    .A1(n098),
    .A2(n024),
    .ZN(n099)
  );
  AND2_X1 g100 (
    .A1(n099),
    .A2(io_43),
    .ZN(n100)
  );
  AND2_X1 g101 (
    .A1(n099),
    .A2(io_44),
    .ZN(n101)
  );
  MUX2_X1 g102 (
    .A(n102),
    .B(io_11),
    .S(n100),
    .Z(n118)
  );
  DFFS_X1 g103 (
    .CK(io_00),
    .D(n118),
    .Q(n102),
    .SN(io_01)
  );
  MUX2_X1 g104 (
    .A(n103),
    .B(io_12),
    .S(n100),
    .Z(n119)
  );
  DFFS_X1 g105 (
    .CK(io_00),
    .D(n119),
    .Q(n103),
    .SN(io_01)
  );
  MUX2_X1 g106 (
    .A(n104),
    .B(io_13),
    .S(n100),
    .Z(n120)
  );
  DFFS_X1 g107 (
    .CK(io_00),
    .D(n120),
    .Q(n104),
    .SN(io_01)
  );
  MUX2_X1 g108 (
    .A(n105),
    .B(io_14),
    .S(n100),
    .Z(n121)
  );
  DFFS_X1 g109 (
    .CK(io_00),
    .D(n121),
    .Q(n105),
    .SN(io_01)
  );
  MUX2_X1 g110 (
    .A(n106),
    .B(io_15),
    .S(n100),
    .Z(n122)
  );
  DFFR_X1 g111 (
    .CK(io_00),
    .D(n122),
    .Q(n106),
    .RN(io_01)
  );
  MUX2_X1 g112 (
    .A(n107),
    .B(io_16),
    .S(n100),
    .Z(n123)
  );
  DFFS_X1 g113 (
    .CK(io_00),
    .D(n123),
    .Q(n107),
    .SN(io_01)
  );
  MUX2_X1 g114 (
    .A(n108),
    .B(io_17),
    .S(n100),
    .Z(n124)
  );
  DFFS_X1 g115 (
    .CK(io_00),
    .D(n124),
    .Q(n108),
    .SN(io_01)
  );
  MUX2_X1 g116 (
    .A(n109),
    .B(io_18),
    .S(n100),
    .Z(n125)
  );
  DFFS_X1 g117 (
    .CK(io_00),
    .D(n125),
    .Q(n109),
    .SN(io_01)
  );
  MUX2_X1 g118 (
    .A(n110),
    .B(io_19),
    .S(n101),
    .Z(n126)
  );
  DFFR_X1 g119 (
    .CK(io_00),
    .D(n126),
    .Q(n110),
    .RN(io_01)
  );
  MUX2_X1 g120 (
    .A(n111),
    .B(io_20),
    .S(n101),
    .Z(n127)
  );
  DFFS_X1 g121 (
    .CK(io_00),
    .D(n127),
    .Q(n111),
    .SN(io_01)
  );
  MUX2_X1 g122 (
    .A(n112),
    .B(io_21),
    .S(n101),
    .Z(n128)
  );
  DFFS_X1 g123 (
    .CK(io_00),
    .D(n128),
    .Q(n112),
    .SN(io_01)
  );
  MUX2_X1 g124 (
    .A(n113),
    .B(io_22),
    .S(n101),
    .Z(n129)
  );
  DFFS_X1 g125 (
    .CK(io_00),
    .D(n129),
    .Q(n113),
    .SN(io_01)
  );
  MUX2_X1 g126 (
    .A(n114),
    .B(io_23),
    .S(n101),
    .Z(n130)
  );
  DFFS_X1 g127 (
    .CK(io_00),
    .D(n130),
    .Q(n114),
    .SN(io_01)
  );
  MUX2_X1 g128 (
    .A(n115),
    .B(io_24),
    .S(n101),
    .Z(n131)
  );
  DFFS_X1 g129 (
    .CK(io_00),
    .D(n131),
    .Q(n115),
    .SN(io_01)
  );
  MUX2_X1 g130 (
    .A(n116),
    .B(io_25),
    .S(n101),
    .Z(n132)
  );
  DFFR_X1 g131 (
    .CK(io_00),
    .D(n132),
    .Q(n116),
    .RN(io_01)
  );
  MUX2_X1 g132 (
    .A(n117),
    .B(io_26),
    .S(n101),
    .Z(n133)
  );
  DFFS_X1 g133 (
    .CK(io_00),
    .D(n133),
    .Q(n117),
    .SN(io_01)
  );
  AND2_X1 g134 (
    .A1(n018),
    .A2(n024),
    .ZN(n134)
  );
  AND2_X1 g135 (
    .A1(n011),
    .A2(n058),
    .ZN(n135)
  );
  AND2_X1 g136 (
    .A1(n017),
    .A2(n102),
    .ZN(n136)
  );
  OR2_X1 g137 (
    .A1(n134),
    .A2(n135),
    .ZN(n137)
  );
  OR2_X1 g138 (
    .A1(n137),
    .A2(n136),
    .ZN(n138)
  );
  AND2_X1 g139 (
    .A1(n003),
    .A2(n138),
    .ZN(io_27)
  );
  AND2_X1 g140 (
    .A1(n018),
    .A2(n025),
    .ZN(n139)
  );
  AND2_X1 g141 (
    .A1(n011),
    .A2(n059),
    .ZN(n140)
  );
  AND2_X1 g142 (
    .A1(n017),
    .A2(n103),
    .ZN(n141)
  );
  OR2_X1 g143 (
    .A1(n139),
    .A2(n140),
    .ZN(n142)
  );
  OR2_X1 g144 (
    .A1(n142),
    .A2(n141),
    .ZN(n143)
  );
  AND2_X1 g145 (
    .A1(n003),
    .A2(n143),
    .ZN(io_28)
  );
  AND2_X1 g146 (
    .A1(n018),
    .A2(n026),
    .ZN(n144)
  );
  AND2_X1 g147 (
    .A1(n011),
    .A2(n060),
    .ZN(n145)
  );
  AND2_X1 g148 (
    .A1(n017),
    .A2(n104),
    .ZN(n146)
  );
  OR2_X1 g149 (
    .A1(n144),
    .A2(n145),
    .ZN(n147)
  );
  OR2_X1 g150 (
    .A1(n147),
    .A2(n015),
    .ZN(n148)
  );
  OR2_X1 g151 (
    .A1(n148),
    .A2(n146),
    .ZN(n149)
  );
  AND2_X1 g152 (
    .A1(n003),
    .A2(n149),
    .ZN(io_29)
  );
  AND2_X1 g153 (
    .A1(n018),
    .A2(n027),
    .ZN(n150)
  );
  AND2_X1 g154 (
    .A1(n011),
    .A2(n061),
    .ZN(n151)
  );
  AND2_X1 g155 (
    .A1(n017),
    .A2(n105),
    .ZN(n152)
  );
  OR2_X1 g156 (
    .A1(n150),
    .A2(n151),
    .ZN(n153)
  );
  OR2_X1 g157 (
    .A1(n153),
    .A2(n015),
    .ZN(n154)
  );
  OR2_X1 g158 (
    .A1(n154),
    .A2(n152),
    .ZN(n155)
  );
  AND2_X1 g159 (
    .A1(n003),
    .A2(n155),
    .ZN(io_30)
  );
  AND2_X1 g160 (
    .A1(n018),
    .A2(n028),
    .ZN(n156)
  );
  AND2_X1 g161 (
    .A1(n011),
    .A2(n062),
    .ZN(n157)
  );
  AND2_X1 g162 (
    .A1(n017),
    .A2(n106),
    .ZN(n158)
  );
  OR2_X1 g163 (
    .A1(n156),
    .A2(n157),
    .ZN(n159)
  );
  OR2_X1 g164 (
    .A1(n159),
    .A2(n015),
    .ZN(n160)
  );
  OR2_X1 g165 (
    .A1(n160),
    .A2(n158),
    .ZN(n161)
  );
  AND2_X1 g166 (
    .A1(n003),
    .A2(n161),
    .ZN(io_31)
  );
  AND2_X1 g167 (
    .A1(n018),
    .A2(n029),
    .ZN(n162)
  );
  AND2_X1 g168 (
    .A1(n011),
    .A2(n063),
    .ZN(n163)
  );
  AND2_X1 g169 (
    .A1(n017),
    .A2(n107),
    .ZN(n164)
  );
  OR2_X1 g170 (
    .A1(n162),
    .A2(n163),
    .ZN(n165)
  );
  OR2_X1 g171 (
    .A1(n165),
    .A2(n015),
    .ZN(n166)
  );
  OR2_X1 g172 (
    .A1(n166),
    .A2(n164),
    .ZN(n167)
  );
  AND2_X1 g173 (
    .A1(n003),
    .A2(n167),
    .ZN(io_32)
  );
  AND2_X1 g174 (
    .A1(n018),
    .A2(n030),
    .ZN(n168)
  );
  AND2_X1 g175 (
    .A1(n011),
    .A2(n064),
    .ZN(n169)
  );
  AND2_X1 g176 (
    .A1(n017),
    .A2(n108),
    .ZN(n170)
  );
  OR2_X1 g177 (
    .A1(n168),
    .A2(n169),
    .ZN(n171)
  );
  OR2_X1 g178 (
    .A1(n171),
    .A2(n170),
    .ZN(n172)
  );
  AND2_X1 g179 (
    .A1(n003),
    .A2(n172),
    .ZN(io_33)
  );
  AND2_X1 g180 (
    .A1(n018),
    .A2(n031),
    .ZN(n173)
  );
  AND2_X1 g181 (
    .A1(n011),
    .A2(n065),
    .ZN(n174)
  );
  AND2_X1 g182 (
    .A1(n017),
    .A2(n109),
    .ZN(n175)
  );
  OR2_X1 g183 (
    .A1(n173),
    .A2(n174),
    .ZN(n176)
  );
  OR2_X1 g184 (
    .A1(n176),
    .A2(n175),
    .ZN(n177)
  );
  AND2_X1 g185 (
    .A1(n003),
    .A2(n177),
    .ZN(io_34)
  );
  AND2_X1 g186 (
    .A1(n018),
    .A2(n032),
    .ZN(n178)
  );
  AND2_X1 g187 (
    .A1(n017),
    .A2(n110),
    .ZN(n179)
  );
  OR2_X1 g188 (
    .A1(n178),
    .A2(n015),
    .ZN(n180)
  );
  OR2_X1 g189 (
    .A1(n180),
    .A2(n179),
    .ZN(n181)
  );
  AND2_X1 g190 (
    .A1(n003),
    .A2(n181),
    .ZN(io_35)
  );
  AND2_X1 g191 (
    .A1(n018),
    .A2(n033),
    .ZN(n182)
  );
  AND2_X1 g192 (
    .A1(n017),
    .A2(n111),
    .ZN(n183)
  );
  OR2_X1 g193 (
    .A1(n182),
    .A2(n183),
    .ZN(n184)
  );
  AND2_X1 g194 (
    .A1(n003),
    .A2(n184),
    .ZN(io_36)
  );
  AND2_X1 g195 (
    .A1(n018),
    .A2(n034),
    .ZN(n185)
  );
  AND2_X1 g196 (
    .A1(n017),
    .A2(n112),
    .ZN(n186)
  );
  OR2_X1 g197 (
    .A1(n185),
    .A2(n015),
    .ZN(n187)
  );
  OR2_X1 g198 (
    .A1(n187),
    .A2(n186),
    .ZN(n188)
  );
  AND2_X1 g199 (
    .A1(n003),
    .A2(n188),
    .ZN(io_37)
  );
  AND2_X1 g200 (
    .A1(n018),
    .A2(n035),
    .ZN(n189)
  );
  AND2_X1 g201 (
    .A1(n017),
    .A2(n113),
    .ZN(n190)
  );
  OR2_X1 g202 (
    .A1(n189),
    .A2(n190),
    .ZN(n191)
  );
  AND2_X1 g203 (
    .A1(n003),
    .A2(n191),
    .ZN(io_38)
  );
  AND2_X1 g204 (
    .A1(n018),
    .A2(n036),
    .ZN(n192)
  );
  AND2_X1 g205 (
    .A1(n017),
    .A2(n114),
    .ZN(n193)
  );
  OR2_X1 g206 (
    .A1(n192),
    .A2(n193),
    .ZN(n194)
  );
  AND2_X1 g207 (
    .A1(n003),
    .A2(n194),
    .ZN(io_39)
  );
  AND2_X1 g208 (
    .A1(n018),
    .A2(n037),
    .ZN(n195)
  );
  AND2_X1 g209 (
    .A1(n017),
    .A2(n115),
    .ZN(n196)
  );
  OR2_X1 g210 (
    .A1(n195),
    .A2(n015),
    .ZN(n197)
  );
  OR2_X1 g211 (
    .A1(n197),
    .A2(n196),
    .ZN(n198)
  );
  AND2_X1 g212 (
    .A1(n003),
    .A2(n198),
    .ZN(io_40)
  );
  AND2_X1 g213 (
    .A1(n018),
    .A2(n038),
    .ZN(n199)
  );
  AND2_X1 g214 (
    .A1(n017),
    .A2(n116),
    .ZN(n200)
  );
  OR2_X1 g215 (
    .A1(n199),
    .A2(n200),
    .ZN(n201)
  );
  AND2_X1 g216 (
    .A1(n003),
    .A2(n201),
    .ZN(io_41)
  );
  AND2_X1 g217 (
    .A1(n018),
    .A2(n039),
    .ZN(n202)
  );
  AND2_X1 g218 (
    .A1(n017),
    .A2(n117),
    .ZN(n203)
  );
  OR2_X1 g219 (
    .A1(n202),
    .A2(n015),
    .ZN(n204)
  );
  OR2_X1 g220 (
    .A1(n204),
    .A2(n203),
    .ZN(n205)
  );
  AND2_X1 g221 (
    .A1(n003),
    .A2(n205),
    .ZN(io_42)
  );
  LOGIC1_X1 g222 (
    .Z(n206)
  );
  DLH_X1 g223 (
    .D(n001),
    .G(n206),
    .Q(io_05)
  );
endmodule
