// Generated by tools/hal_agilex from a Quartus Prime Pro EDA netlist export.
// Load with the AGILEX_TENNM gate library.
// source: shift_debouncer.vo
// Inversions on ALM data inputs were absorbed into lut_mask; tri1 nets became wires tied to 1'b1.

module shift_debouncer (btn_state, btn_rise, clk, rst_n, btn_raw);
output btn_state;
output btn_rise;
input clk;
input rst_n;
input btn_raw;
wire \btn_rise~0_combout ;
wire [3:0] cnt;
wire \cnt[0]~1_combout ;
wire \cnt[1]~2_combout ;
wire \cnt[2]~3_combout ;
wire \cnt[3]~0_combout ;
wire devclrn;
wire devoe;
wire devpor;
wire gnd;
wire \i38~0_combout ;
wire \state_d~q ;
wire \state~q ;
wire [1:0] sync;
wire unknown;
wire vcc;

assign gnd = 1'b0;
assign vcc = 1'b1;
// dropped: assign unknown = 1'bx;  (declared by Quartus, read by nothing)
assign devclrn = 1'b1;
assign devpor = 1'b1;
assign devoe = 1'b1;
assign btn_rise = \btn_rise~0_combout ;
assign btn_state = \state~q ;

tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) state (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\i38~0_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (\state~q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) state_d (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\state~q ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (\state_d~q ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2222222222222222), .shared_arith ("off")) \btn_rise~0  (.cin (gnd), .combout (\btn_rise~0_combout ), .dataa (\state~q ), .datab (\state_d~q ), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \cnt[3]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\cnt[3]~0_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (cnt[3]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \cnt[0]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\cnt[0]~1_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (cnt[0]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \cnt[1]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\cnt[1]~2_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (cnt[1]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \cnt[2]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\cnt[2]~3_combout ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (cnt[2]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hEAAAAAA8EAAAAAA8), .shared_arith ("off")) \i38~0  (.cin (gnd), .combout (\i38~0_combout ), .dataa (\state~q ), .datab (cnt[3]), .datac (cnt[0]), .datad (cnt[1]), .datae (cnt[2]), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \sync[1]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (sync[0]), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (sync[1]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hEAAAAAA8EAAAAAA8), .shared_arith ("off")) \cnt[3]~0  (.cin (gnd), .combout (\cnt[3]~0_combout ), .dataa (cnt[3]), .datab (cnt[0]), .datac (cnt[1]), .datad (cnt[2]), .datae (sync[1]), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hB3333332B3333332), .shared_arith ("off")) \cnt[0]~1  (.cin (gnd), .combout (\cnt[0]~1_combout ), .dataa (cnt[3]), .datab (cnt[0]), .datac (cnt[1]), .datad (cnt[2]), .datae (sync[1]), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hBC3CC3C2BC3CC3C2), .shared_arith ("off")) \cnt[1]~2  (.cin (gnd), .combout (\cnt[1]~2_combout ), .dataa (cnt[3]), .datab (cnt[0]), .datac (cnt[1]), .datad (cnt[2]), .datae (sync[1]), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hBFC0FC02BFC0FC02), .shared_arith ("off")) \cnt[2]~3  (.cin (gnd), .combout (\cnt[2]~3_combout ), .dataa (cnt[3]), .datab (cnt[0]), .datac (cnt[1]), .datad (cnt[2]), .datae (sync[1]), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \sync[0]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (btn_raw), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (sync[0]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));

endmodule
