"""Emit small Agilex-shaped ``.vo`` netlists for the recognition tests.

These are **synthesized shapes, not vendor exports**.  The real Quartus
exports in ``tools/hal_agilex/fixtures`` are what establishes that the
``tennm_lcell_comb`` / ``tennm_ff`` semantics in ``hal_agilex.primitives`` are
correct; this module only assembles cells *using* those same semantics, so it
can build the structures a crypto core is made of -- an S-box, a feedback shift
register, a rotation, a butterfly -- without a Quartus licence.

Two consequences follow and both are deliberate:

* a fixture built here proves something about the *recognizer*, never about the
  vendor's primitive behaviour, and the ``GROUND_TRUTH.md`` next to the
  generated files says so;
* the emitted text goes through the same ``hal_agilex.vo_netlist`` reader as a
  real export, so a fixture that the reader would refuse cannot be written
  here and quietly bypass it.

The committed ``.vo`` files are regenerated by ``python tools/hal_crypto
fixtures --check`` (or ``--write``), which is what keeps them from drifting
away from this generator.
"""

import hashlib
import json
import os

from hal_agilex import primitives

__all__ = [
    "Builder",
    "FIXTURES",
    "MANIFEST_NAME",
    "build_all",
    "manifest",
    "write_all",
    "check_all",
]

HEADER = """\
// Synthesized Agilex-shaped netlist, generated by tools/hal_crypto/fixtures/synth.py.
// This is NOT a Quartus export: it is assembled from the tennm_lcell_comb and
// tennm_ff semantics that tools/hal_agilex validated against real exports, so it
// exercises the hal_crypto recognizers and nothing else.
//
// PROGRAM "hal_crypto.fixtures.synth"
// VERSION "1.0.0"
//
// Device: Altera A3CW135BM16AE6S Package MBGA896
//

`timescale 1 ps/ 1 ps

"""


def _mask_from_table(table):
    """A 64-bit ``lut_mask`` for a table over the first ``log2(len)`` data pins.

    The pattern is replicated over the unused address bits, the way Quartus
    writes it, so the mask is readable next to a real export.
    """
    arity = (len(table) - 1).bit_length() if len(table) > 1 else 0
    mask = 0
    for address in range(64):
        if table[address & ((1 << arity) - 1) if arity else 0]:
            mask |= 1 << address
    return mask


class Builder(object):
    """Assemble one module out of ``tennm_lcell_comb`` and ``tennm_ff`` cells."""

    def __init__(self, name):
        self.name = name
        self.ports = []          # (direction, name, width)
        self.wires = []          # (name, width)
        self._wire_names = set()
        self.body = []
        self.assigns = []
        self._counter = 0

    # -- declarations -----------------------------------------------------

    def port(self, direction, name, width=1):
        self.ports.append((direction, name, width))
        return name

    def wire(self, name, width=1):
        if name not in self._wire_names:
            self.wires.append((name, width))
            self._wire_names.add(name)
        return name

    def temp(self, stem):
        self._counter += 1
        return self.wire("{}_{}".format(stem, self._counter))

    def assign(self, target, source):
        self.assigns.append((target, source))

    # -- cells ------------------------------------------------------------

    def lut(self, name, output, inputs, table):
        """One ALM cell in normal mode computing ``table`` over ``inputs``.

        ``inputs`` are net expressions, least significant address bit first, at
        most six of them; ``table`` has ``2**len(inputs)`` entries.
        """
        if len(inputs) > 6:
            raise ValueError("an ALM cell has six data inputs, got {}".format(len(inputs)))
        if len(table) != 1 << len(inputs):
            raise ValueError(
                "a {}-input cell needs {} table entries, got {}".format(
                    len(inputs), 1 << len(inputs), len(table)
                )
            )
        pins = list(inputs) + ["gnd"] * (6 - len(inputs))
        connections = [
            ".{}({})".format(pin, pins[position])
            for position, pin in enumerate(primitives.LCELL_DATA_PINS)
        ]
        connections += [".datag(gnd)", ".datah(gnd)", ".cin(gnd)", ".sharein(gnd)"]
        connections += [
            ".combout({})".format(output),
            ".sumout()",
            ".cout()",
            ".shareout()",
        ]
        self._cell(name, _mask_from_table(table), connections)
        return output

    def arithmetic(self, name, operand_a, operand_b, sum_net, carry_in, carry_out):
        """One full-adder bit slice: ``sumout = a ^ b ^ cin`` on the carry chain."""
        low = [((index >> 2) & 1) ^ ((index >> 3) & 1) for index in range(16)]
        high = [((index >> 2) & 1) & ((index >> 3) & 1) for index in range(16)]
        mask = 0
        for index in range(16):
            if low[index]:
                mask |= 1 << index
            if high[index]:
                mask |= 1 << (16 + index)
        connections = [
            ".dataa(gnd)",
            ".datab(gnd)",
            ".datac({})".format(operand_a),
            ".datad({})".format(operand_b),
            ".datae(gnd)",
            ".dataf(gnd)",
            ".datag(gnd)",
            ".datah(gnd)",
            ".cin({})".format(carry_in),
            ".sharein(gnd)",
            ".combout()",
            ".sumout({})".format(sum_net),
            ".cout({})".format(carry_out if carry_out else ""),
            ".shareout()",
        ]
        self._cell(name, mask, connections)

    def _cell(self, name, mask, connections):
        self.body.append(
            "tennm_lcell_comb #(\n"
            '  .extended_lut ("off"),\n'
            "  .lut_mask (64'h{:016X}),\n"
            '  .shared_arith ("off"))\n'
            "{} (\n\t{});\n".format(mask, name, ",\n\t".join(connections))
        )

    def register(self, name, data, output, clock="clk", enable="vcc", clear="vcc"):
        self.body.append(
            "tennm_ff #(\n"
            '  .is_wysiwyg ("true"),\n'
            '  .power_up ("dont_care"))\n'
            "{} (\n"
            "\t.clk({}),\n"
            "\t.d({}),\n"
            "\t.asdata(vcc),\n"
            "\t.clrn({}),\n"
            "\t.aload(gnd),\n"
            "\t.sclr(gnd),\n"
            "\t.sload(gnd),\n"
            "\t.ena({}),\n"
            "\t.sclr1(gnd),\n"
            "\t.devclrn(devclrn),\n"
            "\t.devpor(devpor),\n"
            "\t.q({}));\n".format(name, clock, data, clear, enable, output)
        )

    # -- composite helpers ------------------------------------------------

    def function(self, stem, output, inputs, evaluate):
        """A function of any arity, decomposed into six-input cells.

        ``evaluate`` takes a tuple of bits (aligned with ``inputs``) and returns
        the output bit.  Inputs beyond the sixth are peeled off two at a time
        and recombined with a 4:1 multiplexer cell, which is exactly how a
        seven-or-more-input function has to be built out of ALMs.
        """
        if len(inputs) <= 6:
            table = [
                evaluate(tuple((index >> position) & 1 for position in range(len(inputs))))
                for index in range(1 << len(inputs))
            ]
            return self.lut(stem, output, inputs, table)

        selects = inputs[-2:]
        rest = inputs[:-2]
        branches = []
        for choice in range(4):
            branch = self.wire("{}_b{}".format(output, choice))
            self.function(
                "{}_b{}".format(stem, choice),
                branch,
                rest,
                lambda bits, choice=choice: evaluate(
                    tuple(bits) + (choice & 1, (choice >> 1) & 1)
                ),
            )
            branches.append(branch)
        table = []
        for index in range(64):
            selector = (index >> 4) & 3
            table.append((index >> selector) & 1)
        return self.lut(stem + "_mux", output, branches + list(selects), table)

    def adder(self, stem, operands_a, operands_b, sums, carry_in="gnd", carry_out=None):
        """A ripple-carry chain over the two operand bit lists."""
        carry = carry_in
        for index, (a, b) in enumerate(zip(operands_a, operands_b)):
            last = index == len(operands_a) - 1
            following = (carry_out or "") if last else self.wire(
                "{}_c{}".format(stem, index)
            )
            self.arithmetic(
                "{}_{}".format(stem, index), a, b, sums[index], carry, following
            )
            carry = following
        return carry

    # -- output -----------------------------------------------------------

    def dumps(self):
        lines = [HEADER, "module {} (".format(self.name)]
        lines.append(
            ",\n".join("\t" + name for _, name, _ in self.ports) + ");"
        )
        for direction, name, width in self.ports:
            span = "" if width == 1 else "\t[{}:0]".format(width - 1)
            lines.append("{} {} {};".format(direction, span, name))
        lines.append("")
        lines.append("wire gnd;")
        lines.append("wire vcc;")
        lines.append("assign gnd = 1'b0;")
        lines.append("assign vcc = 1'b1;")
        lines.append("tri1 devclrn;")
        lines.append("tri1 devpor;")
        for name, width in self.wires:
            span = "" if width == 1 else " [{}:0]".format(width - 1)
            lines.append("wire{} {};".format(span, name))
        lines.append("")
        lines.extend(self.body)
        for target, source in self.assigns:
            lines.append("assign {} = {};".format(target, source))
        lines.append("")
        lines.append("endmodule")
        return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# the fixtures themselves
# ---------------------------------------------------------------------------


def _sbox_round(name, table, bits, nibbles=1, add_permutation=None):
    """A register bank feeding ``nibbles`` copies of an S-box, then back."""
    builder = Builder(name)
    builder.port("input", "clk")
    builder.port("input", "rst_n")
    width = bits * nibbles
    builder.port("output", "dout", width)
    builder.wire("state", width)
    builder.wire("sub", width)
    for nibble in range(nibbles):
        base = nibble * bits
        inputs = ["state[{}]".format(base + index) for index in range(bits)]
        for position in range(bits):
            builder.function(
                "sb{}_{}".format(nibble, position),
                "sub[{}]".format(base + position),
                inputs,
                lambda values, position=position: (
                    table[sum(bit << index for index, bit in enumerate(values))] >> position
                )
                & 1,
            )
    for index in range(width):
        source = index if add_permutation is None else add_permutation[index]
        builder.register(
            "state_{}".format(index),
            "sub[{}]".format(source),
            "state[{}]".format(index),
            clear="rst_n",
        )
        builder.assign("dout[{}]".format(index), "state[{}]".format(index))
    return builder


def _shift_chain(name, length, taps=None, nonlinear=False, galois_taps=None):
    builder = Builder(name)
    builder.port("input", "clk")
    builder.port("input", "rst_n")
    builder.port("input", "din")
    builder.port("output", "dout")
    builder.wire("state", length)

    if galois_taps is not None:
        builder.wire("fb", length)
        for index in range(length):
            if index == 0:
                builder.assign("fb[0]", "state[{}]".format(length - 1))
                data = "state[{}]".format(length - 1)
            elif index in galois_taps:
                builder.lut(
                    "gx_{}".format(index),
                    "fb[{}]".format(index),
                    ["state[{}]".format(index - 1), "state[{}]".format(length - 1)],
                    [0, 1, 1, 0],
                )
                data = "fb[{}]".format(index)
            else:
                data = "state[{}]".format(index - 1)
            builder.register(
                "state_{}".format(index), data, "state[{}]".format(index), clear="rst_n"
            )
        builder.assign("dout", "state[{}]".format(length - 1))
        return builder

    if taps is not None:
        inputs = ["state[{}]".format(tap) for tap in taps]
        if nonlinear:

            def evaluate(values):
                parity = 0
                for value in values[:-2]:
                    parity ^= value
                return parity ^ (values[-2] & values[-1])

        else:

            def evaluate(values):
                parity = 0
                for value in values:
                    parity ^= value
                return parity

        builder.wire("feedback")
        builder.function("fb", "feedback", inputs, evaluate)
        head = "feedback"
    else:
        head = "din"

    for index in range(length):
        data = head if index == 0 else "state[{}]".format(index - 1)
        builder.register(
            "state_{}".format(index), data, "state[{}]".format(index), clear="rst_n"
        )
    builder.assign("dout", "state[{}]".format(length - 1))
    return builder


def _loadable_lfsr(name, length=16, taps=(3, 12, 14, 15)):
    """The Fibonacci LFSR above, behind a parallel ``load ? seed : shift``.

    Every stage's next state is a multiplexer, so the plain "is this register
    driven by exactly one other register" test fails on all of them at once and
    the chain is invisible until ``load`` is held at 0.  That is what a vendor
    export of any keyed generator looks like -- see
    ``examples/agilex3_walkthroughs/13_trivium_stream`` -- and it is the shape
    :func:`hal_crypto.shiftreg.mode_candidates` exists for.
    """
    builder = Builder(name)
    builder.port("input", "clk")
    builder.port("input", "rst_n")
    builder.port("input", "load")
    builder.port("input", "seed", length)
    builder.port("output", "dout")
    builder.wire("state", length)
    builder.wire("nxt", length)
    builder.wire("feedback")

    def parity(values):
        result = 0
        for value in values:
            result ^= value
        return result

    builder.function(
        "fb", "feedback", ["state[{}]".format(tap) for tap in taps], parity
    )
    for index in range(length):
        shifted = "feedback" if index == 0 else "state[{}]".format(index - 1)
        data = "nxt[{}]".format(index)
        builder.lut(
            "mux_{}".format(index),
            data,
            ["load", "seed[{}]".format(index), shifted],
            # address bit 0 = load, 1 = seed, 2 = shifted
            [0, 0, 0, 1, 1, 0, 1, 1],
        )
        builder.register(
            "state_{}".format(index), data, "state[{}]".format(index), clear="rst_n"
        )
    builder.assign("dout", "state[{}]".format(length - 1))
    return builder


def _coupled_nlfsr(name, lengths=(8, 10)):
    """Two shift registers, each closed through the *other* one.

    Neither chain's feedback is a function of its own stages alone, so neither
    has a feedback polynomial or a period; together they are one 18-bit
    nonlinear generator.  This is the Trivium/Grain shape at toy size, and it is
    the minimum case for the ``coupled`` reporting in
    :func:`hal_crypto.shiftreg.find_shift_structures`.
    """
    builder = Builder(name)
    builder.port("input", "clk")
    builder.port("input", "rst_n")
    builder.port("output", "dout")
    first, second = lengths
    builder.wire("a", first)
    builder.wire("b", second)
    builder.wire("head_a")
    builder.wire("head_b")

    def feedback(values):
        # own tap ^ foreign tap ^ (two adjacent foreign stages ANDed)
        return values[0] ^ values[1] ^ (values[2] & values[3])

    builder.function(
        "fa",
        "head_a",
        [
            "a[{}]".format(first - 3),
            "b[{}]".format(second - 1),
            "b[{}]".format(second - 3),
            "b[{}]".format(second - 2),
        ],
        feedback,
    )
    builder.function(
        "fb",
        "head_b",
        [
            "b[{}]".format(second - 4),
            "a[{}]".format(first - 1),
            "a[{}]".format(first - 3),
            "a[{}]".format(first - 2),
        ],
        feedback,
    )
    for index in range(first):
        data = "head_a" if index == 0 else "a[{}]".format(index - 1)
        builder.register("a_{}".format(index), data, "a[{}]".format(index), clear="rst_n")
    for index in range(second):
        data = "head_b" if index == 0 else "b[{}]".format(index - 1)
        builder.register("b_{}".format(index), data, "b[{}]".format(index), clear="rst_n")
    builder.assign("dout", "a[{}]".format(first - 1))
    return builder


def _arx_round(name, width=8, rotation=3):
    """One ARX round: add two registered words, rotate, XOR, register back."""
    builder = Builder(name)
    builder.port("input", "clk")
    builder.port("input", "rst_n")
    builder.port("input", "load", width)
    builder.port("output", "dout", width)
    builder.wire("x", width)
    builder.wire("y", width)
    builder.wire("sum", width)
    builder.wire("rot", width)
    builder.wire("xored", width)

    builder.adder(
        "add",
        ["x[{}]".format(index) for index in range(width)],
        ["y[{}]".format(index) for index in range(width)],
        ["sum[{}]".format(index) for index in range(width)],
    )
    for index in range(width):
        builder.assign("rot[{}]".format(index), "y[{}]".format((index - rotation) % width))
        builder.lut(
            "xor_{}".format(index),
            "xored[{}]".format(index),
            ["sum[{}]".format(index), "rot[{}]".format(index)],
            [0, 1, 1, 0],
        )
        builder.register(
            "x_{}".format(index), "sum[{}]".format(index), "x[{}]".format(index),
            clear="rst_n",
        )
        builder.register(
            "y_{}".format(index), "xored[{}]".format(index), "y[{}]".format(index),
            clear="rst_n",
        )
        builder.assign("dout[{}]".format(index), "x[{}]".format(index))
    return builder


def _counter(name, width=8):
    """An adder-only accumulator: the ARX negative control.

    The second operand is a port rather than the constant 1, so the carry chain
    really is a two-operand adder and the fixture tests "an adder on its own is
    not ARX" instead of "there is no adder here".
    """
    builder = Builder(name)
    builder.port("input", "clk")
    builder.port("input", "rst_n")
    builder.port("input", "step", width)
    builder.port("output", "dout", width)
    builder.wire("count", width)
    builder.wire("sum", width)
    builder.adder(
        "add",
        ["count[{}]".format(index) for index in range(width)],
        ["step[{}]".format(index) for index in range(width)],
        ["sum[{}]".format(index) for index in range(width)],
    )
    for index in range(width):
        builder.register(
            "count_{}".format(index), "sum[{}]".format(index), "count[{}]".format(index),
            clear="rst_n",
        )
        builder.assign("dout[{}]".format(index), "count[{}]".format(index))
    return builder


def _butterfly(name, width=4):
    """A single NTT-style butterfly: ``a+b`` and ``a-b`` over the same operands."""
    builder = Builder(name)
    builder.port("input", "clk")
    builder.port("input", "rst_n")
    builder.port("output", "up", width + 1)
    builder.port("output", "down", width + 1)
    builder.wire("a", width)
    builder.wire("b", width)
    builder.wire("nb", width)
    builder.wire("sum", width)
    builder.wire("diff", width)
    builder.wire("sum_r", width)
    builder.wire("diff_r", width)

    for index in range(width):
        builder.lut("inv_{}".format(index), "nb[{}]".format(index),
                    ["b[{}]".format(index)], [1, 0])
    builder.adder(
        "add",
        ["a[{}]".format(index) for index in range(width)],
        ["b[{}]".format(index) for index in range(width)],
        ["sum[{}]".format(index) for index in range(width)],
    )
    builder.adder(
        "sub",
        ["a[{}]".format(index) for index in range(width)],
        ["nb[{}]".format(index) for index in range(width)],
        ["diff[{}]".format(index) for index in range(width)],
        carry_in="vcc",
    )
    for index in range(width):
        builder.register("a_{}".format(index), "sum[{}]".format(index),
                         "a[{}]".format(index), clear="rst_n")
        builder.register("b_{}".format(index), "diff[{}]".format(index),
                         "b[{}]".format(index), clear="rst_n")
        builder.register("sr_{}".format(index), "sum[{}]".format(index),
                         "sum_r[{}]".format(index), clear="rst_n")
        builder.register("dr_{}".format(index), "diff[{}]".format(index),
                         "diff_r[{}]".format(index), clear="rst_n")
        builder.assign("up[{}]".format(index), "sum_r[{}]".format(index))
        builder.assign("down[{}]".format(index), "diff_r[{}]".format(index))
    builder.assign("up[{}]".format(width), "gnd")
    builder.assign("down[{}]".format(width), "gnd")
    return builder


def _ntt_stage(name, bits=13, modulus=3329):
    """A butterfly whose sum is reduced modulo *q* by a conditional subtract.

    ``sum - q`` is built as ``sum + (2**bits - q)``, which is how a hardware
    reduction is written and which is why the modulus has to be read back out
    of the constant as ``2**w - k``.
    """
    builder = Builder(name)
    builder.port("input", "clk")
    builder.port("input", "rst_n")
    builder.port("output", "dout", bits)
    for vector in ("a", "b", "nb", "sum", "diff", "red", "out"):
        builder.wire(vector, bits)
    builder.wire("ge")

    complement = (1 << bits) - modulus
    for index in range(bits):
        builder.lut("inv_{}".format(index), "nb[{}]".format(index),
                    ["b[{}]".format(index)], [1, 0])
    builder.adder(
        "add",
        ["a[{}]".format(index) for index in range(bits)],
        ["b[{}]".format(index) for index in range(bits)],
        ["sum[{}]".format(index) for index in range(bits)],
    )
    builder.adder(
        "sub",
        ["a[{}]".format(index) for index in range(bits)],
        ["nb[{}]".format(index) for index in range(bits)],
        ["diff[{}]".format(index) for index in range(bits)],
        carry_in="vcc",
    )
    builder.adder(
        "mod",
        ["sum[{}]".format(index) for index in range(bits)],
        ["vcc" if (complement >> index) & 1 else "gnd" for index in range(bits)],
        ["red[{}]".format(index) for index in range(bits)],
        carry_out="ge",
    )
    for index in range(bits):
        builder.lut(
            "mux_{}".format(index),
            "out[{}]".format(index),
            ["sum[{}]".format(index), "red[{}]".format(index), "ge"],
            [0, 1, 0, 1, 0, 0, 1, 1],
        )
        builder.register("a_{}".format(index), "out[{}]".format(index),
                         "a[{}]".format(index), clear="rst_n")
        builder.register("b_{}".format(index), "diff[{}]".format(index),
                         "b[{}]".format(index), clear="rst_n")
        builder.assign("dout[{}]".format(index), "a[{}]".format(index))
    return builder


def _rotation_layer(name, width=16, rotation=5):
    """Two register banks joined by nothing but a cyclic rewiring."""
    builder = Builder(name)
    builder.port("input", "clk")
    builder.port("input", "rst_n")
    builder.port("input", "din", width)
    builder.port("output", "dout", width)
    builder.wire("front", width)
    builder.wire("back", width)
    for index in range(width):
        builder.register("front_{}".format(index), "din[{}]".format(index),
                         "front[{}]".format(index), clear="rst_n")
        builder.register(
            "back_{}".format(index),
            "front[{}]".format((index - rotation) % width),
            "back[{}]".format(index),
            clear="rst_n",
        )
        builder.assign("dout[{}]".format(index), "back[{}]".format(index))
    return builder


def _present_table():
    from ..known import SBOXES

    return SBOXES["present"]["sbox"].table


def _control_bijection():
    """A fixed 4-bit bijection that is in no published library.

    The S-box negative control.  It is hard-coded rather than drawn at random
    so it cannot drift, and ``test_hal_crypto`` checks it against every library
    entry at every match tier -- if a future library addition collides with it,
    that test fails and the control gets replaced deliberately.
    """
    return (0x0, 0x3, 0x5, 0x8, 0xB, 0xE, 0x1, 0x6, 0xD, 0x2, 0xF, 0x4, 0x9, 0xC, 0x7, 0xA)


#: Fixture name -> what it is, how to build it, and what ``identify`` must say
#: about it.  The expected verdicts live here rather than in the test file so
#: that a fixture and the expectation for it cannot be added separately.
FIXTURES = {
    "present_sbox_layer": {
        "build": lambda: _sbox_round("present_sbox_layer", _present_table(), 4, nibbles=2),
        "description": "two PRESENT S-boxes between register banks",
        "role": "positive control for the S-box pass",
        "family": "spn",
        "style": "classical-style",
    },
    "unknown_sbox_layer": {
        "build": lambda: _sbox_round(
            "unknown_sbox_layer", _control_bijection(), 4, nibbles=2
        ),
        "description": "the same shape with a 4-bit bijection that is in no library",
        "role": "negative control for S-box *matching*: extracted, never matched",
        "family": "spn",
        "style": "classical-style",
    },
    "lfsr16_fibonacci": {
        "build": lambda: _shift_chain("lfsr16_fibonacci", 16, taps=[3, 12, 14, 15]),
        "description": "16-stage Fibonacci LFSR, x^16 + x^15 + x^13 + x^4 + 1",
        "role": "positive control for the LFSR pass",
        "family": "lfsr-stream",
        "style": "classical-style",
    },
    "lfsr16_galois": {
        "build": lambda: _shift_chain("lfsr16_galois", 16, galois_taps=[1, 3, 12]),
        "description": "16-stage Galois LFSR with three injection points",
        "role": "positive control for Galois-versus-Fibonacci",
        "family": "lfsr-stream",
        "style": "classical-style",
    },
    "nlfsr16": {
        "build": lambda: _shift_chain("nlfsr16", 16, taps=[3, 12, 14, 15], nonlinear=True),
        "description": "16-stage NLFSR: the same taps with an AND term in the feedback",
        "role": "negative control for *linear* feedback: no polynomial exists",
        "family": "lfsr-stream",
        "style": "classical-style",
    },
    "lfsr16_loadable": {
        "build": lambda: _loadable_lfsr("lfsr16_loadable", 16, (3, 12, 14, 15)),
        "description": "the same LFSR behind a parallel `load ? seed : shift`",
        "role": (
            "positive control for the operating-mode search: every shift link is a "
            "multiplexer until `load` is held at 0"
        ),
        "family": "lfsr-stream",
        "style": "classical-style",
    },
    "coupled_nlfsr": {
        "build": lambda: _coupled_nlfsr("coupled_nlfsr", (8, 10)),
        "description": "two chains of 8 and 10 stages, each closed through the other",
        "role": (
            "positive control for coupled (Trivium/Grain-style) registers: neither "
            "chain has a feedback polynomial of its own"
        ),
        "family": "lfsr-stream",
        "style": "classical-style",
    },
    "shift16_plain": {
        "build": lambda: _shift_chain("shift16_plain", 16),
        "description": "16-stage shift register with no feedback at all",
        "role": "negative control for the LFSR pass",
        "family": "none-detected",
        "style": "undetermined",
    },
    "arx_round8": {
        "build": lambda: _arx_round("arx_round8", width=8, rotation=3),
        "description": "one ARX round: 8-bit add, rotate by 3, XOR, register",
        "role": "positive control for the ARX pass",
        "family": "arx",
        "style": "classical-style",
    },
    "counter8": {
        "build": lambda: _counter("counter8", width=8),
        "description": "8-bit accumulator: adders without rotation or XOR layers",
        "role": "negative control for the ARX pass -- an adder alone is not ARX",
        "family": "none-detected",
        "style": "undetermined",
    },
    "butterfly4": {
        "build": lambda: _butterfly("butterfly4", width=4),
        "description": "4-bit butterfly: a+b and a-b over the same operands",
        "role": "positive control for butterfly detection, negative for the modulus",
        "family": "none-detected",
        "style": "undetermined",
    },
    "ntt_stage13": {
        "build": lambda: _ntt_stage("ntt_stage13", bits=13, modulus=3329),
        "description": "a butterfly with a conditional subtract of q = 3329",
        "role": "positive control for the NTT pass and the PQC-style verdict",
        "family": "lattice-ntt",
        "style": "pqc-style",
    },
    "rotate16": {
        "build": lambda: _rotation_layer("rotate16", width=16, rotation=5),
        "description": "two 16-bit register banks joined by a rotation of 5",
        "role": "positive control for the permutation pass, negative for ARX",
        "family": "none-detected",
        "style": "undetermined",
    },
}

#: The manifest that ships next to the generated netlists.
MANIFEST_NAME = "MANIFEST.json"


def build_all():
    """``{name: verilog text}`` for every fixture."""
    return {name: entry["build"]().dumps() for name, entry in sorted(FIXTURES.items())}


def manifest(texts=None):
    """The manifest contents, derived from the fixture table and the texts."""
    texts = texts or build_all()
    return {
        "generator": "tools/hal_crypto/fixtures/synth.py",
        "kind": "synthesized shapes, not vendor exports",
        "family": "Agilex 3",
        "device": "A3CW135BM16AE6S",
        "provenance": (
            "Assembled from the tennm_lcell_comb and tennm_ff semantics in "
            "hal_agilex.primitives, which were validated against real Quartus "
            "exports in tools/hal_agilex/fixtures. Nothing here came out of "
            "Quartus, so nothing here is evidence about vendor primitive "
            "behaviour -- only about the hal_crypto recognizers."
        ),
        "regenerate": ["python tools/hal_crypto fixtures --write"],
        "verify": ["python tools/hal_crypto fixtures --check"],
        "files": {
            "{}.vo".format(name): {
                "description": FIXTURES[name]["description"],
                "role": FIXTURES[name]["role"],
                "expected_family": FIXTURES[name]["family"],
                "expected_style": FIXTURES[name]["style"],
                "sha256": hashlib.sha256(text.encode("utf-8")).hexdigest(),
                "size_bytes": len(text.encode("utf-8")),
            }
            for name, text in sorted(texts.items())
        },
    }


def _manifest_text(texts=None):
    return json.dumps(manifest(texts), indent=2, sort_keys=True) + "\n"


def _path(directory, name):
    return os.path.join(directory, "{}.vo".format(name))


def _expected(directory):
    texts = build_all()
    expected = {_path(directory, name): text for name, text in texts.items()}
    expected[os.path.join(directory, MANIFEST_NAME)] = _manifest_text(texts)
    return expected


def write_all(directory):
    written = []
    for path, text in sorted(_expected(directory).items()):
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        written.append(path)
    return written


def check_all(directory):
    """Paths whose committed content differs from what this module generates."""
    stale = []
    for path, text in sorted(_expected(directory).items()):
        if not os.path.isfile(path):
            stale.append(path)
            continue
        with open(path, "r", encoding="utf-8") as handle:
            if handle.read() != text:
                stale.append(path)
    return stale
