"""Unit tests for the clock-step page generator. No HAL, no browser, no Graphviz.

Run from the repository root::

    python -m unittest discover -s tools/hal_viz -t tools -p "test_*.py"

The generator's whole job is a join between two committed artifacts, so what
these tests assert is the join: which drawn node and which drawn arrow ends up
carrying which net's value, what happens to the ones that cannot be resolved,
and that the emitted document really is one self-contained file.
"""

import json
import os
import re
import sys
import unittest

if __package__ in (None, ""):  # pragma: no cover - direct execution
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from hal_viz.clockstep import (  # noqa: E402
    BLINDED_NOTE,
    ClockStepError,
    bind_trace,
    build_page,
    load_name_map,
    parse_dag_dot,
)

# A hand-written stand-in for what `hal_viz dag` emits: two flip-flops, one
# combinational cell, a constant tie-off, and the decoration nodes a reader
# needs but a value never lands on.
DOT = '''\
// generated by hal_viz 1.0.0 (dag)
// 2 level(s), 2 edge(s) cut at a register
digraph "demo - whole netlist - levelled graph" {
  graph [rankdir="LR"];

  subgraph "level_0" {
    graph [rank="same"];

    "lvl_0" [shape="plaintext", label="level 0"];
    "tie0_1" [tooltip="constant 0 from global_gnd [HAL_GND], net '0'", label="0"];
    "tie1_2" [tooltip="constant 1 from global_vcc [HAL_VCC], net '1'", label="1"];
    "g1" [shape="box", label="q0\\n[tennm_ff]\\nid 1"];
    "g2" [shape="box", label="q1\\n[tennm_ff]\\nid 2"];
  }

  subgraph "level_1" {
    graph [rank="same"];

    "lvl_1" [shape="plaintext", label="level 1"];
    "g3" [label="xor0\\n[tennm_lcell_comb]\\nid 3"];
  }

  subgraph "cluster_legend" {
    graph [label="legend"];

    "legend_comb" [label="combinational\\ngate"];
    "legend_net_a" [shape="point", label=""];
    "legend_net_b" [shape="point", label=""];

    "legend_net_a" -> "legend_net_b" [label="net"];
  }

  "lvl_0" -> "lvl_1" [style="invis"];
  "g1" -> "g3";
  "g2" -> "g3";
  "g3" -> "g1" [style="dashed", color="#c0392b"];
  "tie0_1" -> "g1" [color="#8a8a8a"];
  "tie1_2" -> "g2" [color="#8a8a8a"];
}
'''

# nets: 0 q0, 1 q1, 2 xor, 3 an undriven net
TRACE = {
    "schema": "hal_agilex/trace/1",
    "design": "demo",
    "stimulus": {
        "seed": 4242,
        "driveable_inputs": [["rst_n", 1], ["addend", 8]],
        "ignored_inputs": ["clk"],
        "held_inputs": {"addend": 3},
        "clear_input": "rst_n",
        "clear_cycles": [0],
    },
    "window": {"start": 0, "cycles": 3, "end": 2},
    "nets": ["q0~q", "q1~q", "xor0_combout", "dangling"],
    "gates": {
        "q0": {
            "type": "tennm_ff",
            "sequential": True,
            "inputs": {"d": 2},
            "outputs": {"q": 0},
            "output": 0,
            "drives_ports": ["out"],
        },
        "q1": {
            "type": "tennm_ff",
            "sequential": True,
            "inputs": {"d": 2},
            "outputs": {"q": 1},
            "output": 1,
        },
        "xor0": {
            "type": "tennm_lcell_comb",
            "sequential": False,
            "inputs": {"dataa": 0, "datab": 1},
            "outputs": {"combout": 2},
            "output": 2,
        },
    },
    "ports": {"inputs": {"rst_n": []}, "outputs": {"out": [0]}},
    "frames": [
        {"cycle": 0, "inputs": {"rst_n": 0}, "outputs": {"out": 0}, "values": "000x"},
        {"cycle": 1, "inputs": {"rst_n": 1}, "outputs": {"out": 0}, "values": "011x"},
        {"cycle": 2, "inputs": {"rst_n": 1}, "outputs": {"out": 1}, "values": "110x"},
    ],
}

SVG = (
    '<svg width="100pt" height="50pt" viewBox="0.00 0.00 100.00 50.00" '
    'xmlns="http://www.w3.org/2000/svg">\n'
    '<g id="graph0" class="graph"><title>demo</title>\n'
    '<g id="node1" class="node"><title>g1</title>'
    '<polygon fill="#dbe9f6" stroke="#2a5d8f" points="0,0 1,1"/></g>\n'
    '<g id="edge1" class="edge"><title>g1&#45;&gt;g3</title>'
    '<path fill="none" stroke="#777777" d="M0,0"/></g>\n'
    "</g></svg>\n"
)


def _payload(page):
    """The JSON the page embeds for its own script."""
    match = re.search(
        r'<script id="clock-step-data" type="application/json">(.*?)</script>',
        page,
        re.S,
    )
    assert match, "the page embeds no clock-step data"
    return json.loads(match.group(1))


class ParseDotTestCase(unittest.TestCase):
    def setUp(self):
        self.nodes, self.edges = parse_dag_dot(DOT)

    def test_gate_nodes_carry_their_name_and_type(self):
        self.assertEqual(self.nodes["g1"], {"name": "q0", "type": "tennm_ff", "tie": None})
        self.assertEqual(
            self.nodes["g3"], {"name": "xor0", "type": "tennm_lcell_comb", "tie": None}
        )

    def test_tie_offs_are_recognised_by_id_not_by_label(self):
        self.assertEqual(self.nodes["tie0_1"]["tie"], 0)
        self.assertEqual(self.nodes["tie1_2"]["tie"], 1)
        self.assertIsNone(self.nodes["tie0_1"]["name"])

    def test_legend_and_level_markers_are_not_part_of_the_circuit(self):
        for node_id in ("lvl_0", "lvl_1", "legend_comb", "legend_net_a"):
            self.assertNotIn(node_id, self.nodes)
        self.assertNotIn(("legend_net_a", "legend_net_b"), self.edges)
        self.assertNotIn(("lvl_0", "lvl_1"), self.edges)

    def test_edges_are_kept_in_order(self):
        self.assertEqual(
            self.edges,
            [("g1", "g3"), ("g2", "g3"), ("g3", "g1"), ("tie0_1", "g1"), ("tie1_2", "g2")],
        )

    def test_a_drawing_with_no_gates_is_refused(self):
        with self.assertRaises(ClockStepError):
            parse_dag_dot('digraph "x" {\n  "lvl_0" [label="level 0"];\n}\n')


class NameMapTestCase(unittest.TestCase):
    def _write(self, tmpdir, payload):
        path = os.path.join(tmpdir, "map.json")
        with open(path, "w", encoding="utf-8") as handle:
            json.dump(payload, handle)
        return path

    def test_flat_and_wrapped_maps_are_both_accepted(self):
        import tempfile

        with tempfile.TemporaryDirectory() as tmpdir:
            flat = load_name_map(self._write(tmpdir, {"q0": "g1"}))
            self.assertEqual(flat["q0"], "g1")
            wrapped = load_name_map(
                self._write(tmpdir, {"nets": {"a": "n0"}, "gates": {"q0": "g1"}})
            )
            self.assertEqual(wrapped["q0"], "g1")

    def test_a_bus_split_key_also_answers_to_the_bracket_spelling(self):
        import tempfile

        with tempfile.TemporaryDirectory() as tmpdir:
            mapping = load_name_map(self._write(tmpdir, {"gates": {"tick$b3": "g7"}}))
            self.assertEqual(mapping["tick$b3"], "g7")
            self.assertEqual(mapping["tick[3]"], "g7")

    def test_an_explicit_bracket_key_wins_over_the_alias(self):
        import tempfile

        with tempfile.TemporaryDirectory() as tmpdir:
            mapping = load_name_map(
                self._write(tmpdir, {"tick$b3": "g7", "tick[3]": "g9"})
            )
            self.assertEqual(mapping["tick[3]"], "g9")

    def test_a_map_that_is_not_name_to_name_is_refused(self):
        import tempfile

        with tempfile.TemporaryDirectory() as tmpdir:
            with self.assertRaises(ClockStepError):
                load_name_map(self._write(tmpdir, {"q0": [1, 2]}))


class BindTestCase(unittest.TestCase):
    def setUp(self):
        self.nodes, self.edges = parse_dag_dot(DOT)
        self.binding, self.report = bind_trace(self.nodes, self.edges, TRACE)

    def test_every_gate_gets_the_net_its_output_drives(self):
        self.assertEqual(self.binding["nodes"]["g1"]["net"], 0)
        self.assertEqual(self.binding["nodes"]["g2"]["net"], 1)
        self.assertEqual(self.binding["nodes"]["g3"]["net"], 2)
        self.assertEqual(self.report["nodes_bound"], 3)

    def test_flip_flops_and_output_drivers_are_flagged_for_a_label(self):
        self.assertTrue(self.binding["nodes"]["g1"]["seq"])
        self.assertEqual(self.binding["nodes"]["g1"]["ports"], ["out"])
        self.assertNotIn("seq", self.binding["nodes"]["g3"])

    def test_tie_offs_carry_their_constant_not_a_net(self):
        self.assertEqual(self.binding["nodes"]["tie0_1"], {"const": 0})
        self.assertEqual(self.binding["nodes"]["tie1_2"], {"const": 1})
        self.assertEqual(self.report["ties"], 2)

    def test_an_arrow_gets_the_one_net_its_endpoints_share(self):
        self.assertEqual(self.binding["edges"]["g1->g3"], {"net": 0})
        self.assertEqual(self.binding["edges"]["g2->g3"], {"net": 1})
        self.assertEqual(self.binding["edges"]["g3->g1"], {"net": 2})
        self.assertEqual(self.binding["edges"]["tie0_1->g1"], {"const": 0})
        self.assertEqual(self.report["edges_bound"], 5)

    def test_a_gate_the_trace_does_not_know_is_reported_not_guessed(self):
        nodes = dict(self.nodes)
        nodes["g9"] = {"name": "mystery", "type": "tennm_ff", "tie": None}
        binding, report = bind_trace(nodes, self.edges, TRACE)
        self.assertEqual(binding["nodes"]["g9"], {"unknown": True})
        self.assertEqual(report["nodes_unknown"], ["mystery"])

    def test_two_nets_between_the_same_pair_are_ambiguous_not_a_coin_flip(self):
        trace = json.loads(json.dumps(TRACE))
        # q0 now drives both nets that xor0 reads, so which net the single
        # drawn arrow stands for cannot be recovered from the drawing.
        trace["gates"]["q0"]["outputs"] = {"q": 0, "q2": 1}
        binding, report = bind_trace(self.nodes, self.edges, trace)
        self.assertEqual(binding["edges"]["g1->g3"], {"unknown": True})
        self.assertEqual(report["edges_ambiguous"], 1)

    def test_the_legend_is_not_in_the_binding_at_all(self):
        # Absent, not unknown: the legend's own sample arrows are drawn in the
        # same SVG, and painting a value onto the key would break the key.
        for key in self.binding["nodes"]:
            self.assertFalse(key.startswith(("legend", "lvl_")))
        for key in self.binding["edges"]:
            self.assertNotIn("legend", key)
            self.assertNotIn("lvl_", key)

    def test_a_name_map_translates_the_drawing_back_to_the_trace(self):
        nodes = {
            "g1": {"name": "u5", "type": "tennm_ff", "tie": None},
            "g3": {"name": "u9", "type": "tennm_lcell_comb", "tie": None},
        }
        binding, report = bind_trace(
            nodes, [("g1", "g3")], TRACE, name_map={"q0": "u5", "xor0": "u9"}
        )
        self.assertEqual(binding["nodes"]["g1"]["gate"], "q0")
        self.assertEqual(binding["edges"]["g1->g3"], {"net": 0})
        self.assertEqual(report["nodes_bound"], 2)

    def test_a_trace_with_no_gates_is_refused(self):
        with self.assertRaises(ClockStepError):
            bind_trace(self.nodes, self.edges, {"gates": {}})


class PageTestCase(unittest.TestCase):
    def setUp(self):
        nodes, edges = parse_dag_dot(DOT)
        self.binding, self.report = bind_trace(nodes, edges, TRACE)
        self.page = build_page(
            SVG, TRACE, self.binding, self.report, "demo - clock-step DAG"
        )

    def test_it_is_one_html_document_with_the_svg_inlined(self):
        self.assertTrue(self.page.startswith("<!doctype html>"))
        self.assertIn("<title>demo - clock-step DAG</title>", self.page)
        self.assertIn('<g id="node1" class="node"><title>g1</title>', self.page)
        self.assertTrue(self.page.endswith("</html>\n"))

    def test_nothing_is_fetched_from_outside_the_file(self):
        without_namespace = self.page.replace("http://www.w3.org", "")
        self.assertNotIn("http://", without_namespace)
        self.assertNotIn("https://", without_namespace)
        self.assertNotIn("<img", self.page)
        self.assertNotIn("<link", self.page)
        self.assertNotIn("<script src", self.page)
        self.assertNotIn('type="module"', self.page)

    def test_the_controls_the_reader_needs_are_all_there(self):
        for element_id in ("prev", "next", "play", "scrub", "counter", "frame-state"):
            self.assertIn('id="{}"'.format(element_id), self.page)
        self.assertIn('type="range"', self.page)
        self.assertIn('max="2"', self.page)
        self.assertIn("ArrowLeft", self.page)
        self.assertIn("ArrowRight", self.page)

    def test_the_embedded_data_is_the_trace_and_the_binding(self):
        payload = _payload(self.page)
        self.assertEqual(payload["binding"], self.binding)
        self.assertEqual([frame["cycle"] for frame in payload["frames"]], [0, 1, 2])
        self.assertEqual(payload["frames"][2]["values"], "110x")
        self.assertEqual(payload["frames"][2]["outputs"], {"out": 1})

    def test_the_embedded_data_cannot_close_the_script_element(self):
        trace = json.loads(json.dumps(TRACE))
        trace["frames"][0]["inputs"] = {"</script><b>x": 1}
        page = build_page(SVG, trace, self.binding, self.report, "t")
        self.assertNotIn("</script><b>", page)
        self.assertIn("</script><b>x", _payload(page)["frames"][0]["inputs"])

    def test_the_page_states_its_bound_and_its_stimulus(self):
        self.assertIn("cycles 0-2 of one run", self.page)
        self.assertIn("random.Random(4242)", self.page)
        self.assertIn("addend held at 3", self.page)
        self.assertIn("rst_n asserted before the first cycle", self.page)
        self.assertIn("clk", self.page)
        self.assertIn("never as 0", self.page)

    def test_the_legend_keeps_the_drawings_own_vocabulary(self):
        self.assertIn("the net carries 1 in this cycle", self.page)
        self.assertIn("unknown", self.page)
        self.assertIn("dashed arrow = edge cut at a register", self.page)
        self.assertIn("constant tie-off", self.page)

    def test_unresolved_gates_are_announced_on_the_page(self):
        nodes, edges = parse_dag_dot(DOT)
        nodes["g9"] = {"name": "mystery", "type": "tennm_ff", "tie": None}
        binding, report = bind_trace(nodes, edges, TRACE)
        page = build_page(SVG, TRACE, binding, report, "t")
        self.assertIn("are not in the trace and stay marked unknown", page)
        self.assertIn("mystery", page)

    def test_a_blinded_drawing_says_so_before_it_spoils_the_exercise(self):
        page = build_page(SVG, TRACE, self.binding, self.report, "t", blinded=True)
        self.assertIn("Spoiler warning", page)
        self.assertIn(BLINDED_NOTE.split(".")[0], page)
        self.assertNotIn("Spoiler warning", self.page)

    def test_a_trace_with_no_frames_is_refused(self):
        trace = dict(TRACE, frames=[])
        with self.assertRaises(ClockStepError):
            build_page(SVG, trace, self.binding, self.report, "t")


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
