"""Standalone unit tests for ``hal_viz report``.

The report generator is pure standard library and needs neither a built HAL nor
Graphviz, so everything below runs on any machine:

    python tools/hal_viz/test_hal_viz_report.py
    # or
    python -m unittest discover -s tools/hal_viz -t tools -p "test_*.py"

What is covered is what the report is trusted for: that untrusted, netlist
derived strings can never break out of the HTML, that all nine findings
statuses render and stay distinguishable, that a missing artifact, a truncated
list, a bounded claim, a coverage gap and an unknown result are all visible
markers rather than silence, and that the page opens offline (no external
request, no script).
"""

import json
import os
import re
import sys
import tempfile
import unittest

if __package__ in (None, ""):
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from hal_viz import cli, report  # noqa: E402

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
EXAMPLES_DIR = os.path.join(REPO_ROOT, "tools", "hal_findings", "examples")

try:
    from hal_findings import model as findings_model
    from hal_findings import validate as findings_validate
except ImportError:  # pragma: no cover - hal_findings sits next to hal_viz
    findings_model = None
    findings_validate = None


# ---------------------------------------------------------------------------
# fixtures
# ---------------------------------------------------------------------------

HOSTILE_NAME = "gate<script>alert('x')</script>&\"'"

SVG_WITH_ACTIVE_CONTENT = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/svg11.dtd">
<!-- generated by graphviz -->
<svg xmlns="http://www.w3.org/2000/svg" width="100pt" height="50pt" viewBox="0 0 100 50">
<script>window.alert('pwned')</script>
<g onload="alert('pwned')"><title>g42</title>
<a xlink:href="https://example.invalid/tracker.png"><text x="1" y="2">state_reg_0</text></a>
<a xlink:href="#local">local</a>
<path d="M0,0 L10,10"/></g>
</svg>
"""

_ARTIFACT = {
    "artifact_id": "uart",
    "kind": "netlist",
    "path": "uart/uart.hal",
    "sha256": "a" * 64,
    "design_name": "test_ext_uart",
    "gate_count": 407,
}


def _method(kind="formal", bounded=False, name="test method"):
    return {"name": name, "kind": kind, "bounded": bounded}


def _scope(gates=None, description="the region this finding is about"):
    scope = {"artifact_ids": ["uart"], "description": description}
    if gates:
        scope["gates"] = gates
    return scope


def _gate(gate_id=1, name="state_reg_0", gate_type="FFR"):
    return {"artifact_id": "uart", "id": gate_id, "name": name, "type": gate_type}


def finding_for(status, **overrides):
    """A minimal, schema-valid finding for each of the nine statuses."""
    base = {
        "id": "test/{}".format(status.replace("_", "-")),
        "title": "finding with status {}".format(status),
        "summary": "summary of the {} finding".format(status),
        "status": status,
        "method": _method(),
        "scope": _scope([_gate()]),
    }
    if status == "proven_under_assumptions":
        base["bounds"] = {"unbounded": True}
        base["assumptions"] = [
            {
                "id": "clock.single",
                "description": "the design has a single clock domain",
                "kind": "structural",
                "discharged": False,
            }
        ]
    elif status == "proven_bounded":
        base["bounds"] = {"unbounded": False, "cycle_bound": 8}
        base["method"] = _method("bounded_formal", True)
        base["assumptions"] = []
    elif status == "counterexample":
        base["bounds"] = {"unbounded": True}
        base["counterexample"] = {
            "description": "the outputs differ",
            "witness": [{"signal": "rx_data", "value": "0x41"}],
        }
    elif status == "bounded_counterexample":
        base["bounds"] = {"unbounded": False, "cycle_bound": 12}
        base["method"] = _method("bounded_formal", True)
        base["counterexample"] = {
            "description": "the outputs differ within 5 cycles",
            "cycle_bound": 5,
            "witness": [{"signal": "rx_data", "cycle": 5, "value": "0x41"}],
        }
    elif status == "heuristic":
        base["method"] = _method("heuristic", False, "dataflow analysis (DANA)")
        base["confidence"] = 0.8
    elif status == "timeout":
        base["limits"] = {"timeout_s": 60, "hit": True}
    elif status == "error":
        base["error"] = {"kind": "plugin_error", "message": "the plugin returned None"}
    elif status == "unsupported":
        base["unsupported"] = {
            "kind": "primitive",
            "reason": "block RAM is not modelled",
            "primitives": [
                {
                    "gate_type": "RAMB18E1",
                    "reason": "not a flip-flop",
                    "count": 4,
                    "example_gates": [_gate(1701, "mem_inst/bram_0", "RAMB18E1")],
                }
            ],
        }
    base.update(overrides)
    return base


def document_with(findings, notes=None):
    return {
        "schema_version": "1.0.0",
        "generated_at": "2026-01-15T09:30:00Z",
        "producer": {"name": "test_hal_viz_report", "version": "1.0.0"},
        "artifacts": [dict(_ARTIFACT)],
        "analysis": {
            "plugin": {"name": "test_plugin", "version": "0.1.0"},
            "entry_point": "test.analyze",
        },
        "findings": list(findings),
        "notes": list(notes or []),
    }


class ReportTestCase(unittest.TestCase):
    """Base class with a temporary directory and a one-call render helper."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = self._tmp.name
        self.addCleanup(self._tmp.cleanup)

    def write_document(self, document, name="findings.json"):
        path = os.path.join(self.tmp, name)
        with open(path, "w", encoding="utf-8") as handle:
            json.dump(document, handle)
        return path

    def render(self, document, name="findings.json", artifacts=(), **options):
        """Write ``document``, render it, and return the HTML page."""
        path = self.write_document(document, name)
        loaded = report.load_documents([path])
        opts = report.ReportOptions(
            report_path=os.path.join(self.tmp, "report.html"), **options
        )
        page, builder = report.build_report(loaded, opts, artifacts)
        self.builder = builder
        self.loaded = loaded
        return page


# ---------------------------------------------------------------------------
# escaping
# ---------------------------------------------------------------------------


class TestEscaping(ReportTestCase):
    def test_text_escapes_every_html_metacharacter(self):
        escaped = report.text("<a href='x' onclick=\"y\">&")
        for raw in ("<", ">", '"', "'"):
            self.assertNotIn(raw, escaped)
        self.assertIn("&lt;a", escaped)
        self.assertIn("&#x27;", escaped)
        self.assertIn("&quot;", escaped)
        self.assertIn("&amp;", escaped)

    def test_text_neutralizes_control_characters(self):
        self.assertEqual(report.text("a\x00b\x1bc"), "a�b�c")
        # tab and newline are legitimate whitespace and survive
        self.assertEqual(report.text("a\tb\nc"), "a\tb\nc")

    def test_text_handles_non_strings_and_none(self):
        self.assertEqual(report.text(None), "")
        self.assertEqual(report.text(42), "42")

    def test_hostile_netlist_names_never_reach_the_page_raw(self):
        finding = finding_for("heuristic")
        finding["scope"] = _scope([_gate(7, HOSTILE_NAME, "LUT<6>")])
        finding["title"] = HOSTILE_NAME
        finding["summary"] = HOSTILE_NAME
        page = self.render(document_with([finding]))
        self.assertNotIn("<script>alert", page)
        self.assertNotIn("</script>", page)
        self.assertIn("&lt;script&gt;alert", page)
        self.assertIn("LUT&lt;6&gt;", page)

    def test_hostile_names_in_every_reference_position(self):
        finding = finding_for("unsupported")
        finding["unsupported"]["primitives"][0]["gate_type"] = HOSTILE_NAME
        finding["unsupported"]["primitives"][0]["example_gates"] = [
            _gate(9, HOSTILE_NAME, HOSTILE_NAME)
        ]
        finding["scope"]["nets"] = [
            {"artifact_id": "uart", "id": 3, "name": HOSTILE_NAME, "role": "clock"}
        ]
        finding["scope"]["modules"] = [
            {"artifact_id": "uart", "id": 1, "name": HOSTILE_NAME}
        ]
        finding["scope"]["gate_types"] = [HOSTILE_NAME]
        document = document_with([finding], notes=[HOSTILE_NAME])
        document["artifacts"][0]["design_name"] = HOSTILE_NAME
        document["artifacts"][0]["path"] = HOSTILE_NAME
        page = self.render(document)
        self.assertNotIn("<script>", page)
        self.assertGreater(page.count("&lt;script&gt;"), 3)

    def test_hostile_names_inside_attributes(self):
        # An unescaped name in a title="" attribute would let a quote escape it.
        finding = finding_for("unknown")
        finding["id"] = 'weird" onmouseover="alert(1)'
        page = self.render(document_with([finding]))
        self.assertNotIn('onmouseover="alert(1)"', page)
        self.assertIn("&quot;", page)


# ---------------------------------------------------------------------------
# statuses
# ---------------------------------------------------------------------------


class TestStatuses(ReportTestCase):
    ALL = (
        "proven_under_assumptions",
        "proven_bounded",
        "counterexample",
        "bounded_counterexample",
        "heuristic",
        "unknown",
        "timeout",
        "error",
        "unsupported",
    )

    def test_status_metadata_matches_the_schema_vocabulary(self):
        if findings_model is None:
            self.skipTest("hal_findings is not importable")
        self.assertEqual(set(report.STATUS_META), set(findings_model.STATUSES))
        self.assertEqual(set(self.ALL), set(findings_model.STATUSES))

    def test_fixtures_are_schema_valid(self):
        if findings_validate is None:
            self.skipTest("hal_findings is not importable")
        document = document_with([finding_for(status) for status in self.ALL])
        self.assertEqual(findings_validate.collect_errors(document), [])

    def test_all_nine_statuses_render_and_stay_distinguishable(self):
        page = self.render(document_with([finding_for(status) for status in self.ALL]))
        labels, glyphs, css = set(), set(), set()
        for status in self.ALL:
            meta = report.STATUS_META[status]
            self.assertIn(report.text(meta["label"]), page)
            self.assertIn('badge {}'.format(meta["css"]), page)
            self.assertIn("{}: {}".format(status, meta["claim"]).split(":")[0], page)
            labels.add(meta["label"])
            glyphs.add(meta["glyph"])
            css.add(meta["css"])
        # Colour alone must not carry the distinction: label, glyph and class are
        # all unique, so the nine are told apart in greyscale too.
        self.assertEqual(len(labels), 9)
        self.assertEqual(len(glyphs), 9)
        self.assertEqual(len(css), 9)

    def test_unbounded_proof_and_bounded_proof_are_not_the_same_badge(self):
        page = self.render(
            document_with([finding_for("proven_under_assumptions"), finding_for("proven_bounded")])
        )
        self.assertIn("PROVEN (bounded)", page)
        self.assertIn("BOUNDED: only up to 8 cycle(s)", page)
        self.assertIn("unbounded claim", page)

    def test_bounded_counterexample_shows_the_cycle_it_was_found_at(self):
        page = self.render(document_with([finding_for("bounded_counterexample")]))
        self.assertIn("witness found at cycle bound 5", page)
        self.assertIn("BOUNDED: only up to 12 cycle(s)", page)

    def test_inconclusive_results_stay_visible(self):
        page = self.render(
            document_with(
                [finding_for("unknown"), finding_for("timeout"), finding_for("error")]
            )
        )
        self.assertIn("no verdict was reached", page)
        self.assertIn("a resource limit was reached", page)
        self.assertIn("the plugin returned None", page)
        self.assertIn("timeout_s: 60", page)

    def test_unsupported_primitives_are_listed(self):
        page = self.render(document_with([finding_for("unsupported")]))
        self.assertIn("Not covered by this analysis", page)
        self.assertIn("RAMB18E1", page)
        self.assertIn("coverage gap", page)
        self.assertIn("mem_inst/bram_0", page)

    def test_unrecognized_status_is_flagged_not_hidden(self):
        finding = finding_for("heuristic")
        finding["status"] = "totally_new_status"
        page = self.render(document_with([finding]))
        self.assertIn("UNRECOGNIZED STATUS", page)
        self.assertIn("totally_new_status", page)

    def test_findings_are_ordered_worst_first(self):
        page = self.render(
            document_with(
                [
                    finding_for("proven_under_assumptions"),
                    finding_for("heuristic"),
                    finding_for("counterexample"),
                ]
            )
        )
        positions = [
            page.index("finding with status counterexample"),
            page.index("finding with status heuristic"),
            page.index("finding with status proven_under_assumptions"),
        ]
        self.assertEqual(positions, sorted(positions))

    def test_assumptions_are_shown_with_their_discharge_state(self):
        page = self.render(document_with([finding_for("proven_under_assumptions")]))
        self.assertIn("single clock domain", page)
        self.assertIn("assumed, not checked", page)

    def test_empty_assumption_list_says_so(self):
        page = self.render(document_with([finding_for("proven_bounded")]))
        self.assertIn("this claim is stated to rest on nothing", page)

    def test_shipped_examples_cover_all_nine_statuses(self):
        if not os.path.isdir(EXAMPLES_DIR):
            self.skipTest("hal_findings examples are not in this checkout")
        paths = sorted(
            os.path.join(EXAMPLES_DIR, name)
            for name in os.listdir(EXAMPLES_DIR)
            if name.endswith(".json")
        )
        loaded = report.load_documents(paths)
        options = report.ReportOptions(os.path.join(self.tmp, "examples.html"))
        page, builder = report.build_report(loaded, options)
        for document in loaded:
            self.assertEqual(document.validation_errors, [], document.path)
        seen = {
            finding["status"] for document in loaded for finding in document.findings
        }
        self.assertEqual(seen, set(self.ALL))
        for status in self.ALL:
            self.assertIn(report.STATUS_META[status]["label"], page)


# ---------------------------------------------------------------------------
# artifacts and evidence
# ---------------------------------------------------------------------------


class TestArtifacts(ReportTestCase):
    def _finding_with_evidence(self, *evidence):
        finding = finding_for("counterexample")
        finding["evidence"] = list(evidence)
        return finding

    def test_missing_artifact_is_marked_and_not_linked(self):
        finding = self._finding_with_evidence(
            {"kind": "waveform", "path": "traces/nothing_here.vcd"}
        )
        page = self.render(document_with([finding]))
        self.assertIn("artifact not found", page)
        self.assertIn("evidence-missing", page)
        self.assertNotIn('href="traces/nothing_here.vcd"', page)
        self.assertEqual(self.builder.missing_evidence, 1)

    def test_present_artifact_is_linked_relatively(self):
        os.makedirs(os.path.join(self.tmp, "traces"), exist_ok=True)
        witness = os.path.join(self.tmp, "traces", "witness.vcd")
        with open(witness, "w", encoding="utf-8") as handle:
            handle.write("$timescale 1ns $end\n")
        finding = self._finding_with_evidence(
            {"kind": "waveform", "path": "traces/witness.vcd", "description": "witness"}
        )
        page = self.render(document_with([finding]))
        self.assertIn('href="traces/witness.vcd"', page)
        self.assertIn("download", page)
        self.assertEqual(self.builder.missing_evidence, 0)

    def test_evidence_paths_resolve_relative_to_their_document(self):
        nested = os.path.join(self.tmp, "run1")
        os.makedirs(nested, exist_ok=True)
        with open(os.path.join(nested, "log.txt"), "w", encoding="utf-8") as handle:
            handle.write("log\n")
        finding = self._finding_with_evidence({"kind": "log", "path": "log.txt"})
        path = self.write_document(document_with([finding]), os.path.join("run1", "d.json"))
        loaded = report.load_documents([path])
        options = report.ReportOptions(os.path.join(self.tmp, "report.html"))
        page, builder = report.build_report(loaded, options)
        self.assertEqual(builder.missing_evidence, 0)
        self.assertIn('href="run1/log.txt"', page)

    def test_svg_evidence_is_embedded_and_sanitized(self):
        svg_path = os.path.join(self.tmp, "scoped.svg")
        with open(svg_path, "w", encoding="utf-8") as handle:
            handle.write(SVG_WITH_ACTIVE_CONTENT)
        finding = self._finding_with_evidence(
            {"kind": "file", "path": "scoped.svg", "media_type": "image/svg+xml"}
        )
        page = self.render(document_with([finding]))
        self.assertIn("<svg", page)
        self.assertIn("state_reg_0", page)  # the drawing itself survived
        self.assertNotIn("window.alert", page)
        self.assertNotIn("onload=", page)
        self.assertNotIn("example.invalid", page)
        self.assertEqual(self.builder.embedded, 1)

    def test_oversized_svg_is_linked_with_a_marker_not_embedded(self):
        svg_path = os.path.join(self.tmp, "big.svg")
        with open(svg_path, "w", encoding="utf-8") as handle:
            handle.write(SVG_WITH_ACTIVE_CONTENT)
        finding = self._finding_with_evidence({"kind": "file", "path": "big.svg"})
        page = self.render(document_with([finding]), max_embed_bytes=10)
        self.assertIn("--max-embed-bytes", page)
        self.assertIn('href="big.svg"', page)
        self.assertEqual(self.builder.embedded, 0)

    def test_no_embed_only_links(self):
        svg_path = os.path.join(self.tmp, "scoped.svg")
        with open(svg_path, "w", encoding="utf-8") as handle:
            handle.write(SVG_WITH_ACTIVE_CONTENT)
        finding = self._finding_with_evidence({"kind": "file", "path": "scoped.svg"})
        page = self.render(document_with([finding]), embed=False)
        self.assertIn("embedding disabled", page)
        self.assertNotIn("<svg", page)

    def test_dot_evidence_without_graphviz_is_marked_not_dropped(self):
        dot_path = os.path.join(self.tmp, "graph.dot")
        with open(dot_path, "w", encoding="utf-8") as handle:
            handle.write('digraph "g" { "a" -> "b"; }\n')
        finding = self._finding_with_evidence({"kind": "dot", "path": "graph.dot"})
        page = self.render(
            document_with([finding]),
            dot_binary=os.path.join(self.tmp, "no_such_dot_binary"),
        )
        self.assertIn("Graphviz", page)
        self.assertIn('href="graph.dot"', page)

    def test_dot_evidence_prefers_an_existing_rendered_sibling(self):
        with open(os.path.join(self.tmp, "graph.dot"), "w", encoding="utf-8") as handle:
            handle.write('digraph "g" { "a" -> "b"; }\n')
        with open(os.path.join(self.tmp, "graph.svg"), "w", encoding="utf-8") as handle:
            handle.write(SVG_WITH_ACTIVE_CONTENT)
        finding = self._finding_with_evidence({"kind": "dot", "path": "graph.dot"})
        page = self.render(
            document_with([finding]),
            dot_binary=os.path.join(self.tmp, "no_such_dot_binary"),
        )
        self.assertIn("<svg", page)
        self.assertIn('href="graph.svg"', page)
        self.assertEqual(self.builder.embedded, 1)

    def test_render_dot_never_leaves_the_dot_alone(self):
        with open(os.path.join(self.tmp, "graph.dot"), "w", encoding="utf-8") as handle:
            handle.write('digraph "g" { "a" -> "b"; }\n')
        finding = self._finding_with_evidence({"kind": "dot", "path": "graph.dot"})
        page = self.render(document_with([finding]), render_dot="never")
        self.assertNotIn("<svg", page)
        self.assertIn('href="graph.dot"', page)

    def test_extra_artifacts_are_attached(self):
        svg_path = os.path.join(self.tmp, "module_tree.svg")
        with open(svg_path, "w", encoding="utf-8") as handle:
            handle.write(SVG_WITH_ACTIVE_CONTENT)
        page = self.render(document_with([finding_for("heuristic")]), artifacts=[svg_path])
        self.assertIn("hal_viz artifacts", page)
        self.assertIn("module_tree.svg", page)
        self.assertEqual(self.builder.embedded, 1)

    def test_copy_evidence_makes_the_report_directory_portable(self):
        witness = os.path.join(self.tmp, "witness.vcd")
        with open(witness, "w", encoding="utf-8") as handle:
            handle.write("$timescale 1ns $end\n")
        finding = self._finding_with_evidence({"kind": "trace", "path": "witness.vcd"})
        page = self.render(document_with([finding]), copy_evidence=True)
        copied = os.path.join(self.tmp, "report_evidence", "000_witness.vcd")
        self.assertTrue(os.path.isfile(copied))
        self.assertIn("report_evidence/000_witness.vcd", page)

    def test_command_and_inline_evidence_are_shown(self):
        finding = self._finding_with_evidence(
            {"kind": "command", "command": ["hal", "--python-script", "check.py"]},
            {"kind": "inline", "inline": {"queries": 3}},
        )
        page = self.render(document_with([finding]))
        self.assertIn("hal --python-script check.py", page)
        self.assertIn("&quot;queries&quot;: 3", page)

    def test_unhashed_artifact_is_marked(self):
        document = document_with([finding_for("heuristic")])
        document["artifacts"][0].pop("sha256")
        document["artifacts"][0]["unhashed_reason"] = "netlist built in memory"
        page = self.render(document)
        self.assertIn("unhashed: netlist built in memory", page)


# ---------------------------------------------------------------------------
# truncation
# ---------------------------------------------------------------------------


class TestTruncation(ReportTestCase):
    def test_long_scopes_are_truncated_visibly(self):
        finding = finding_for("heuristic")
        finding["scope"] = _scope(
            [_gate(index + 1, "state_reg_{}".format(index)) for index in range(100)]
        )
        page = self.render(document_with([finding]), max_items=5)
        self.assertIn("TRUNCATED: 95 further gate(s) not shown", page)
        self.assertIn("100 gate(s) in scope", page)
        self.assertIn("state_reg_4", page)
        self.assertNotIn("state_reg_50", page)

    def test_witness_truncation_is_visible(self):
        finding = finding_for("bounded_counterexample")
        finding["counterexample"]["witness"] = [
            {"signal": "s{}".format(index), "value": "0", "cycle": index}
            for index in range(40)
        ]
        page = self.render(document_with([finding]), max_items=3)
        self.assertIn("TRUNCATED: 37 further witness entry(s) not shown", page)

    def test_nothing_is_truncated_below_the_limit(self):
        finding = finding_for("heuristic")
        finding["scope"] = _scope([_gate(1), _gate(2, "state_reg_1")])
        page = self.render(document_with([finding]), max_items=25)
        self.assertNotIn("TRUNCATED", page)

    def test_missing_witness_is_stated(self):
        finding = finding_for("counterexample")
        finding["counterexample"] = {
            "description": "outputs differ",
            "witness_available": False,
        }
        page = self.render(document_with([finding]))
        self.assertIn("no witness is available", page)


# ---------------------------------------------------------------------------
# sanitizing and offline behaviour
# ---------------------------------------------------------------------------


class TestSanitizeSvg(unittest.TestCase):
    def test_strips_scripts_handlers_and_remote_references(self):
        svg = report.sanitize_svg(SVG_WITH_ACTIVE_CONTENT)
        self.assertTrue(svg.startswith("<svg"))
        self.assertTrue(svg.endswith("</svg>"))
        self.assertNotIn("<script", svg)
        self.assertNotIn("window.alert", svg)
        self.assertNotIn("onload", svg)
        self.assertNotIn("example.invalid", svg)
        self.assertNotIn("<!DOCTYPE", svg)
        self.assertNotIn("<?xml", svg)
        self.assertIn('xlink:href="#local"', svg)
        self.assertIn("M0,0 L10,10", svg)

    def test_root_size_is_dropped_only_when_a_viewbox_exists(self):
        scalable = report.sanitize_svg(SVG_WITH_ACTIVE_CONTENT)
        self.assertNotIn('width="100pt"', scalable)
        fixed = report.sanitize_svg('<svg width="10pt" height="5pt"><g/></svg>')
        self.assertIn('width="10pt"', fixed)

    def test_javascript_urls_are_removed(self):
        svg = report.sanitize_svg(
            '<svg viewBox="0 0 1 1"><a href="javascript:alert(1)">x</a></svg>'
        )
        self.assertNotIn("javascript:", svg)

    def test_non_svg_input_is_rejected(self):
        self.assertIsNone(report.sanitize_svg(""))
        self.assertIsNone(report.sanitize_svg("<html><body>not an svg</body></html>"))

    def test_foreign_object_is_removed(self):
        svg = report.sanitize_svg(
            '<svg viewBox="0 0 1 1"><foreignObject><iframe src="http://x/"></iframe>'
            "</foreignObject><path d=\"M0 0\"/></svg>"
        )
        self.assertNotIn("iframe", svg)
        self.assertNotIn("foreignObject", svg)
        self.assertIn("M0 0", svg)


SCOPED_GRAPHVIZ_SVG = """<?xml version="1.0"?>
<svg xmlns="http://www.w3.org/2000/svg" width="60pt" height="30pt" viewBox="0 0 60 30">
<g id="graph0" class="graph"><title>netlist</title>
<g id="node1" class="node"><title>g10</title><ellipse cx="10" cy="10" rx="5" ry="5"/>
<text x="10" y="12">CLK_CNT</text></g>
<g id="node2" class="node"><title>g99</title><ellipse cx="40" cy="10" rx="5" ry="5"/></g>
<g id="edge1" class="edge"><title>g10&#45;&gt;g99</title><path d="M15,10 L35,10"/></g>
</g></svg>
"""


class TestScopedHighlight(ReportTestCase):
    def test_scope_labels_offer_both_hal_viz_ids_and_names(self):
        finding = finding_for("heuristic")
        finding["scope"] = _scope([_gate(10, "CLK_CNT_10_i_1_inst")])
        finding["scope"]["modules"] = [{"artifact_id": "uart", "id": 1, "name": "top"}]
        finding["scope"]["nets"] = [{"artifact_id": "uart", "id": 4, "name": "clk"}]
        labels = report.scope_labels(finding)
        self.assertEqual(labels, {"g10", "CLK_CNT_10_i_1_inst", "m1", "top", "clk"})

    def test_only_scoped_nodes_are_outlined(self):
        svg, matched = report.highlight_svg(SCOPED_GRAPHVIZ_SVG, {"g10"})
        self.assertEqual(matched, 1)
        self.assertIn('class="{} node"><title>g10</title>'.format(report.HIGHLIGHT_CLASS), svg)
        self.assertIn('class="node"><title>g99</title>', svg)

    def test_highlighting_is_a_no_op_without_labels(self):
        svg, matched = report.highlight_svg(SCOPED_GRAPHVIZ_SVG, set())
        self.assertEqual(matched, 0)
        self.assertEqual(svg, SCOPED_GRAPHVIZ_SVG)

    def test_embedded_diagram_is_highlighted_for_its_finding(self):
        with open(os.path.join(self.tmp, "scoped.svg"), "w", encoding="utf-8") as handle:
            handle.write(SCOPED_GRAPHVIZ_SVG)
        finding = finding_for("heuristic")
        finding["scope"] = _scope([_gate(10, "CLK_CNT_10_i_1_inst")])
        finding["evidence"] = [{"kind": "file", "path": "scoped.svg"}]
        page = self.render(document_with([finding]))
        self.assertIn(report.HIGHLIGHT_CLASS, page)
        self.assertIn("1 node(s) of the finding scope are outlined", page)
        self.assertIn(".{} ellipse".format(report.HIGHLIGHT_CLASS), page)

    def test_a_diagram_that_does_not_match_the_scope_says_so(self):
        with open(os.path.join(self.tmp, "other.svg"), "w", encoding="utf-8") as handle:
            handle.write(SCOPED_GRAPHVIZ_SVG)
        finding = finding_for("heuristic")
        finding["scope"] = _scope([_gate(4242, "somewhere_else")])
        finding["evidence"] = [{"kind": "file", "path": "other.svg"}]
        page = self.render(document_with([finding]))
        self.assertIn("nothing could be outlined", page)
        self.assertIn("may not be the scoped view of this finding", page)

    def test_extra_artifacts_are_not_highlighted(self):
        path = os.path.join(self.tmp, "module_tree.svg")
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(SCOPED_GRAPHVIZ_SVG)
        page = self.render(document_with([finding_for("heuristic")]), artifacts=[path])
        self.assertNotIn("nothing could be outlined", page)


class TestOffline(ReportTestCase):
    def test_page_makes_no_external_request(self):
        svg_path = os.path.join(self.tmp, "scoped.svg")
        with open(svg_path, "w", encoding="utf-8") as handle:
            handle.write(SVG_WITH_ACTIVE_CONTENT)
        finding = finding_for("counterexample", id="test/with-evidence")
        finding["evidence"] = [{"kind": "file", "path": "scoped.svg"}]
        page = self.render(
            document_with([finding] + [finding_for(s) for s in TestStatuses.ALL]),
            artifacts=[svg_path],
        )
        lowered = page.lower()
        # XML namespace URIs are identifiers, not fetches; everything else that
        # looks like a URL would be an external request and must not be there.
        without_namespaces = re.sub(r'xmlns(:\w+)?="[^"]*"', "", lowered)
        self.assertNotIn("<script", lowered)
        self.assertNotIn("http://", without_namespaces)
        self.assertNotIn("https://", without_namespaces)
        self.assertNotIn("<link ", lowered)
        self.assertNotIn('src="//', lowered)
        self.assertNotIn("@import", lowered)
        # styles are inline, so exactly one <style> block and no stylesheet link
        self.assertEqual(lowered.count("<style>"), 1)

    def test_page_is_well_formed_enough_to_parse(self):
        from html.parser import HTMLParser

        class Parser(HTMLParser):
            def __init__(self):
                HTMLParser.__init__(self)
                self.tags = []

            def handle_starttag(self, tag, attrs):
                self.tags.append(tag)

        page = self.render(document_with([finding_for(s) for s in TestStatuses.ALL]))
        parser = Parser()
        parser.feed(page)
        self.assertIn("section", parser.tags)
        self.assertIn("table", parser.tags)
        self.assertNotIn("script", parser.tags)


class TestPaths(unittest.TestCase):
    def test_relative_href_is_url_quoted_and_uses_forward_slashes(self):
        base = os.path.abspath(os.path.join("a", "b"))
        target = os.path.join(base, "c d", "e#f.svg")
        href = report.relative_href(target, base)
        self.assertEqual(href, "c%20d/e%23f.svg")

    def test_relative_href_can_walk_up(self):
        base = os.path.abspath(os.path.join("a", "b"))
        target = os.path.abspath(os.path.join("a", "x.svg"))
        self.assertEqual(report.relative_href(target, base), "../x.svg")

    def test_resolve_path_honours_absolute_evidence_paths(self):
        absolute = os.path.abspath(os.path.join(os.sep, "tmp", "x.vcd"))
        self.assertEqual(report.resolve_path(absolute, "/elsewhere"), os.path.normpath(absolute))
        self.assertEqual(
            report.resolve_path("x.vcd", os.path.join("a", "b")),
            os.path.normpath(os.path.join("a", "b", "x.vcd")),
        )


# ---------------------------------------------------------------------------
# document loading and the CLI
# ---------------------------------------------------------------------------


class TestLoading(ReportTestCase):
    def test_invalid_document_is_reported_in_the_page(self):
        document = document_with([finding_for("heuristic")])
        # a heuristic that claims to hold for every execution is exactly the
        # confusion the schema exists to prevent
        document["findings"][0]["bounds"] = {"unbounded": True}
        page = self.render(document)
        if self.loaded[0].validated:
            self.assertIn("does not validate against the hal_findings schema", page)
            self.assertTrue(self.loaded[0].validation_errors)

    def test_unreadable_document_raises_a_readable_error(self):
        missing = os.path.join(self.tmp, "nope.json")
        with self.assertRaises(report.ReportError):
            report.load_document(missing)

    def test_non_json_document_raises_a_readable_error(self):
        path = os.path.join(self.tmp, "broken.json")
        with open(path, "w", encoding="utf-8") as handle:
            handle.write("{not json")
        with self.assertRaises(report.ReportError) as caught:
            report.load_document(path)
        self.assertIn("not valid JSON", str(caught.exception))

    def test_json_that_is_not_a_document_raises(self):
        path = os.path.join(self.tmp, "list.json")
        with open(path, "w", encoding="utf-8") as handle:
            handle.write("[1, 2, 3]")
        with self.assertRaises(report.ReportError):
            report.load_document(path)

    def test_document_without_findings_still_renders(self):
        page = self.render(document_with([]))
        self.assertIn("no findings", page.lower())


class TestCli(ReportTestCase):
    def _run(self, argv):
        return cli.main(argv)

    def test_report_subcommand_writes_a_page(self):
        path = self.write_document(
            document_with([finding_for(status) for status in TestStatuses.ALL])
        )
        out = os.path.join(self.tmp, "out", "report.html")
        self.assertEqual(self._run(["report", path, "-o", out, "-q"]), 0)
        self.assertTrue(os.path.isfile(out))
        with open(out, encoding="utf-8") as handle:
            page = handle.read()
        self.assertIn("<!doctype html>", page)
        self.assertIn("HAL findings report", page)

    def test_output_directory_gets_a_default_name(self):
        path = self.write_document(document_with([finding_for("heuristic")]))
        out_dir = os.path.join(self.tmp, "out") + os.sep
        self.assertEqual(self._run(["report", path, "-o", out_dir, "-q"]), 0)
        self.assertTrue(os.path.isfile(os.path.join(self.tmp, "out", "findings_report.html")))

    def test_extension_is_added_when_missing(self):
        self.assertTrue(
            cli._resolve_report_output(os.path.join(self.tmp, "r")).endswith("r.html")
        )
        self.assertTrue(
            cli._resolve_report_output(os.path.join(self.tmp, "r.htm")).endswith("r.htm")
        )

    def test_multiple_documents_are_merged_into_one_page(self):
        first = self.write_document(document_with([finding_for("heuristic")]), "a.json")
        second = self.write_document(document_with([finding_for("error")]), "b.json")
        out = os.path.join(self.tmp, "both.html")
        self.assertEqual(self._run(["report", first, second, "-o", out, "-q"]), 0)
        with open(out, encoding="utf-8") as handle:
            page = handle.read()
        self.assertIn("a.json", page)
        self.assertIn("b.json", page)
        self.assertIn("2 document(s)", page)

    def test_strict_fails_on_an_invalid_document_but_still_writes_it(self):
        document = document_with([finding_for("heuristic")])
        document["findings"][0]["bounds"] = {"unbounded": True}
        path = self.write_document(document, "invalid.json")
        out = os.path.join(self.tmp, "strict.html")
        code = self._run(["report", path, "-o", out, "--strict", "-q"])
        self.assertTrue(os.path.isfile(out))
        loaded = report.load_document(path)
        self.assertEqual(code, 1 if loaded.validation_errors else 0)

    def test_missing_document_exits_one_with_a_message(self):
        code = self._run(
            ["report", os.path.join(self.tmp, "gone.json"), "-o", os.path.join(self.tmp, "x.html")]
        )
        self.assertEqual(code, 1)

    def test_report_needs_no_hal(self):
        # The subcommand must not take --hal-lib: it never imports hal_py.
        parser = cli.build_parser()
        args = parser.parse_args(["report", "doc.json"])
        self.assertFalse(hasattr(args, "hal_lib"))
        self.assertTrue(callable(args.func))


if __name__ == "__main__":
    unittest.main()
