// Generated by tools/hal_agilex from a Quartus Prime Pro EDA netlist export.
// Load with the AGILEX_TENNM gate library.
// source: pwm_generator.vo
// Inversions on ALM data inputs were absorbed into lut_mask; tri1 nets became wires tied to 1'b1.

module pwm_generator (pwm_out, period_tick, clk, rst_n, run, cfg_wdata, cfg_we, cfg_addr);
output pwm_out;
output period_tick;
input clk;
input rst_n;
input run;
input [7:0] cfg_wdata;
input cfg_we;
input [1:0] cfg_addr;
wire \LessThan_0~12_cout ;
wire \LessThan_0~17_cout ;
wire \LessThan_0~1_sumout ;
wire \LessThan_0~1_wirecell_combout ;
wire \LessThan_0~22_cout ;
wire \LessThan_0~27_cout ;
wire \LessThan_0~7_cout ;
wire \add_0~11_sumout ;
wire \add_0~12 ;
wire \add_0~16_sumout ;
wire \add_0~17 ;
wire \add_0~1_sumout ;
wire \add_0~21_sumout ;
wire \add_0~22 ;
wire \add_0~26_sumout ;
wire \add_0~27 ;
wire \add_0~31_sumout ;
wire \add_0~32 ;
wire \add_0~6_sumout ;
wire \add_0~7 ;
wire [7:0] cnt;
wire \cnt[0]~0_combout ;
wire devclrn;
wire devoe;
wire devpor;
wire [7:0] duty;
wire \duty_we~0_combout ;
wire gnd;
wire \reduce_nor_1~0_combout ;
wire \reduce_nor_1~combout ;
wire unknown;
wire vcc;

assign gnd = 1'b0;
assign vcc = 1'b1;
// dropped: assign unknown = 1'bx;  (declared by Quartus, read by nothing)
assign devclrn = 1'b1;
assign devpor = 1'b1;
assign devoe = 1'b1;
assign pwm_out = \LessThan_0~1_wirecell_combout ;
assign period_tick = \reduce_nor_1~combout ;

tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000FFFF), .shared_arith ("off")) \LessThan_0~1  (.cin (\LessThan_0~7_cout ), .dataa (gnd), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\LessThan_0~1_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000F0F0), .shared_arith ("off")) \add_0~1  (.cin (\add_0~7 ), .dataa (gnd), .datab (gnd), .datac (cnt[7]), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~1_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000F0F0), .shared_arith ("off")) \add_0~6  (.cin (\add_0~12 ), .cout (\add_0~7 ), .dataa (gnd), .datab (gnd), .datac (cnt[6]), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~6_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000F0F0), .shared_arith ("off")) \add_0~11  (.cin (\add_0~17 ), .cout (\add_0~12 ), .dataa (gnd), .datab (gnd), .datac (cnt[5]), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~11_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000F0F0), .shared_arith ("off")) \add_0~16  (.cin (\add_0~22 ), .cout (\add_0~17 ), .dataa (gnd), .datab (gnd), .datac (cnt[4]), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~16_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000F0F0), .shared_arith ("off")) \add_0~21  (.cin (\add_0~27 ), .cout (\add_0~22 ), .dataa (gnd), .datab (gnd), .datac (cnt[3]), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~21_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000F0F0), .shared_arith ("off")) \add_0~26  (.cin (\add_0~32 ), .cout (\add_0~27 ), .dataa (gnd), .datab (gnd), .datac (cnt[2]), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~26_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h00000000F0000FF0), .shared_arith ("off")) \add_0~31  (.cin (gnd), .cout (\add_0~32 ), .dataa (gnd), .datab (gnd), .datac (cnt[1]), .datad (cnt[0]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (\add_0~31_sumout ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000004D449009), .shared_arith ("off")) \LessThan_0~7  (.cin (\LessThan_0~12_cout ), .cout (\LessThan_0~7_cout ), .dataa (cnt[7]), .datab (duty[7]), .datac (cnt[6]), .datad (duty[6]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0000000000F0F00F), .shared_arith ("off")) \LessThan_0~12  (.cin (\LessThan_0~17_cout ), .cout (\LessThan_0~12_cout ), .dataa (gnd), .datab (gnd), .datac (duty[5]), .datad (cnt[5]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000004D449009), .shared_arith ("off")) \LessThan_0~17  (.cin (\LessThan_0~22_cout ), .cout (\LessThan_0~17_cout ), .dataa (cnt[4]), .datab (duty[4]), .datac (cnt[3]), .datad (duty[3]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0000000000F0F00F), .shared_arith ("off")) \LessThan_0~22  (.cin (\LessThan_0~27_cout ), .cout (\LessThan_0~22_cout ), .dataa (gnd), .datab (gnd), .datac (duty[2]), .datad (cnt[2]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000004D449009), .shared_arith ("off")) \LessThan_0~27  (.cin (gnd), .cout (\LessThan_0~27_cout ), .dataa (cnt[1]), .datab (duty[1]), .datac (cnt[0]), .datad (duty[0]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \cnt[7]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\add_0~1_sumout ), .devclrn (devclrn), .devpor (devpor), .ena (run), .q (cnt[7]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \cnt[6]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\add_0~6_sumout ), .devclrn (devclrn), .devpor (devpor), .ena (run), .q (cnt[6]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \cnt[5]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\add_0~11_sumout ), .devclrn (devclrn), .devpor (devpor), .ena (run), .q (cnt[5]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \cnt[4]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\add_0~16_sumout ), .devclrn (devclrn), .devpor (devpor), .ena (run), .q (cnt[4]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \cnt[3]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\add_0~21_sumout ), .devclrn (devclrn), .devpor (devpor), .ena (run), .q (cnt[3]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \cnt[2]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\add_0~26_sumout ), .devclrn (devclrn), .devpor (devpor), .ena (run), .q (cnt[2]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \cnt[1]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\add_0~31_sumout ), .devclrn (devclrn), .devpor (devpor), .ena (run), .q (cnt[1]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \cnt[0]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\cnt[0]~0_combout ), .devclrn (devclrn), .devpor (devpor), .ena (run), .q (cnt[0]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8000800080008000), .shared_arith ("off")) \reduce_nor_1~0  (.cin (gnd), .combout (\reduce_nor_1~0_combout ), .dataa (cnt[3]), .datab (cnt[2]), .datac (cnt[1]), .datad (cnt[0]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8000000080000000), .shared_arith ("off")) reduce_nor_1 (.cin (gnd), .combout (\reduce_nor_1~combout ), .dataa (cnt[7]), .datab (cnt[6]), .datac (cnt[5]), .datad (cnt[4]), .datae (\reduce_nor_1~0_combout ), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \duty[7]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (cfg_wdata[7]), .devclrn (devclrn), .devpor (devpor), .ena (\duty_we~0_combout ), .q (duty[7]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0808080808080808), .shared_arith ("off")) \duty_we~0  (.cin (gnd), .combout (\duty_we~0_combout ), .dataa (cfg_we), .datab (cfg_addr[0]), .datac (cfg_addr[1]), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \duty[6]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (cfg_wdata[6]), .devclrn (devclrn), .devpor (devpor), .ena (\duty_we~0_combout ), .q (duty[6]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \duty[5]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (cfg_wdata[5]), .devclrn (devclrn), .devpor (devpor), .ena (\duty_we~0_combout ), .q (duty[5]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \duty[4]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (cfg_wdata[4]), .devclrn (devclrn), .devpor (devpor), .ena (\duty_we~0_combout ), .q (duty[4]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \duty[3]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (cfg_wdata[3]), .devclrn (devclrn), .devpor (devpor), .ena (\duty_we~0_combout ), .q (duty[3]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \duty[2]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (cfg_wdata[2]), .devclrn (devclrn), .devpor (devpor), .ena (\duty_we~0_combout ), .q (duty[2]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \duty[1]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (cfg_wdata[1]), .devclrn (devclrn), .devpor (devpor), .ena (\duty_we~0_combout ), .q (duty[1]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \duty[0]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (cfg_wdata[0]), .devclrn (devclrn), .devpor (devpor), .ena (\duty_we~0_combout ), .q (duty[0]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) \cnt[0]~0  (.cin (gnd), .combout (\cnt[0]~0_combout ), .dataa (cnt[0]), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) \LessThan_0~1_wirecell  (.cin (gnd), .combout (\LessThan_0~1_wirecell_combout ), .dataa (\LessThan_0~1_sumout ), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));

endmodule
