// parity_counter -- the fault-campaign fixture.
//
// Hand written against plugins/gate_libraries/definitions/example_library.hgl
// (the library examples/uart.zip ships), in the same flat gate-level style as
// examples/uart.zip's uart.v, so HAL's Verilog parser reads it with no extra
// support.  Nine registers, three deliberately different fates:
//
//   CNT_reg_0..2   a 3-bit up counter, protected by PAR_reg, which carries the
//   PAR_reg        parity of the *next* counter value.  ERR = PAR ^ CNT0 ^ CNT1
//                  ^ CNT2 is 0 in every fault-free cycle, so a flip in any of
//                  the four raises ERR in the very cycle it happens.
//                  -> DETECTED, latency 0.
//
//   AUX_reg        a toggle flip-flop driving AUX_O directly. Nothing checks
//                  it. A flip inverts AUX_O for the injection cycle and, since
//                  its next state is the inverse of its (corrupted) output,
//                  inverts the whole toggle sequence from then on.
//                  -> SILENT DIVERGENCE, latency 0, permanent.
//
//   PIPE_reg_0..3  a four-deep shift register from PIPE_IN to PIPE_O. A flip in
//                  stage k reaches PIPE_O after 3-k cycles, so with a short
//                  observation window an early stage is UNOBSERVED and a late
//                  one is a SILENT DIVERGENCE -- the same fault model, the same
//                  design, a different window. That contrast is the fixture's
//                  whole point: unobserved is a property of the window, not a
//                  masking claim.
//
// All nine registers are FFR (async reset on R) driven from the RST primary
// input.  That matters: driven through NetlistSimulatorController there is no
// way to preload sequential state (initialize_sequential_gates is not on the
// controller), so the reset is what makes the run deterministic instead of
// starting every register at X.
//
// Ground truth for a specific workload lives in ground_truth.json, generated by
// reference_model.py, which models this file independently of HAL.

module parity_counter (
  CLK,
  RST,
  PIPE_IN,
  CNT0,
  CNT1,
  CNT2,
  AUX_O,
  PIPE_O,
  ERR
 ) ;
  input CLK ;
  input RST ;
  input PIPE_IN ;
  output CNT0 ;
  output CNT1 ;
  output CNT2 ;
  output AUX_O ;
  output PIPE_O ;
  output ERR ;
  wire const0 ;
  wire const1 ;
  wire cnt0_next ;
  wire cnt1_next ;
  wire cnt2_next ;
  wire carry01 ;
  wire par ;
  wire par_next ;
  wire par_next_01 ;
  wire err_01 ;
  wire err_012 ;
  wire aux_next ;
  wire pipe1 ;
  wire pipe2 ;
  wire pipe3 ;

GND const0_inst (
  .\O (const0 )
 ) ;
VCC const1_inst (
  .\O (const1 )
 ) ;

// ---- 3-bit counter next state -------------------------------------------
INV cnt0_next_inst (
  .\I (CNT0 ),
  .\O (cnt0_next )
 ) ;
XOR cnt1_next_inst (
  .\I0 (CNT1 ),
  .\I1 (CNT0 ),
  .\O (cnt1_next )
 ) ;
AND2 carry01_inst (
  .\I0 (CNT0 ),
  .\I1 (CNT1 ),
  .\O (carry01 )
 ) ;
XOR cnt2_next_inst (
  .\I0 (CNT2 ),
  .\I1 (carry01 ),
  .\O (cnt2_next )
 ) ;

// ---- parity of the next counter value ------------------------------------
XOR par_next_01_inst (
  .\I0 (cnt0_next ),
  .\I1 (cnt1_next ),
  .\O (par_next_01 )
 ) ;
XOR par_next_inst (
  .\I0 (par_next_01 ),
  .\I1 (cnt2_next ),
  .\O (par_next )
 ) ;

// ---- the detector: parity of the counter must equal the parity register ---
XOR err_01_inst (
  .\I0 (CNT0 ),
  .\I1 (CNT1 ),
  .\O (err_01 )
 ) ;
XOR err_012_inst (
  .\I0 (err_01 ),
  .\I1 (CNT2 ),
  .\O (err_012 )
 ) ;
XOR err_inst (
  .\I0 (err_012 ),
  .\I1 (par ),
  .\O (ERR )
 ) ;

// ---- unprotected toggle register -----------------------------------------
INV aux_next_inst (
  .\I (AUX_O ),
  .\O (aux_next )
 ) ;

// ---- registers ------------------------------------------------------------
FFR #(.INIT(1'h0))
CNT_reg_0_inst (
  .\C (CLK ),
  .\CE (const1 ),
  .\D (cnt0_next ),
  .\R (RST ),
  .\Q (CNT0 )
 ) ;
FFR #(.INIT(1'h0))
CNT_reg_1_inst (
  .\C (CLK ),
  .\CE (const1 ),
  .\D (cnt1_next ),
  .\R (RST ),
  .\Q (CNT1 )
 ) ;
FFR #(.INIT(1'h0))
CNT_reg_2_inst (
  .\C (CLK ),
  .\CE (const1 ),
  .\D (cnt2_next ),
  .\R (RST ),
  .\Q (CNT2 )
 ) ;
FFR #(.INIT(1'h0))
PAR_reg_inst (
  .\C (CLK ),
  .\CE (const1 ),
  .\D (par_next ),
  .\R (RST ),
  .\Q (par )
 ) ;
FFR #(.INIT(1'h0))
AUX_reg_inst (
  .\C (CLK ),
  .\CE (const1 ),
  .\D (aux_next ),
  .\R (RST ),
  .\Q (AUX_O )
 ) ;
FFR #(.INIT(1'h0))
PIPE_reg_0_inst (
  .\C (CLK ),
  .\CE (const1 ),
  .\D (PIPE_IN ),
  .\R (RST ),
  .\Q (pipe1 )
 ) ;
FFR #(.INIT(1'h0))
PIPE_reg_1_inst (
  .\C (CLK ),
  .\CE (const1 ),
  .\D (pipe1 ),
  .\R (RST ),
  .\Q (pipe2 )
 ) ;
FFR #(.INIT(1'h0))
PIPE_reg_2_inst (
  .\C (CLK ),
  .\CE (const1 ),
  .\D (pipe2 ),
  .\R (RST ),
  .\Q (pipe3 )
 ) ;
FFR #(.INIT(1'h0))
PIPE_reg_3_inst (
  .\C (CLK ),
  .\CE (const1 ),
  .\D (pipe3 ),
  .\R (RST ),
  .\Q (PIPE_O )
 ) ;

endmodule
