// Generated by tools/hal_agilex from a Quartus Prime Pro EDA netlist export.
// Load with the AGILEX_TENNM gate library.
// source: lfsr_prng.vo
// Inversions on ALM data inputs were absorbed into lut_mask; tri1 nets became wires tied to 1'b1.

module lfsr_prng (rand_out, bit_out, clk, rst_n, en);
output [15:0] rand_out;
output bit_out;
input clk;
input rst_n;
input en;
wire devclrn;
wire devoe;
wire devpor;
wire \feedback~combout ;
wire gnd;
wire [15:0] state;
wire \state[0]~_wirecell_combout ;
wire \state[10]~3_combout ;
wire \state[10]~_wirecell_combout ;
wire \state[11]~_wirecell_combout ;
wire \state[12]~4_combout ;
wire \state[13]~5_combout ;
wire \state[13]~_wirecell_combout ;
wire \state[14]~6_combout ;
wire \state[15]~7_combout ;
wire \state[15]~_wirecell_combout ;
wire \state[1]~0_combout ;
wire \state[5]~1_combout ;
wire \state[5]~_wirecell_combout ;
wire \state[6]~_wirecell_combout ;
wire \state[7]~_wirecell_combout ;
wire \state[8]~2_combout ;
wire unknown;
wire vcc;

assign gnd = 1'b0;
assign vcc = 1'b1;
// dropped: assign unknown = 1'bx;  (declared by Quartus, read by nothing)
assign devclrn = 1'b1;
assign devpor = 1'b1;
assign devoe = 1'b1;
assign rand_out[0] = \state[0]~_wirecell_combout ;
assign rand_out[10] = \state[10]~_wirecell_combout ;
assign rand_out[11] = \state[11]~_wirecell_combout ;
assign rand_out[13] = \state[13]~_wirecell_combout ;
assign rand_out[15] = \state[15]~_wirecell_combout ;
assign bit_out = \state[15]~_wirecell_combout ;
assign rand_out[5] = \state[5]~_wirecell_combout ;
assign rand_out[6] = \state[6]~_wirecell_combout ;
assign rand_out[7] = \state[7]~_wirecell_combout ;
assign rand_out[12] = state[12];
assign rand_out[14] = state[14];
assign rand_out[1] = state[1];
assign rand_out[2] = state[2];
assign rand_out[3] = state[3];
assign rand_out[4] = state[4];
assign rand_out[8] = state[8];
assign rand_out[9] = state[9];

tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \state[0]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\feedback~combout ), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (state[0]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \state[1]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\state[1]~0_combout ), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (state[1]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \state[2]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (state[1]), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (state[2]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \state[3]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (state[2]), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (state[3]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \state[4]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (state[3]), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (state[4]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \state[5]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\state[5]~1_combout ), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (state[5]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \state[6]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (state[5]), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (state[6]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \state[7]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (state[6]), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (state[7]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \state[8]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\state[8]~2_combout ), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (state[8]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \state[9]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (state[8]), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (state[9]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \state[10]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\state[10]~3_combout ), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (state[10]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \state[11]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (state[10]), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (state[11]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \state[12]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\state[12]~4_combout ), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (state[12]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \state[13]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\state[13]~5_combout ), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (state[13]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \state[14]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\state[14]~6_combout ), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (state[14]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) \state[15]  (.aload (gnd), .asdata (vcc), .clk (clk), .clrn (rst_n), .d (\state[15]~7_combout ), .devclrn (devclrn), .devpor (devpor), .ena (en), .q (state[15]), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h6996699669966996), .shared_arith ("off")) feedback (.cin (gnd), .combout (\feedback~combout ), .dataa (state[3]), .datab (state[12]), .datac (state[14]), .datad (state[15]), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) \state[1]~0  (.cin (gnd), .combout (\state[1]~0_combout ), .dataa (state[0]), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) \state[5]~1  (.cin (gnd), .combout (\state[5]~1_combout ), .dataa (state[4]), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) \state[8]~2  (.cin (gnd), .combout (\state[8]~2_combout ), .dataa (state[7]), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) \state[10]~3  (.cin (gnd), .combout (\state[10]~3_combout ), .dataa (state[9]), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) \state[12]~4  (.cin (gnd), .combout (\state[12]~4_combout ), .dataa (state[11]), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) \state[13]~5  (.cin (gnd), .combout (\state[13]~5_combout ), .dataa (state[12]), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) \state[14]~6  (.cin (gnd), .combout (\state[14]~6_combout ), .dataa (state[13]), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) \state[15]~7  (.cin (gnd), .combout (\state[15]~7_combout ), .dataa (state[14]), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) \state[0]~_wirecell  (.cin (gnd), .combout (\state[0]~_wirecell_combout ), .dataa (state[0]), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) \state[10]~_wirecell  (.cin (gnd), .combout (\state[10]~_wirecell_combout ), .dataa (state[10]), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) \state[11]~_wirecell  (.cin (gnd), .combout (\state[11]~_wirecell_combout ), .dataa (state[11]), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) \state[13]~_wirecell  (.cin (gnd), .combout (\state[13]~_wirecell_combout ), .dataa (state[13]), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) \state[15]~_wirecell  (.cin (gnd), .combout (\state[15]~_wirecell_combout ), .dataa (state[15]), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) \state[5]~_wirecell  (.cin (gnd), .combout (\state[5]~_wirecell_combout ), .dataa (state[5]), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) \state[6]~_wirecell  (.cin (gnd), .combout (\state[6]~_wirecell_combout ), .dataa (state[6]), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) \state[7]~_wirecell  (.cin (gnd), .combout (\state[7]~_wirecell_combout ), .dataa (state[7]), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));

endmodule
