// Structurally identical to netlist.hal.v with every design-specific identifier
// removed, internal vectors split into unrelated scalars and both instance and
// net numbering scrambled (see anonymize.py).  This is the file the walkthrough
// analyses: what a netlist looks like when the vendor tool did not hand you the
// RTL names.
// Load with the AGILEX_TENNM gate library.

module top (port_o0, port_o1, port_o2, port_o3, port_o4, port_i0, port_i1, port_i2);
output [7:0] port_o0;
output port_o1;
output port_o2;
output port_o3;
output [3:0] port_o4;
input port_i0;
input port_i1;
input port_i2;
wire n135 ;
wire n90 ;
wire n45 ;
wire n0 ;
wire n91 ;
wire n46 ;
wire n1 ;
wire n92 ;
wire n47 ;
wire n2 ;
wire n93 ;
wire n48 ;
wire n3 ;
wire n94 ;
wire n49 ;
wire n4 ;
wire n95 ;
wire n50 ;
wire n5 ;
wire n96 ;
wire n51 ;
wire n6 ;
wire n97 ;
wire n52 ;
wire n7 ;
wire n98 ;
wire n53 ;
wire n8 ;
wire n99 ;
wire n54 ;
wire n9 ;
wire n100 ;
wire n55 ;
wire n10;
wire n101;
wire n56;
wire n11;
wire n102;
wire n57;
wire n12;
wire n103;
wire n58;
wire n13;
wire n104;
wire n59;
wire n14;
wire n105;
wire n60;
wire n15;
wire n106;
wire n61;
wire n16;
wire n107 ;
wire n62 ;
wire n17;
wire n108;
wire n63;
wire n18;
wire n109;
wire n64;
wire n19;
wire n110;
wire devclrn;
wire devoe;
wire devpor;
wire n65 ;
wire n20 ;
wire gnd;
wire n111 ;
wire n66 ;
wire n21 ;
wire n112 ;
wire n67 ;
wire n22 ;
wire n113 ;
wire n68 ;
wire n23 ;
wire n114 ;
wire n69 ;
wire n24 ;
wire n115 ;
wire n70 ;
wire n25 ;
wire n116 ;
wire n71 ;
wire n26 ;
wire n117 ;
wire n72 ;
wire n27 ;
wire n118 ;
wire n73 ;
wire n28 ;
wire n119 ;
wire n74 ;
wire n29 ;
wire n120 ;
wire n75 ;
wire n30 ;
wire n121 ;
wire n76 ;
wire n31 ;
wire n122 ;
wire n77 ;
wire n32 ;
wire n123;
wire n78;
wire n33;
wire n124;
wire n79;
wire n34;
wire n125;
wire n80;
wire n35 ;
wire n126 ;
wire n81 ;
wire n36 ;
wire n127 ;
wire n82 ;
wire n37 ;
wire n128 ;
wire n83 ;
wire n38;
wire n129;
wire n84;
wire n39;
wire n130;
wire n85;
wire n40;
wire n131;
wire n86;
wire n41;
wire n132;
wire n87;
wire n42 ;
wire n133 ;
wire n88 ;
wire n43 ;
wire n134 ;
wire n89 ;
wire unknown;
wire n44 ;
wire vcc;

assign gnd = 1'b0;
assign vcc = 1'b1;
// dropped: assign unknown = 1'bx;  (declared by Quartus, read by nothing)
assign devclrn = 1'b1;
assign devpor = 1'b1;
assign devoe = 1'b1;
assign port_o3 = n65 ;
assign port_o2 = n81 ;
assign link___bit_state_0__ = n42 ;
assign port_o1 = n44 ;
assign port_o0[0] = n110;
assign port_o0[1] = n63;
assign port_o0[2] = n64;
assign port_o0[3] = n17;
assign port_o0[4] = n18;
assign port_o0[5] = n19;
assign port_o0[6] = n108;
assign port_o0[7] = n109;
assign link___bit_state_1__ = n132;
assign link___bit_state_2__ = n41;
assign link___bit_state_3__ = n86;

tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000F0F0), .shared_arith ("off")) u3  (.cin (n93 ), .cout (n91 ), .dataa (gnd), .datab (gnd), .datac (n12), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (n0 ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000F0F0), .shared_arith ("off")) u10  (.cin (n51 ), .cout (n53 ), .dataa (gnd), .datab (gnd), .datac (n58), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (n98 ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000F0F0), .shared_arith ("off")) u17  (.cin (n45 ), .dataa (gnd), .datab (gnd), .datac (n102), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (n135 ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000F0F0), .shared_arith ("off")) u24  (.cin (n47 ), .cout (n45 ), .dataa (gnd), .datab (gnd), .datac (n13), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (n90 ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000F0F0), .shared_arith ("off")) u31  (.cin (n53 ), .cout (n1 ), .dataa (gnd), .datab (gnd), .datac (n11), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (n46 ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000F0F0), .shared_arith ("off")) u38  (.cin (n1 ), .cout (n47 ), .dataa (gnd), .datab (gnd), .datac (n60), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (n92 ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000F0F0), .shared_arith ("off")) u45  (.cin (n3 ), .cout (n93 ), .dataa (gnd), .datab (gnd), .datac (n59), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (n2 ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000F0F0), .shared_arith ("off")) u52  (.cin (n49 ), .cout (n3 ), .dataa (gnd), .datab (gnd), .datac (n10), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (n48 ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000F0F0), .shared_arith ("off")) u59  (.cin (n5 ), .cout (n49 ), .dataa (gnd), .datab (gnd), .datac (n57), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (n94 ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h00000000F0F00F0F), .shared_arith ("off")) u66  (.cin (gnd), .cout (n95 ), .dataa (gnd), .datab (gnd), .datac (n15), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (n4 ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000F0F0), .shared_arith ("off")) u73  (.cin (n95 ), .cout (n5 ), .dataa (gnd), .datab (gnd), .datac (n104), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (n50 ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000F0F0), .shared_arith ("off")) u80  (.cin (n97 ), .cout (n51 ), .dataa (gnd), .datab (gnd), .datac (n105), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (n96 ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000F0F0), .shared_arith ("off")) u87  (.cin (n7 ), .cout (n97 ), .dataa (gnd), .datab (gnd), .datac (n56), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (n6 ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000F0F0), .shared_arith ("off")) u94  (.cin (n9 ), .cout (n7 ), .dataa (gnd), .datab (gnd), .datac (n103), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (n52 ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000F0F0), .shared_arith ("off")) u101  (.cin (n91 ), .cout (n99 ), .dataa (gnd), .datab (gnd), .datac (n101), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (n8 ));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h000000000000F0F0), .shared_arith ("off")) u108  (.cin (n99 ), .cout (n9 ), .dataa (gnd), .datab (gnd), .datac (n14), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd), .sumout (n54 ));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u115  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (port_i0), .devclrn (devclrn), .devpor (devpor), .ena (n88 ), .q (n110), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u2  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n131), .devclrn (devclrn), .devpor (devpor), .ena (n88 ), .q (n63), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u9  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n84), .devclrn (devclrn), .devpor (devpor), .ena (n88 ), .q (n64), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u16  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n85), .devclrn (devclrn), .devpor (devpor), .ena (n88 ), .q (n17), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u23  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n38), .devclrn (devclrn), .devpor (devpor), .ena (n88 ), .q (n18), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u30  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n39), .devclrn (devclrn), .devpor (devpor), .ena (n88 ), .q (n19), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u37  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n40), .devclrn (devclrn), .devpor (devpor), .ena (n88 ), .q (n108), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u44  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n129), .devclrn (devclrn), .devpor (devpor), .ena (n88 ), .q (n109), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u51 (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n88 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n44 ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u58 (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n122 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n81 ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u65 (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n111 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n65 ), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u72  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n66 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n87), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u79  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n67 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n132), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u86  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n21 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n41), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u93  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n112 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n86), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u100  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (port_i0), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n131), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u107  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n131), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n84), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u114  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n84), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n85), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u1  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n85), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n38), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u8  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n38), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n39), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u15  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n39), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n40), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u22  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n40), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n129), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0808080808080808), .shared_arith ("off")) u29 (.cin (gnd), .combout (n122 ), .dataa (n62 ), .datab (n133 ), .datac (n20 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hFFFFCE0AFFFFCE0A), .shared_arith ("off")) u36  (.cin (gnd), .combout (n111 ), .dataa (n62 ), .datab (n43 ), .datac (n133 ), .datad (n126 ), .datae (n20 ), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0E0E0E0E0E0E0E0E), .shared_arith ("off")) u43 (.cin (gnd), .combout (n66 ), .dataa (n87), .datab (n133 ), .datac (n134 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h50DC50DC50DC50DC), .shared_arith ("off")) u50 (.cin (gnd), .combout (n67 ), .dataa (n87), .datab (n132), .datac (n133 ), .datad (n77 ), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0CAE0CAE0CAE0CAE), .shared_arith ("off")) u57  (.cin (gnd), .combout (n21 ), .dataa (n41), .datab (n43 ), .datac (n126 ), .datad (n32 ), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hF2F2F2F2F2F2F2F2), .shared_arith ("off")) u64  (.cin (gnd), .combout (n112 ), .dataa (n86), .datab (n77 ), .datac (n89 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8888888888888888), .shared_arith ("off")) u71 (.cin (gnd), .combout (n88 ), .dataa (n41), .datab (n107 ), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8888888888888888), .shared_arith ("off")) u78 (.cin (gnd), .combout (n62 ), .dataa (n86), .datab (n107 ), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8000800080008000), .shared_arith ("off")) u85  (.cin (gnd), .combout (n36 ), .dataa (n131), .datab (n84), .datac (n85), .datad (n38), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0040000000400000), .shared_arith ("off")) u92 (.cin (gnd), .combout (n133 ), .dataa (port_i0), .datab (n39), .datac (n40), .datad (n129), .datae (n36 ), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u99  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n23 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n12), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u106  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n116 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n58), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u113  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n71 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n102), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u0  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n26 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n13), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u7  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n117 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n11), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u14  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n72 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n60), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8000800080008000), .shared_arith ("off")) u21  (.cin (gnd), .combout (n37 ), .dataa (n102), .datab (n13), .datac (n11), .datad (n60), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u28  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n27 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n59), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u35  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n118 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n10), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u42  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n73 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n57), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u49  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n28 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n15), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u56  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n114 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n104), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8000000080000000), .shared_arith ("off")) u63  (.cin (gnd), .combout (n128 ), .dataa (n59), .datab (n10), .datac (n57), .datad (n15), .datae (n104), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u70  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n69 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n105), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u77  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n24 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n56), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u84  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n115 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n103), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u91  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n70 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n101), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u98  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n25 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n14), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8000000080000000), .shared_arith ("off")) u105  (.cin (gnd), .combout (n83 ), .dataa (n105), .datab (n56), .datac (n103), .datad (n101), .datae (n14), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8000000080000000), .shared_arith ("off")) u112 (.cin (gnd), .combout (n20 ), .dataa (n12), .datab (n58), .datac (n37 ), .datad (n128 ), .datae (n83 ), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8888888888888888), .shared_arith ("off")) u119 (.cin (gnd), .combout (n43 ), .dataa (n132), .datab (n107 ), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0001000100010001), .shared_arith ("off")) u6  (.cin (gnd), .combout (n127 ), .dataa (n131), .datab (n84), .datac (n85), .datad (n38), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0001000000010000), .shared_arith ("off")) u13 (.cin (gnd), .combout (n126 ), .dataa (port_i0), .datab (n39), .datac (n40), .datad (n129), .datae (n127 ), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hFFEAFFEAFFEAFFEA), .shared_arith ("off")) u20 (.cin (gnd), .combout (n134 ), .dataa (n62 ), .datab (n43 ), .datac (n126 ), .datad (n20 ), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hEEEEEEEEEEEEEEEE), .shared_arith ("off")) u27 (.cin (gnd), .combout (n77 ), .dataa (n107 ), .datab (n20 ), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hF8F8F8F8F8F8F8F8), .shared_arith ("off")) u34 (.cin (gnd), .combout (n32 ), .dataa (n88 ), .datab (n35 ), .datac (n20 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0808080808080808), .shared_arith ("off")) u41 (.cin (gnd), .combout (n89 ), .dataa (n88 ), .datab (n35 ), .datac (n20 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u48  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n22 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n61), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u55  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n113 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n106), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u62  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n68 ), .devclrn (devclrn), .devpor (devpor), .ena (vcc), .q (n16), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h8080808080808080), .shared_arith ("off")) u69 (.cin (gnd), .combout (n107 ), .dataa (n61), .datab (n106), .datac (n16), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0808080808080808), .shared_arith ("off")) u76  (.cin (gnd), .combout (n23 ), .dataa (n87), .datab (n0 ), .datac (n20 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2020202020202020), .shared_arith ("off")) u83  (.cin (gnd), .combout (n116 ), .dataa (n87), .datab (n20 ), .datac (n98 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2020202020202020), .shared_arith ("off")) u90  (.cin (gnd), .combout (n71 ), .dataa (n87), .datab (n20 ), .datac (n135 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2020202020202020), .shared_arith ("off")) u97  (.cin (gnd), .combout (n26 ), .dataa (n87), .datab (n20 ), .datac (n90 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2020202020202020), .shared_arith ("off")) u104  (.cin (gnd), .combout (n117 ), .dataa (n87), .datab (n20 ), .datac (n46 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2020202020202020), .shared_arith ("off")) u111  (.cin (gnd), .combout (n72 ), .dataa (n87), .datab (n20 ), .datac (n92 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0808080808080808), .shared_arith ("off")) u118  (.cin (gnd), .combout (n27 ), .dataa (n87), .datab (n2 ), .datac (n20 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0808080808080808), .shared_arith ("off")) u5  (.cin (gnd), .combout (n118 ), .dataa (n87), .datab (n48 ), .datac (n20 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0808080808080808), .shared_arith ("off")) u12  (.cin (gnd), .combout (n73 ), .dataa (n87), .datab (n94 ), .datac (n20 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0808080808080808), .shared_arith ("off")) u19  (.cin (gnd), .combout (n28 ), .dataa (n87), .datab (n4 ), .datac (n20 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0808080808080808), .shared_arith ("off")) u26  (.cin (gnd), .combout (n114 ), .dataa (n87), .datab (n50 ), .datac (n20 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2020202020202020), .shared_arith ("off")) u33  (.cin (gnd), .combout (n69 ), .dataa (n87), .datab (n20 ), .datac (n96 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2020202020202020), .shared_arith ("off")) u40  (.cin (gnd), .combout (n24 ), .dataa (n87), .datab (n20 ), .datac (n6 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2020202020202020), .shared_arith ("off")) u47  (.cin (gnd), .combout (n115 ), .dataa (n87), .datab (n20 ), .datac (n52 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0808080808080808), .shared_arith ("off")) u54  (.cin (gnd), .combout (n70 ), .dataa (n87), .datab (n8 ), .datac (n20 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0808080808080808), .shared_arith ("off")) u61  (.cin (gnd), .combout (n25 ), .dataa (n87), .datab (n54 ), .datac (n20 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u68  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n119 ), .devclrn (devclrn), .devpor (devpor), .ena (n74 ), .q (n125), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u75  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n29 ), .devclrn (devclrn), .devpor (devpor), .ena (n74 ), .q (n124), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u82  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n120 ), .devclrn (devclrn), .devpor (devpor), .ena (n74 ), .q (n78), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u89  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n75 ), .devclrn (devclrn), .devpor (devpor), .ena (n74 ), .q (n79), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u96  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n30 ), .devclrn (devclrn), .devpor (devpor), .ena (n74 ), .q (n123), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u103  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n121 ), .devclrn (devclrn), .devpor (devpor), .ena (n74 ), .q (n34), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u110  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n76 ), .devclrn (devclrn), .devpor (devpor), .ena (n74 ), .q (n80), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_ff #(.is_wysiwyg ("true"), .power_up ("dont_care")) u117  (.aload (gnd), .asdata (vcc), .clk (port_i1), .clrn (port_i2), .d (n31 ), .devclrn (devclrn), .devpor (devpor), .ena (n74 ), .q (n33), .sclr (gnd), .sclr1 (gnd), .sload (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0010001000100010), .shared_arith ("off")) u4  (.cin (gnd), .combout (n82 ), .dataa (n123), .datab (n34), .datac (n80), .datad (n33), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0001000000010000), .shared_arith ("off")) u11 (.cin (gnd), .combout (n35 ), .dataa (n125), .datab (n124), .datac (n78), .datad (n79), .datae (n82 ), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2888288828882888), .shared_arith ("off")) u18  (.cin (gnd), .combout (n22 ), .dataa (n87), .datab (n61), .datac (n106), .datad (n16), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2222222222222222), .shared_arith ("off")) u25  (.cin (gnd), .combout (n113 ), .dataa (n87), .datab (n106), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h2828282828282828), .shared_arith ("off")) u32  (.cin (gnd), .combout (n68 ), .dataa (n87), .datab (n106), .datac (n16), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h0001000100010001), .shared_arith ("off")) u39  (.cin (gnd), .combout (n100 ), .dataa (n123), .datab (n34), .datac (n80), .datad (n33), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h4444444444444444), .shared_arith ("off")) u46  (.cin (gnd), .combout (n55 ), .dataa (n124), .datab (n100 ), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hAA3CAA3CAA3CAA3C), .shared_arith ("off")) u53  (.cin (gnd), .combout (n119 ), .dataa (n39), .datab (n125), .datac (n55 ), .datad (n43 ), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hEEEEEEEEEEEEEEEE), .shared_arith ("off")) u60  (.cin (gnd), .combout (n74 ), .dataa (n88 ), .datab (n43 ), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hAA3CAA3CAA3CAA3C), .shared_arith ("off")) u67  (.cin (gnd), .combout (n29 ), .dataa (n38), .datab (n124), .datac (n100 ), .datad (n43 ), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hAAAAC3F0AAAAC3F0), .shared_arith ("off")) u74  (.cin (gnd), .combout (n120 ), .dataa (n40), .datab (n125), .datac (n78), .datad (n55 ), .datae (n43 ), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hAAAAAAAAFC03FF00), .shared_arith ("off")) u81  (.cin (gnd), .combout (n75 ), .dataa (n129), .datab (n125), .datac (n78), .datad (n79), .datae (n55 ), .dataf (n43 ), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hAAAAAAAACCCCCCC3), .shared_arith ("off")) u88  (.cin (gnd), .combout (n30 ), .dataa (n85), .datab (n123), .datac (n34), .datad (n80), .datae (n33), .dataf (n43 ), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hAAAACCC3AAAACCC3), .shared_arith ("off")) u95  (.cin (gnd), .combout (n121 ), .dataa (n84), .datab (n34), .datac (n80), .datad (n33), .datae (n43 ), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hA3A3A3A3A3A3A3A3), .shared_arith ("off")) u102  (.cin (gnd), .combout (n76 ), .dataa (port_i0), .datab (n80), .datac (n43 ), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'hAAC3AAC3AAC3AAC3), .shared_arith ("off")) u109  (.cin (gnd), .combout (n31 ), .dataa (n131), .datab (n80), .datac (n33), .datad (n43 ), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));
tennm_lcell_comb #(.extended_lut ("off"), .lut_mask (64'h5555555555555555), .shared_arith ("off")) u116  (.cin (gnd), .combout (n42 ), .dataa (n87), .datab (gnd), .datac (gnd), .datad (gnd), .datae (gnd), .dataf (gnd), .datag (gnd), .datah (gnd), .sharein (gnd));

endmodule
