/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module chip(io_6_0_0, io_7_0_1, io_8_31_1);
  input io_6_0_0;
  wire io_6_0_0;
  output io_7_0_1;
  wire io_7_0_1;
  wire io_7_0_1_SB_DFFESR_Q_D;
  wire io_7_0_1_SB_DFFESR_Q_E;
  input io_8_31_1;
  wire io_8_31_1;
  wire n17;
  wire n2;
  wire n20;
  wire n22;
  wire n23;
  wire n24;
  wire n2_SB_DFFESR_Q_D;
  wire n2_SB_DFFESR_Q_E;
  wire n3;
  wire n3_SB_DFFESR_Q_D;
  wire n3_SB_DFFESR_Q_E;
  wire n4;
  wire n4_SB_DFFESR_Q_D;
  wire n4_SB_DFFESR_Q_E;
  wire [3:0] n4_SB_LUT4_I2_O;
  wire n5;
  wire n5_SB_DFFESR_Q_D;
  wire n5_SB_DFFESR_Q_E;
  wire n6;
  wire n6_SB_DFFESR_Q_D;
  wire n6_SB_DFFESR_Q_E;
  wire n7;
  wire n7_SB_DFFESR_Q_D;
  wire n7_SB_DFFESR_Q_E;
  wire [1:0] n7_SB_LUT4_I2_O;
  wire n9;
  SB_DFFESR io_7_0_1_SB_DFFESR_Q (
    .C(io_6_0_0),
    .D(io_7_0_1_SB_DFFESR_Q_D),
    .E(io_7_0_1_SB_DFFESR_Q_E),
    .Q(io_7_0_1),
    .R(io_8_31_1)
  );
  SB_LUT4 #(
    .LUT_INIT(16'hfff0)
  ) io_7_0_1_SB_DFFESR_Q_E_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(n7_SB_LUT4_I2_O[0]),
    .I3(io_8_31_1),
    .O(io_7_0_1_SB_DFFESR_Q_E)
  );
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) io_7_0_1_SB_LUT4_I3 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(io_7_0_1),
    .O(io_7_0_1_SB_DFFESR_Q_D)
  );
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) n20_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(n9),
    .O(n20)
  );
  SB_DFFESR n2_SB_DFFESR_Q (
    .C(io_6_0_0),
    .D(n2_SB_DFFESR_Q_D),
    .E(n2_SB_DFFESR_Q_E),
    .Q(n2),
    .R(io_8_31_1)
  );
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) n2_SB_DFFESR_Q_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(n2),
    .O(n2_SB_DFFESR_Q_D)
  );
  SB_LUT4 #(
    .LUT_INIT(16'hfff0)
  ) n2_SB_DFFESR_Q_E_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(io_8_31_1),
    .I3(n9),
    .O(n2_SB_DFFESR_Q_E)
  );
  SB_DFFESR n3_SB_DFFESR_Q (
    .C(io_6_0_0),
    .D(n3_SB_DFFESR_Q_D),
    .E(n3_SB_DFFESR_Q_E),
    .Q(n3),
    .R(io_8_31_1)
  );
  SB_LUT4 #(
    .LUT_INIT(16'hffc0)
  ) n3_SB_DFFESR_Q_E_SB_LUT4_O (
    .I0(1'h0),
    .I1(n9),
    .I2(n2),
    .I3(io_8_31_1),
    .O(n3_SB_DFFESR_Q_E)
  );
  SB_LUT4 #(
    .LUT_INIT(16'hff80)
  ) n3_SB_LUT4_I0 (
    .I0(n3),
    .I1(n9),
    .I2(n2),
    .I3(io_8_31_1),
    .O(n4_SB_DFFESR_Q_E)
  );
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) n3_SB_LUT4_I3 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(n3),
    .O(n3_SB_DFFESR_Q_D)
  );
  SB_DFFESR n4_SB_DFFESR_Q (
    .C(io_6_0_0),
    .D(n4_SB_DFFESR_Q_D),
    .E(n4_SB_DFFESR_Q_E),
    .Q(n4),
    .R(io_8_31_1)
  );
  SB_LUT4 #(
    .LUT_INIT(16'h8000)
  ) n4_SB_LUT4_I2 (
    .I0(n9),
    .I1(n2),
    .I2(n4),
    .I3(n3),
    .O(n4_SB_LUT4_I2_O[0])
  );
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) n4_SB_LUT4_I3 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(n4),
    .O(n4_SB_DFFESR_Q_D)
  );
  SB_DFFESR n5_SB_DFFESR_Q (
    .C(io_6_0_0),
    .D(n5_SB_DFFESR_Q_D),
    .E(n5_SB_DFFESR_Q_E),
    .Q(n5),
    .R(io_8_31_1)
  );
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) n5_SB_DFFESR_Q_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(n5),
    .O(n5_SB_DFFESR_Q_D)
  );
  SB_LUT4 #(
    .LUT_INIT(16'hfff0)
  ) n5_SB_DFFESR_Q_E_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(n4_SB_LUT4_I2_O[0]),
    .I3(io_8_31_1),
    .O(n5_SB_DFFESR_Q_E)
  );
  SB_DFFESR n6_SB_DFFESR_Q (
    .C(io_6_0_0),
    .D(n6_SB_DFFESR_Q_D),
    .E(n6_SB_DFFESR_Q_E),
    .Q(n6),
    .R(io_8_31_1)
  );
  SB_LUT4 #(
    .LUT_INIT(16'hffc0)
  ) n6_SB_DFFESR_Q_E_SB_LUT4_O (
    .I0(1'h0),
    .I1(n4_SB_LUT4_I2_O[0]),
    .I2(n5),
    .I3(io_8_31_1),
    .O(n6_SB_DFFESR_Q_E)
  );
  SB_LUT4 #(
    .LUT_INIT(16'hff80)
  ) n6_SB_LUT4_I0 (
    .I0(n6),
    .I1(n4_SB_LUT4_I2_O[0]),
    .I2(n5),
    .I3(io_8_31_1),
    .O(n7_SB_DFFESR_Q_E)
  );
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) n6_SB_LUT4_I3 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(n6),
    .O(n6_SB_DFFESR_Q_D)
  );
  SB_DFFESR n7_SB_DFFESR_Q (
    .C(io_6_0_0),
    .D(n7_SB_DFFESR_Q_D),
    .E(n7_SB_DFFESR_Q_E),
    .Q(n7),
    .R(io_8_31_1)
  );
  SB_LUT4 #(
    .LUT_INIT(16'h8000)
  ) n7_SB_LUT4_I2 (
    .I0(n4_SB_LUT4_I2_O[0]),
    .I1(n5),
    .I2(n7),
    .I3(n6),
    .O(n7_SB_LUT4_I2_O[0])
  );
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) n7_SB_LUT4_I3 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(n7),
    .O(n7_SB_DFFESR_Q_D)
  );
  SB_DFFSR n9_SB_DFFSR_Q (
    .C(io_6_0_0),
    .D(n20),
    .Q(n9),
    .R(io_8_31_1)
  );
  assign n4_SB_LUT4_I2_O[3:1] = { n6, n7, n5 };
  assign n7_SB_LUT4_I2_O[1] = io_8_31_1;
  assign n17 = n9;
  assign n22 = 1'h0;
  assign n23 = 1'h0;
  assign n24 = 1'h1;
endmodule
